[core]
copyFrom:ROOT:/DATA/total/forcesAttack.template, ROOT:/DATA/Terran/terranUpgrades.template, ROOT:/DATA/total/debuffs.template, ROOT:/DATA/total/customUI.template, ROOT:/DATA/total/unit_portrait.template
name: medic
tags: medic,bio,S,unit,vis17,groundUnit
isBuilder:true
canRepairBuildings:false
canRepairUnits:true
class: CustomUnitMetadata
price:Gas=75
maxHp: 340
armour:1
energyMax:200
energyRegen:0.0124
energyStartingPercentage:0.3
mass: 500
displayText_ru: Медик
displayText: Medic
displayText_zh:医疗兵
techLevel: 1
buildSpeed: 8.9s
#availableInDemo: true
radius: 12
hideScorchMark: true
displayRadius: 14
isBio: true
isBug: false
isUnrepairableUnit: false
softCollisionOnAll: 5
transportSlotsNeeded: 1
nanoRange:80
nanoRepairSpeed:0.31
fogOfWarSightRange:17
autoRepair:true
canRepairUnitsOnlyWithTags: bio
effectOnDeath:CUSTOM:corpse
soundOnMoveOrder:medic_yes_1.ogg:0.3,medic_yes_2.ogg:0.3,medic_yes_3.ogg:0.3,medic_yes_4.ogg:0.3
soundOnAttackOrder:medic_yes_1.ogg:0.3,medic_yes_2.ogg:0.3,medic_yes_3.ogg:0.3,medic_yes_4.ogg:0.3
soundOnNewSelection:medic_what_1.ogg:0.3,medic_what_2.ogg:0.3,medic_what_3.ogg:0.3,medic_what_4.ogg:0.3

@memory restoration:unit

[hiddenAction_autoRepair]
requireConditional: if select(self.hp(full=true),numberOfUnitsInTeam(withTag='repairInfantry',withinRange=200)>0,numberOfUnitsInTeam(withTag='repairInfantry',withinRange=200)>1) or self.numberOfUnitsInAllyNotOwnTeam(withTag='repairInfantry',withinRange=200)>0
autoTrigger: if self.hasActiveWaypoint(type='attackmove') or not self.hasActiveWaypoint() or self.hasActiveWaypoint(type='attack')
addWaypoint_target_randomUnit_tagged: repairInfantry
addWaypoint_target_randomUnit_team: ally
addWaypoint_target_randomUnit_maxRange: 200
addWaypoint_type:repair
addWaypoint_prepend: true
addWaypoint_triggerActionIfFailed: autoRepair

[hiddenAction_healing]
autoTrigger: if self.hasActiveWaypoint(type="repair") and distanceBetween(self,activeWaypointTarget)<=${core.nanoRange} and self.queueSize(withActionTag="rechargeHeal")==0 and self.resource.maelstrom<=0 and self.resource.stasis<=0
addResources:energy=-1
setUnitStats: nanoRange=select(self.energy>=1,${core.nanoRange},0),  moveSpeed=select(self.energy>=1,${movement.moveSpeed},0)
alsoQueueAction:healing_recharge
alsoTriggerOrQueueActionConditional: if self.energy<1

[hiddenAction_healing_recharge]
tags:rechargeHeal
buildSpeed:1s
addResources:energy=1
whenBuilding_cannotMove:true
whenBuilding_playAnimation:idle
setUnitStats: nanoRange=${core.nanoRange}, moveSpeed=${movement.moveSpeed}

[hiddenAction_repairForMedic]
autoTrigger: if not self.hp(full=true) and not self.tags(includes='repairInfantry')
temporarilyAddTags:repairInfantry

[hiddenAction_notRepairForMedic]
autoTrigger: if self.hp(full=true) and self.tags(includes='repairInfantry')
temporarilyRemoveTags:repairInfantry

[hiddenAction_guardForAI]
autoTrigger: if self.isControlledByAI() and not self.hasActiveWaypoint(type='repair') and numberOfUnitsInTeam(withTag='infantry',withinRange=200,lessThan=1)
addWaypoint_type: touchTarget
clearAllWaypoints:true
addWaypoint_target_nearestUnit_team:own
addWaypoint_target_nearestUnit_tagged:infantry

[hiddenAction_soundOnCreate]
autoTriggerOnEvent: created
playSoundToPlayer:medic_ready.wav
requireConditional:if self.customTarget1!=nullUnit
addWaypoint_type:move
addWaypoint_target_fromReference: customTarget1.readUnitMemory(name="rally",type="unit")

[action_restoration]
isVisible: if self.globalTeamTags(includes='Restoration')
isActive: if self.resource.maelstrom<=0 and self.resource.stasis<=0 and memory.restoration==null
alwaysSinglePress:true
price:energy=50
displayType:infoOnly
buildSpeed:0s
text_ru:Восстановление
text:Restoration
text_zh:治疗
isGuiBlinking: if memory.restoration!=null
onlyOneUnitAtATime: true
fireTurretXAtGround:null
fireTurretXAtGround_withProjectile:null
ai_isDisabled: true
iconExtraColor:#FFFFFFFF
iconExtraImage:ROOT:/DATA/Terran/restoration_icon.png
addResources:energy=50
alsoTriggerAction:restoration_2
alsoTriggerOrQueueActionConditional: if createMarker(x=thisActionTarget.x,y=thisActionTarget.y,teamId=self.teamId).nearestUnit(withinRange=40, withTag='unit', relation='ally') != nullUnit and thisActionTarget.nearestUnit(withinRange=40, withTag='unit', relation='ally') != self and (createMarker(x=thisActionTarget.x,y=thisActionTarget.y,teamId=self.teamId).nearestUnit(withinRange=40, withTag='unit', relation='ally').resource.ensnare>0 or createMarker(x=thisActionTarget.x,y=thisActionTarget.y,teamId=self.teamId).nearestUnit(withinRange=40, withTag='unit', relation='ally').resource.plague>0 or createMarker(x=thisActionTarget.x,y=thisActionTarget.y,teamId=self.teamId).nearestUnit(withinRange=40, withTag='unit', relation='ally').resource.lockdown>0 or createMarker(x=thisActionTarget.x,y=thisActionTarget.y,teamId=self.teamId).nearestUnit(withinRange=40, withTag='unit', relation='ally').resource.acidSpores>0 or createMarker(x=thisActionTarget.x,y=thisActionTarget.y,teamId=self.teamId).nearestUnit(withinRange=40, withTag='unit', relation='ally').resource.maelstrom>0)

[hiddenAction_restoration_2]
addWaypoint_type: touchTarget
clearAllWaypoints:true
addWaypoint_target_fromReference: createMarker(x=thisActionTarget.x,y=thisActionTarget.y,teamId=self.teamId).nearestUnit(withinRange=40, withTag='unit', relation='ally')
setUnitMemory: restoration=createMarker(x=thisActionTarget.x,y=thisActionTarget.y,teamId=self.teamId).nearestUnit(withinRange=40, withTag='unit', relation='ally')

[hiddenAction_restoration_3]
autoTrigger: if memory.restoration!=nullUnit and memory.restoration.hp>0 and distanceBetween(self, memory.restoration)<=100 and self.energy>=50 and self.resource.stasis<=0
sendMessageTo: memory.restoration
sendMessageWithTags:Restoration
clearAllWaypoints:true
addResources:energy=-50
alsoTriggerAction:removeRestoration

[hiddenAction_removeRestoration]
autoTriggerOnEvent:newWaypointGivenByPlayer
requireConditional: if memory.restoration!=nullUnit
autoTrigger: if memory.restoration!=nullUnit and (self.energy<50 or memory.restoration.hp<=0)
setUnitMemory: restoration=null

[hiddenAction_armour]
@copyFromSection:template_set_armour
@define armourUpgradeType: TerranInfantryArmor

[hiddenAction_maxEnergy]
autoTrigger: if self.globalTeamTags(includes='CaduceusReactor') and self.maxEnergy!=250
temporarilyAddTags: maxEnergy
setUnitStats: maxEnergy=250

[hiddenAction_startingEnergy]
autoTriggerOnEvent:created
requireConditional: if self.globalTeamTags(includes='CaduceusReactor')
setUnitStats:energy=62

[effect_corpse]
alwayStartDirAtZero:true
attachedToUnit: false
life: 50
alpha: 5
image: death.png
priority: critical
drawUnderUnits: true
total_frames:5
animateFrameStart:0
animateFrameEnd:4
animateFrameSpeed:0.2
alsoPlaySound:death.ogg

[action_portrait]
unitShownInUI:portrait_medic

[graphics]
image_offsetY:-10
total_frames: 10
icon_build: medic_icon.png
image:        medic.png
image_wreak:  dead.png
image_turret: NONE
image_shadow:ROOT:/DATA/total/shadow.png
animation_moving_start: 0
animation_moving_end: 7
animation_moving_speed: 3
repairEffect: NONE
lock_body_rotation_with_main_turret: true
drawLayer:experimentals
rotate_with_direction: false
animation_direction_units: 45
animation_direction_strideX:0
animation_direction_strideY:1
animation_direction_starting:180
frame_width:  64
frame_height: 64

[attack]
aimOffsetSpread:0
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
isMelee:true
isFixedFiring: true
turretSize: 8
turretTurnSpeed: 3
showRangeUIGuide:false
maxAttackRange:70

[turret_1]
x: 0
y: 0
isMainNanoTurret:true
canShoot:false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
recoilOffset: 0
shoot_flame:NONE
energyUsage:1
showRangeUIGuide:false
onShoot_freezeBodyMovementFor:0.63s

[turret_null]
x: 0
y: 0
limitingRange:9999
canShoot: false
projectile:null
showRangeUIGuide:false

[projectile_null]
life:0
speed:0
invisible: true
directDamage: 0
explodeEffect:NONE
explodeEffectOnShield:NONE

[movement]
movementType: LAND
moveSpeed: 1.1904
moveAccelerationSpeed: 20
moveDecelerationSpeed: 20
maxTurnSpeed: 40
turnAcceleration: 40
moveSlidingMode: false
moveIgnoringBody:true
reverseSpeedPercentage:0
joinsGroupFormations: false

[ai]
buildPriority: 0.8
noneInBaseExtraPriority: 0.8
noneGlobalExtraPriority: 0.8
maxEachBase: 10

[animation_idle]
body_0s: {frame:0}
body_2s: {frame:0}

[animation_repair]
onActions : repair
body_0s: {frame:8}
body_0.03s: {frame:9}
body_0.06s: {frame:9}

[hiddenAction_debuff_lockdown]
@copyFrom_skipThisSection: true

[hiddenAction_removeDebuff_lockdown]
@copyFrom_skipThisSection: true

[decal_grn_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByOwnPlayer:true
image:ROOT:/DATA/total/circle_smll_grn.png

[decal_red_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByEnemyPlayer:true
image:ROOT:/DATA/total/circle_smll_red.png

[decal_yellow_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByAllyNotOwnPlayer:true
image:ROOT:/DATA/total/circle_smll_yell.png

[decal_hp]
@copyFromSection: template_customBar
@define totalFrames:5
image:ROOT:/DATA/total/hp_6.png
frame_width:19
frame_height:5
frame:int((self.hp*100/self.maxHp)/(100/${totalFrames}))
yOffsetAbsolute:14

[decal_energy]
@copyFromSection: template_customBar
@define totalFrames:6
onlyWhenSelectedByOwnPlayer:true
onlyWhenSelectedByAnyPlayer:false
image:ROOT:/DATA/total/energy_6.png
frame_width:19
frame_height:5
frame:int((self.energy*100/self.maxEnergy)/(100/${totalFrames}))
yOffsetAbsolute:20