[core]
copyFrom:ROOT:/DATA/total/forcesAttack.template, ROOT:/DATA/Terran/terranUpgrades.template, ROOT:/DATA/total/debuffs.template, ROOT:/DATA/total/customUI.template, ROOT:/DATA/total/unit_portrait.template
name: marine
tags: bio,bunkerBio,marine,S,unit,infantry,vis17,groundUnit
class: CustomUnitMetadata
price:Gas=70
maxHp: 290
energyMax:0
energyRegen:-0.0166666666666
mass: 500
displayText_ru: Морпех
displayText: Marine
displayText_zh:陆战队员
techLevel: 1
buildSpeed: 7.5s
radius: 12
hideScorchMark: false
displayRadius: 14
isBio: true
isBug: false
isUnrepairableUnit: false
softCollisionOnAll: 5
fogOfWarSightRange:17
transportSlotsNeeded: 1
effectOnDeath:CUSTOM:corpse
soundOnMoveOrder:marine_yes_1.ogg:0.3,marine_yes_2.ogg:0.3,marine_yes_3.ogg:0.3,marine_yes_4.ogg:0.3
soundOnAttackOrder:marine_yes_1.ogg:0.3,marine_yes_2.ogg:0.3,marine_yes_3.ogg:0.3,marine_yes_4.ogg:0.3
soundOnNewSelection:marine_what_1.ogg:0.3,marine_what_2.ogg:0.3,marine_what_3.ogg:0.3,marine_what_4.ogg:0.3
@memory attackAnimTimer:float

[hiddenAction_moveToBunkerAI]
autoTrigger: if self.isControlledByAI() and numberOfUnitsInTeam(withTag='BunkerAI',greaterThan=0,withinRange=320) and not self.hasActiveWaypoint(type='loadInto')
addWaypoint_type:loadInto
addWaypoint_target_nearestUnit_team:own
addWaypoint_target_nearestUnit_tagged:BunkerAI
clearAllWaypoints:true
#addWaypoint_prepend: true

[hiddenAction_repairForMedic]
autoTrigger: if not self.hp(full=true) and not self.tags(includes='repairInfantry')
temporarilyAddTags:repairInfantry

[hiddenAction_notRepairForMedic]
autoTrigger: if self.hp(full=true) and self.tags(includes='repairInfantry')
temporarilyRemoveTags:repairInfantry

[hiddenAction_soundOnCreate]
autoTriggerOnEvent: created
playSoundToPlayer:marine_ready.wav
requireConditional:if self.customTarget1!=nullUnit
addWaypoint_type:move
addWaypoint_target_fromReference: customTarget1.readUnitMemory(name="rally",type="unit")

[hiddenAction_Bunker]
autoTriggerOnEvent:enteredTransport
autoTrigger: if self.hasParent(withTag='Bunker')
requireConditional: if self.hasParent(withTag='Bunker')
convertTo_keepCurrentFields: armour
convertTo:marineBunker
clearAllWaypoints:true

[action_stimPack]
alwaysSinglePress:true
isVisible: if self.globalTeamTags(includes='AcademyStimPack')
isActive: if self.globalTeamTags(includes='AcademyStimPack') and not self.tags(includes='stimpack') and self.resource.stasis<=0 and self.resource.maelstrom<=0
isLocked: if self.isControlledByAI() and ((not self.isAttacking() and distanceBetween(self, self.activeWaypointTarget)>300) or not self.isAttacking())
price: hp=11
text_ru:Стимуляторы
text:Stimpack
text_zh:兴奋剂
displayType:infoOnly
buildSpeed: 0s
highPriorityQueue: true
playSoundAtUnit:stimpack.ogg
iconExtraColor:#FFFFFFFF
iconExtraImage:ROOT:/DATA/Terran/stimpack.png
ai_isHighPriority:true
setUnitStats: moveSpeed=1.7856, maxEnergy=10, energy+=10, shootDelayMultiplier=0.5
temporarilyAddTags: stimpack

[hiddenAction_stimPack_2]
autoTrigger: if (self.tags(includes='stimpack') and self.energy(empty=true)) or (self.tags(includes='stimpack') and self.resource.ensnare>0)
setUnitStats: moveSpeed=1.1904, maxEnergy=0, shootDelayMultiplier=1
temporarilyRemoveTags: stimpack

[hiddenAction_attackRange]
autoTrigger: if self.globalTeamTags(includes='AcademyMarine') and not self.tags(includes='attackRange')
temporarilyAddTags: attackRange
setUnitStats: maxAttackRange+=40

[hiddenAction_armour]
@copyFromSection:template_set_armour
@define armourUpgradeType: TerranInfantryArmor

[hiddenAction_attackAnimTimer]
setUnitMemory:attackAnimTimer=self.timeAlive

[hiddenAction_stopAttackAnim]
@define animSize:0.3
autoTrigger: if memory.attackAnimTimer>0 and self.timeAlive-memory.attackAnimTimer>=${animSize} and self.isMoving
stopLastAnimation:true
setUnitMemory:attackAnimTimer=0

[effect_corpse]
alwayStartDirAtZero:true
attachedToUnit: false
life: 80
alpha: 8
image: death.png
priority: critical
drawUnderUnits: true
total_frames:8
animateFrameStart:0
animateFrameEnd:7
animateFrameSpeed:0.2
alsoPlaySound:death.ogg

[effect_sparks]
alwayStartDirAtZero:true
attachedToUnit: false
life: 100
alpha: 10
image:ROOT:/DATA/Terran/units/marineSparks.png
priority: critical
drawUnderUnits:false
total_frames:10
animateFrameStart:0
animateFrameEnd:7
animateFrameSpeed:0.3

[action_portrait]
unitShownInUI:portrait_marine

[graphics]
image_offsetY:-10
total_frames: 11
icon_build: marine_icon.png
image:        marine.png
image_wreak:  dead.png
image_turret: NONE
image_shadow:NONE
animation_moving_start: 0
animation_moving_end: 8
animation_moving_speed: 3
drawLayer:experimentals
lock_body_rotation_with_main_turret: true
rotate_with_direction: false
animation_direction_units: 45
animation_direction_strideX:11
animation_direction_strideY:0
animation_direction_starting:180
frame_width:  64
frame_height: 64

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
isFixedFiring: true
turretSize: 6
turretTurnSpeed: 3
shootDelay: 0.63s
maxAttackRange: 160
showRangeUIGuide:true

[turret_T1T2]
showRangeUIGuide:false
canAttackCondition: if (self.resource(type='TerranInfantryAttack',equalTo=0) or self.resource(type='TerranInfantryAttack',equalTo=1)) and numberOfUnitsInNeutralTeam(withTag='disruptionWeb',withinRange=120,lessThan=1)
x: 0
y: 0
shoot_sound:attack.wav,attack_2.wav
shoot_sound_vol:0.2
recoilOffset: 0
shoot_flame:NONE
projectile:T1
onShoot_freezeBodyMovementFor:0.3s
altProjectile: T2
altProjectileCondition: if self.resource(type='TerranInfantryAttack',equalTo=1)
onShoot_triggerActions:attackAnimTimer

[turret_T3T4]
canAttackCondition: if (self.resource(type='TerranInfantryAttack',equalTo=2) or self.resource(type='TerranInfantryAttack',equalTo=3)) and numberOfUnitsInNeutralTeam(withTag='disruptionWeb',withinRange=120,lessThan=1)
@copyFromSection:turret_T1T2
projectile:T3
altProjectile: T4
altProjectileCondition: if self.resource(type='TerranInfantryAttack',equalTo=3)

[projectile_T1]
directDamage: 32
life: 20
instant: true
invisible: true
explodeEffect:CUSTOM:sparks
explodeEffectOnShield:CUSTOM:sparks
mutator1_ifUnitWithTags: zergSwarm
mutator1_directDamageMultiplier:0
mutator2_ifUnitWithTags:hallucination
mutator2_directDamageMultiplier:2

[projectile_T2]
directDamage:33
@copyFromSection:projectile_T1

[projectile_T3]
directDamage:34
@copyFromSection:projectile_T1

[projectile_T4]
directDamage:36
@copyFromSection:projectile_T1

[movement]
movementType: LAND
moveSpeed: 1.1904
moveAccelerationSpeed: 20
moveDecelerationSpeed: 20
maxTurnSpeed: 40
turnAcceleration: 40
moveSlidingMode :false
moveIgnoringBody:false
reverseSpeedPercentage:0
joinsGroupFormations: false

[ai]
buildPriority: 0.9
noneInBaseExtraPriority: 0.9
noneGlobalExtraPriority: 0.9
maxEachBase: 10

[animation_attack]
onActions: attack
body_0s: {frame:9}
body_0.035s: {frame:10}
body_0.095s: {frame:10}
body_0.15s: {frame:9}
body_0.185s: {frame:10}
body_0.245s: {frame:10}
body_0.3s: {frame:9}
#body_0.335s: {frame:10}
#body_0.395s: {frame:10}
#body_0.45s: {frame:9}
body_0.67s: {frame:9}

[hiddenAction_debuff_ensnare]
setUnitStats: moveSpeed=${movement.moveSpeed}*0.5, shootDelayMultiplier=1.16

[hiddenAction_debuff_lockdown]
@copyFrom_skipThisSection: true

[hiddenAction_removeDebuff_lockdown]
@copyFrom_skipThisSection: true

[hiddenAction_feedback_debuff]
@copyFrom_skipThisSection: true

[effect_feedback]
@copyFrom_skipThisSection: true

[decal_grn_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByOwnPlayer:true
image:ROOT:/DATA/total/circle_smll_grn.png

[decal_red_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByEnemyPlayer:true
image:ROOT:/DATA/total/circle_smll_red.png

[decal_yellow_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByAllyNotOwnPlayer:true
image:ROOT:/DATA/total/circle_smll_yell.png

[decal_hp]
@copyFromSection: template_customBar
@define totalFrames:5
image:ROOT:/DATA/total/hp_6.png
frame_width:19
frame_height:5
frame:int((self.hp*100/self.maxHp)/(100/${totalFrames}))
yOffsetAbsolute:14