[core]
copyFrom:ROOT:/DATA/total/forcesAttack.template, ROOT:/DATA/Protoss/protossUpgrades.template, ROOT:/DATA/total/debuffs.template, ROOT:/DATA/total/customUI.template, ROOT:/DATA/total/unit_portrait.template
name: reaver
tags:L,NotBroodling,unit,mech,vis17,groundLargeUnit, canBeHallucinated
class: CustomUnitMetadata
price:Gas=1125
maxHp: 1380
maxShield:1600
shieldRegen:0.15
shieldDisplayOnlyDeflection:true
mass: 9999
displayText_ru: Опустошитель
displayText: Reaver
displayText_zh:金甲虫
techLevel: 1
buildSpeed: 38s
#availableInDemo: true
radius: 16
displayRadius: 16
isBio: false
hideScorchMark: false
isBug: false
fogOfWarSightRange:17
isUnrepairableUnit: true
softCollisionOnAll: 5
transportSlotsNeeded: 4
soundOnMoveOrder:reaver_yes.ogg:0.3,reaver_yes_1.ogg:0.3,reaver_yes_2.ogg:0.3,reaver_yes_3.ogg:0.3
soundOnAttackOrder:reaver_yes.ogg:0.3,reaver_yes_1.ogg:0.3,reaver_yes_2.ogg:0.3,reaver_yes_3.ogg:0.3
soundOnNewSelection:reaver_what.ogg:0.3,reaver_what_1.ogg:0.3,reaver_what_2.ogg:0.3,reaver_what_3.ogg:0.3
effectOnDeath:NONE
@global hallucinationUnit:reaver
@global supplyAdd:4

[hiddenAction_onDestroyed_nonHallucination]
spawnEffects:CUSTOM:corpse

[hiddenAction_Recall]
autoTrigger: if numberOfUnitsInTeam(withTag='recall',withinRange=100,greaterThan=0) and nearestUnit(withinRange=120, withTag='recall', relation='own').customTarget1!=nullUnit
clearAllWaypoints: true
teleportTo: nearestUnit(withinRange=120, withTag='recall', relation='own').customTarget1

[hiddenAction_soundOnCreate]
autoTriggerOnEvent: created
playSoundToPlayer:reaver_ready.ogg
requireConditional:if self.customTarget1!=nullUnit and customTarget1.tags(includes="building")
addWaypoint_type:move
addWaypoint_target_fromReference: customTarget1.readUnitMemory(name="rally",type="unit")

[effect_corpse]
alwayStartDirAtZero:true
attachedToUnit: false
life: 100
alpha: 10
image: ROOT:/DATA/Protoss/death.png
priority: critical
drawUnderUnits: true
total_frames:10
animateFrameStart:0
animateFrameEnd:9
animateFrameSpeed:0.2
frame_width:  190
frame_height: 152
alsoPlaySound:dead.ogg

[hiddenAction_armour]
@copyFromSection:template_set_shieldArmour
@define armourUpgradeType: ProtossGroundArmor

[hiddenAction_arbiter_cloak]
autoTrigger: if numberOfUnitsInTeam(withTag='arbiter',withinRange=220)>0 and self.resource.hallucination==0
convertTo:reaver_vis
convertTo_keepCurrentFields: armour
playSoundAtUnit:ROOT:/DATA/total/cloaking.ogg:0.4

[action_scarab]
isVisible: if ((self.ammo(lessThan=5) and not self.globalTeamTags(includes='RoboFacilitySupportReaverCapacity')) or (self.ammo(lessThan=10) and self.globalTeamTags(includes='RoboFacilitySupportReaverCapacity'))) and self.resource.hallucination==0
isActive: if (self.ammoIncludingQueued(lessThan=5) and not self.globalTeamTags(includes='RoboFacilitySupportReaverCapacity')) or (self.ammoIncludingQueued(lessThan=10) and self.globalTeamTags(includes='RoboFacilitySupportReaverCapacity'))
displayType:queueUnit
buildSpeed:4s
price: Gas:25
addResources: ammo=1
text_ru: Скарабей
text: Scarab
text_zh:弹药
ai_isDisabled:true
iconExtraColor:#FFFFFFFF
iconExtraImage: scarab_icon.png

[hiddenAction_autoScarab_2]
requireConditional: if self.isControlledByAI() and self.resource(type='Minerals',greaterThan=14)
autoTrigger: if ((self.ammoIncludingQueued(lessThan=5) and self.queueSize(lessThan=5) and not self.globalTeamTags(includes='RoboFacilitySupportReaverCapacity')) or (self.ammoIncludingQueued(lessThan=10) and self.queueSize(lessThan=10) and self.globalTeamTags(includes='RoboFacilitySupportReaverCapacity'))) and self.resource.hallucination==0
alsoQueueAction: scarab
addResources: Gas=-25

[action_portrait]
unitShownInUI:portrait_reaver

[graphics]
image_offsetY:-4
icon_build: reaver_icon.png
image:        reaver.png
image_wreak:  NONE
image_turret: NONE
image_shadow:NONE
animation_moving_start: 0
animation_moving_end: 7
animation_moving_speed: 4
drawLayer:experimentals
lock_body_rotation_with_main_turret: true
rotate_with_direction: false
animation_direction_units: 45
animation_direction_strideX:0
animation_direction_strideY:1
animation_direction_starting:180
frame_width:  90
frame_height: 84
imageScale: 1.15

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
isFixedFiring: true
aimOffsetSpread: 0
turretSize: 40
turretTurnSpeed: 3
maxAttackRange: 330
shootDelay: 3s
showRangeUIGuide:true

[turret_1]
canAttackCondition: if numberOfUnitsInNeutralTeam(withTag='disruptionWeb',withinRange=120)<=0
x: 0
y: 0
shoot_sound:large_gun_fire2
shoot_sound_vol:0.3
resourceUsage:ammo=1
recoilOffset:0
projectile:1
showRangeUIGuide:false
onShoot_freezeBodyMovementFor:0.63s

[projectile_1]
directDamage: 0
explodeEffect:NONE
explodeEffectOnShield:NONE
invisible: true
life: 0
speed:0
explodeOnEndOfLife:true
spawnUnit:scarab

[movement]
movementType: LAND
moveSpeed: 0.5268
moveAccelerationSpeed: 40
moveDecelerationSpeed: 40
maxTurnSpeed: 40
turnAcceleration: 40
reverseSpeedPercentage:0
joinsGroupFormations: false

[ai]
buildPriority: 0.9
noneInBaseExtraPriority: 0.9
noneGlobalExtraPriority: 0.9
maxEachBase: 10

[decal_hallucination_texture]
@copyFromSection: template_hallucination_texture
@define totalFrames:8
image: reaver_illusion.png

[decal_hallucination_energy]
@define totalFrames:10
image:ROOT:/DATA/total/energy_10.png
frame_width:31
frame_height:5
yOffsetAbsolute:30

[decal_ensnare_goo]
image:ROOT:/DATA/total/ensnare_goo_3.png

[decal_plague_goo]
image:ROOT:/DATA/total/plague_goo_3.png

[decal_defensive_matrix]
image:ROOT:/DATA/total/defensive_matrix_3.png

[decal_lockdown]
image:ROOT:/DATA/total/lockdown_3.png

[effect_mindControl]
image:ROOT:/DATA/total/mindControl_3.png
frame_width: 128
frame_height: 128

[hiddenAction_feedback_debuff]
@copyFrom_skipThisSection: true

[effect_feedback]
@copyFrom_skipThisSection: true

[hiddenAction_debuff_maelstrom]
@copyFrom_skipThisSection: true

[hiddenAction_debuff_maelstrom_effect]
@copyFrom_skipThisSection: true

[hiddenAction_removeDebuff_maelstrom]
@copyFrom_skipThisSection: true

[decal_grn_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByOwnPlayer:true
image:ROOT:/DATA/total/circle_med_grn.png

[decal_red_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByEnemyPlayer:true
image:ROOT:/DATA/total/circle_med_red.png

[decal_yellow_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByAllyNotOwnPlayer:true
image:ROOT:/DATA/total/circle_med_yell.png

[decal_hp]
@copyFromSection: template_customBar
@define totalFrames:9
image:ROOT:/DATA/total/hp_p10.png
frame_width:31
frame_height:7
frame:int((self.hp*100/self.maxHp)/(100/${totalFrames}))
yOffsetAbsolute:23

[decal_shield]
@copyFromSection: template_customBar
@define totalFrames:9
image:ROOT:/DATA/total/shield_p10.png
frame_width:31
frame_height:7
frame:int((self.shield*100/self.maxShield)/(100/${totalFrames}))
yOffsetAbsolute:23