[core]
copyFrom:ROOT:/DATA/total/forcesAttack.template, ROOT:/DATA/Protoss/protossUpgrades.template, ROOT:/DATA/total/debuffs.template, ROOT:/DATA/total/customUI.template, ROOT:/DATA/total/unit_portrait.template
name: scoutSC
tags:L,unit,mech,vis17,canBeHallucinated
class: CustomUnitMetadata
price:Gas=1150
maxHp: 1050
maxShield:800
shieldRegen:0.15
shieldDisplayOnlyDeflection:true
mass: 500
displayText_ru: Разведчик
displayText: Scout
displayText_zh:侦察机
techLevel: 1
buildSpeed: 34s
#availableInDemo: true
radius: 20
hideScorchMark: false
displayRadius: 22
isBio: false
isBug: false
fogOfWarSightRange:17
isUnrepairableUnit: true
softCollisionOnAll: 250
transportSlotsNeeded: 2
effectOnDeath:NONE
soundOnMoveOrder:scout_yes.ogg:0.3,scout_yes_1.ogg:0.3,scout_yes_2.ogg:0.3,scout_yes_3.ogg:0.3
soundOnAttackOrder:scout_yes.ogg:0.3,scout_yes_1.ogg:0.3,scout_yes_2.ogg:0.3,scout_yes_3.ogg:0.3
soundOnNewSelection:scout_what.ogg:0.3,scout_what_1.ogg:0.3,scout_what_2.ogg:0.3,scout_what_3.ogg:0.3

@global hallucinationUnit:scoutSC
@global supplyAdd:4

[hiddenAction_onDestroyed_nonHallucination]
spawnEffects:CUSTOM:corpse

[hiddenAction_speed]
autoTrigger: if self.globalTeamTags(includes='GraviticThrusters') and not self.tags(includes='speed')
temporarilyAddTags: speed
setUnitStats: moveSpeed+=0.492

[hiddenAction_apialSensors]
autoTrigger: if self.globalTeamTags(includes='ApialSensors') and not self.tags(includes='sensor')
temporarilyAddTags: sensor
setUnitStats: fogOfWarSightRange=22

[hiddenAction_Recall]
autoTrigger: if numberOfUnitsInTeam(withTag='recall',withinRange=100,greaterThan=0) and nearestUnit(withinRange=120, withTag='recall', relation='own').customTarget1!=nullUnit
clearAllWaypoints: true
teleportTo: nearestUnit(withinRange=120, withTag='recall', relation='own').customTarget1

[hiddenAction_soundOnCreate]
autoTriggerOnEvent: created
playSoundToPlayer:scout_ready.ogg
requireConditional:if self.customTarget1!=nullUnit and customTarget1.tags(includes="building")
addWaypoint_type:move
addWaypoint_target_fromReference: customTarget1.readUnitMemory(name="rally",type="unit")

[effect_light]
alwayStartDirAtZero:true
attachedToUnit: false
life: 70
alpha: 7
image:light.png
priority: critical
drawUnderUnits:false
total_frames:7
animateFrameStart:0
animateFrameEnd:6
animateFrameSpeed:0.2
frame_width:  84
frame_height:84

[effect_corpse]
alwayStartDirAtZero:true
attachedToUnit: false
life: 100
alpha: 10
image: ROOT:/DATA/Protoss/death.png
priority: critical
drawUnderUnits:false
total_frames:10
animateFrameStart:0
animateFrameEnd:9
animateFrameSpeed:0.2
frame_width:  190
frame_height: 152
alsoPlaySound:dead.ogg

[hiddenAction_armour]
@copyFromSection:template_set_shieldArmour
@define armourUpgradeType: ProtossAirArmor

[hiddenAction_arbiter_cloak]
autoTrigger: if numberOfUnitsInTeam(withTag='arbiter',withinRange=220)>0 and self.resource.hallucination==0
convertTo:scoutSC_vis
convertTo_keepCurrentFields: armour
playSoundAtUnit:ROOT:/DATA/total/cloaking.ogg:0.4

[effect_sparks]
alwayStartDirAtZero:true
attachedToUnit: false
life: 80
alpha: 8
hSpeed: 0
image: spark.png
priority: critical
drawUnderUnits:false
total_frames:8
animateFrameStart:0
animateFrameEnd:7
animateFrameSpeed:0.25

[effect_sparks3]
alwayStartDirAtZero:true
attachedToUnit: false
life: 70
alpha: 1
hSpeed: 0
image: ROOT:/DATA/Protoss/units/spark.png
priority: critical
drawUnderUnits:false
total_frames:14
animateFrameStart:0
animateFrameEnd:13
animateFrameSpeed:0.25
scaleFrom:0.8
scaleTo: 0.8

[action_portrait]
unitShownInUI:portrait_scout

[graphics]
image_offsetY:-10
total_frames: 7
icon_build: scout_icon.png
image:        scout.png
image_wreak:  NONE
image_turret: NONE
image_shadow: AUTO_ANIMATED
animation_moving_start: 1
animation_moving_end: 2
animation_moving_speed: 2.5
lock_body_rotation_with_main_turret: true
rotate_with_direction: false
animation_direction_units: 45
animation_direction_strideX:0
animation_direction_strideY:1
animation_direction_starting:180
frame_width: 72
frame_height: 72

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
isFixedFiring: true
turretSize: 6
turretTurnSpeed: 3
maxAttackRange: 160
shootDelay: 1.26s
showRangeUIGuide:true

[turret_T1T2]
showRangeUIGuide:false
canAttackCondition: if self.resource(type='ProtossAirAttack',equalTo=0) or self.resource(type='ProtossAirAttack',equalTo=1)
x: 0
y: 0
shoot_sound:attack.ogg
shoot_sound_vol:0.3
recoilOffset: 0
shoot_flame:NONE
barrelHeight: 10
projectile:T1
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
altProjectile: T2
altProjectileCondition: if self.resource(type='ProtossAirAttack',equalTo=1)
onShoot_playAnimation: attack

[turret_T3T4]
canAttackCondition: if self.resource(type='ProtossAirAttack',equalTo=2) or self.resource(type='ProtossAirAttack',equalTo=3)
@copyFromSection:turret_T1T2
projectile:T3
altProjectile: T4
altProjectileCondition: if self.resource(type='ProtossAirAttack',equalTo=3)

[projectile_T1]
directDamage: 96
areaDamage: 25
areaRadius:42
life: 20
instant: true
invisible: true
explodeEffect:CUSTOM:sparks
explodeEffectOnShield:CUSTOM:sparks
mutator1_ifUnitWithTags: zergSwarm
mutator1_directDamageMultiplier:0
mutator2_ifUnitWithTags:hallucination
mutator2_directDamageMultiplier:2

[projectile_T2]
directDamage: 104
areaDamage: 27
@copyFromSection:projectile_T1

[projectile_T3]
directDamage: 112
areaDamage: 29
@copyFromSection:projectile_T1

[projectile_T4]
directDamage: 120
areaDamage: 31
@copyFromSection:projectile_T1

[turret_T1T2_2]
showRangeUIGuide:false
canAttackCondition: if self.resource(type='ProtossAirAttack',equalTo=0) or self.resource(type='ProtossAirAttack',equalTo=1)
projectile:T1_2
x: 0
y: 0
barrelX: 14
delay:0.924s
canAttackFlyingUnits: true
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
barrelHeight: 10
shoot_sound:rocket.ogg
shoot_sound_vol:0.2
onShoot_freezeBodyMovementFor:0.63s
altProjectile: T2_2
altProjectileCondition: if self.resource(type='ProtossAirAttack',equalTo=1)

[turret_T3T4_2]
canAttackCondition: if self.resource(type='ProtossAirAttack',equalTo=2) or self.resource(type='ProtossAirAttack',equalTo=3)
@copyFromSection:turret_T1T2_2
projectile:T3_2
altProjectile: T4_2
altProjectileCondition: if self.resource(type='ProtossAirAttack',equalTo=3)

[projectile_T1_2]
directDamage: 40
areaDamage: 35
areaRadius: 56
life: 240
speed: 4
targetSpeed: 8
image:rocket.png
trailEffect:CUSTOM:light
trailEffectRate:6
explodeEffect:CUSTOM:sparks3
explodeEffectOnShield:CUSTOM:sparks3
mutator1_ifUnitWithTags:M
mutator1_ifUnitWithoutTags:haveShield
mutator1_directDamageMultiplier:0.75
mutator2_ifUnitWithTags:S
mutator2_ifUnitWithoutTags:haveShield
mutator2_directDamageMultiplier:0.5
mutator3_ifUnitWithTags:hallucination
mutator3_directDamageMultiplier:2
spawnProjectilesOnCreate: T1_2(recursionLimit=1, xOffsetRelative=-14,offsetDir=25)

[projectile_T2_2]
directDamage: 42
areaDamage: 36
spawnProjectilesOnCreate: T2_2(recursionLimit=1, xOffsetRelative=-14,offsetDir=25)
@copyFromSection:projectile_T1_2

[projectile_T3_2]
directDamage: 44
areaDamage: 37
spawnProjectilesOnCreate: T3_2(recursionLimit=1, xOffsetRelative=-14,offsetDir=25)
@copyFromSection:projectile_T1_2

[projectile_T4_2]
directDamage: 46
areaDamage: 38
spawnProjectilesOnCreate: T4_2(recursionLimit=1, xOffsetRelative=-14,offsetDir=25)
@copyFromSection:projectile_T1_2

[movement]
movementType: AIR
moveSpeed: 1.68
moveAccelerationSpeed: 0.03
moveDecelerationSpeed: 0.02
maxTurnSpeed: 40
turnAcceleration: 40
reverseSpeedPercentage:0
joinsGroupFormations: false
startingHeightOffset: 35

[ai]
buildPriority: 0.8
noneInBaseExtraPriority: 0.8
noneGlobalExtraPriority: 0.8
maxEachBase: 10

[animation_attack]
body_0s: {frame:3}
body_0.035s: {frame:4}
body_0.095s: {frame:4}
body_0.15s: {frame:3}
body_0.185s: {frame:4}
body_0.245s: {frame:4}
body_0.3s: {frame:3}
body_0.335s: {frame:4}
body_0.395s: {frame:4}
body_0.45s: {frame:3}
body_0.67s: {frame:3}

[decal_hallucination_texture]
@copyFromSection: template_hallucination_texture
@define totalFrames:4
image: scout_illusion.png

[decal_hallucination_energy]
@define totalFrames:10
image:ROOT:/DATA/total/energy_10.png
frame_width:31
frame_height:5
yOffsetAbsolute:30

[decal_ensnare_goo]
image:ROOT:/DATA/total/ensnare_goo_2.png

[decal_acidSpores]
image:ROOT:/DATA/total/acidSpores_M.png
frame_width:34
frame_height:34

[decal_plague_goo]
image:ROOT:/DATA/total/plague_goo_2.png

[decal_defensive_matrix]
image:ROOT:/DATA/total/defensive_matrix_2.png

[effect_mindControl]
image:ROOT:/DATA/total/mindControl_2.png
frame_width: 64
frame_height: 64

[hiddenAction_feedback_debuff]
@copyFrom_skipThisSection: true

[effect_feedback]
@copyFrom_skipThisSection: true

[hiddenAction_debuff_maelstrom]
@copyFrom_skipThisSection: true

[hiddenAction_debuff_maelstrom_effect]
@copyFrom_skipThisSection: true

[hiddenAction_removeDebuff_maelstrom]
@copyFrom_skipThisSection: true

[decal_grn_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByOwnPlayer:true
image:ROOT:/DATA/total/circle_med_grn.png

[decal_red_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByEnemyPlayer:true
image:ROOT:/DATA/total/circle_med_red.png

[decal_yellow_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByAllyNotOwnPlayer:true
image:ROOT:/DATA/total/circle_med_yell.png

[decal_hp]
@copyFromSection: template_customBar
@define totalFrames:9
image:ROOT:/DATA/total/hp_p10.png
frame_width:31
frame_height:7
frame:int((self.hp*100/self.maxHp)/(100/${totalFrames}))
yOffsetAbsolute:23

[decal_shield]
@copyFromSection: template_customBar
@define totalFrames:9
image:ROOT:/DATA/total/shield_p10.png
frame_width:31
frame_height:7
frame:int((self.shield*100/self.maxShield)/(100/${totalFrames}))
yOffsetAbsolute:23