[core]
copyFrom:ROOT:/DATA/total/forcesAttack.template, ROOT:/DATA/Terran/terranUpgrades.template, ROOT:/DATA/total/debuffs.template, ROOT:/DATA/total/customUI.template, ROOT:/DATA/total/unit_portrait.template
showInEditor: false
canOnlyBeAttackedByUnitsWithTags:massWeapons
name: ghostInvis
tags: bio,ghost,S,invis,haveEnergy,unit,vis17,groundUnit
class: CustomUnitMetadata
price:Minerals=100,Gas=50
borrowResourcesWhileAlive:supply=1,displaySupply=-1
maxHp: 780
energyMax:200
energyRegen:-0.0155
mass: 500
displayText_ru: Призрак
displayText: Ghost
displayText_zh:幽灵
techLevel: 1
buildSpeed: 24s
#availableInDemo: true
radius: 12
hideScorchMark: false
displayRadius: 14
isBio: true
isBug: false
isUnrepairableUnit: false
softCollisionOnAll: 5
fogOfWarSightRange:17
transportSlotsNeeded: 1
effectOnDeath:CUSTOM:corpse
soundOnMoveOrder:ghost_yes_1.ogg:0.3,ghost_yes_2.ogg:0.3,ghost_yes_3.ogg:0.3,ghost_yes_4.ogg:0.3
soundOnAttackOrder:ghost_yes_1.ogg:0.3,ghost_yes_2.ogg:0.3,ghost_yes_3.ogg:0.3,ghost_yes_4.ogg:0.3
soundOnNewSelection:ghost_what_1.ogg:0.3,ghost_what_2.ogg:0.3,ghost_what_3.ogg:0.3,ghost_what_4.ogg:0.3
showOnMinimapToEnemies: false

@memory lockdown:unit
@memory nuke:unit
@memory attackAnimTimer:float

[hiddenAction_repairForMedic]
autoTrigger: if not self.hp(full=true) and not self.tags(includes='repairInfantry')
temporarilyAddTags:repairInfantry

[hiddenAction_notRepairForMedic]
autoTrigger: if self.hp(full=true) and self.tags(includes='repairInfantry')
temporarilyRemoveTags:repairInfantry

[hiddenAction_ocularImplants]
autoTrigger: if self.globalTeamTags(includes='OcularImplants') and not self.tags(includes='ocular')
temporarilyAddTags: ocular, vis24
setUnitStats: fogOfWarSightRange=24

[effect_smoke]
alwayStartDirAtZero:true
attachedToUnit: false
life: 80
alpha: 8
hSpeed: 0
image:ROOT:/DATA/Terran/units/smoke.png
priority: critical
drawUnderUnits:false
total_frames:8
animateFrameStart:0
animateFrameEnd:7
animateFrameSpeed:0.2

[effect_sparks]
alwayStartDirAtZero:true
attachedToUnit: false
life: 100
alpha: 10
image:ROOT:/DATA/Terran/units/explode.png
priority: critical
drawUnderUnits:false
total_frames:10
animateFrameStart:0
animateFrameEnd:9
animateFrameSpeed:0.2

[action_vis_2]
isActive: if self.resource.stasis<=0 and self.resource.maelstrom<=0
alwaysSinglePress:true
displayType:infoOnly
buildSpeed:0s
text_ru:Маскирующее поле
text:Personnel cloaking
text_zh:隐形
convertTo:ghost
price:0
iconExtraColor:#FFFFFFFF
iconExtraImage:ROOT:/DATA/Terran/uncloak.png
iconImage:ROOT:/DATA/Terran/uncloak.png
isLocked: if not self.timeAlive(laterThanSeconds=20) and self.isControlledByAI()
highPriorityQueue: true
convertTo_keepCurrentFields: maxEnergy, moveSpeed, maxTurnSpeed, maxAttackRange, fogOfWarSightRange, maxShield, armour
playSoundAtUnit:ROOT:/DATA/total/cloaking_2.ogg:0.4

[action_lockdown]
isVisible: if self.globalTeamTags(includes='GhostLockdown')
isActive: if self.resource.maelstrom<=0 and self.resource.stasis<=0 and memory.lockdown==null
alwaysSinglePress:true
price:energy=100
displayType:infoOnly
buildSpeed:0s
text_ru:Замыкание
text:Locdown
text_zh:解除隐形
isGuiBlinking: if memory.lockdown!=null
onlyOneUnitAtATime: true
fireTurretXAtGround:null
fireTurretXAtGround_withProjectile:null
ai_isDisabled: true
iconExtraColor:#FFFFFFFF
iconExtraImage:ROOT:/DATA/Terran/lockdown_icon.png
addResources:energy=100
alsoTriggerAction:lockdown_2
alsoTriggerOrQueueActionConditional: if createMarker(x=thisActionTarget.x,y=thisActionTarget.y,teamId=self.teamId).nearestUnit(withinRange=40, withTag='mech', relation='enemy') != nullUnit and not createMarker(x=thisActionTarget.x,y=thisActionTarget.y,teamId=self.teamId).nearestUnit(withinRange=40, withTag='mech', relation='enemy').tags(includes="building")

[hiddenAction_lockdown_2]
addWaypoint_type: touchTarget
clearAllWaypoints:true
addWaypoint_target_fromReference: createMarker(x=thisActionTarget.x,y=thisActionTarget.y,teamId=self.teamId).nearestUnit(withinRange=40, withTag='mech', relation='enemy')
setUnitMemory: lockdown=createMarker(x=thisActionTarget.x,y=thisActionTarget.y,teamId=self.teamId).nearestUnit(withinRange=40, withTag='mech', relation='enemy')

[hiddenAction_lockdown_3]
autoTrigger: if memory.lockdown!=nullUnit and memory.lockdown.hp>0 and distanceBetween(self, memory.lockdown)<=310 and self.energy>=100 and self.resource.maelstrom<=0 and self.resource.stasis<=0
takeResources: lockdown=-44
takeResources_discardCollected: true
takeResources_includeReference: unitRef memory.lockdown
fireTurretXAtGround:null_2
fireTurretXAtGround_withProjectile:lockdown
fireTurretXAtGround_withTarget: memory.lockdown
playSoundAtUnit:lockdown.ogg:0.4
playAnimation:attack
stopLastAnimation:true
clearAllWaypoints:true
addResources:energy=-100
alsoTriggerAction:removeLockdown

[hiddenAction_removeLockdown]
autoTriggerOnEvent:newWaypointGivenByPlayer
requireConditional: if memory.lockdown!=nullUnit
autoTrigger: if memory.lockdown!=nullUnit and (self.energy<100 or memory.lockdown.hp<=0)
setUnitMemory: lockdown=null

[action_lockdown_ai]
price:energy=100
isVisible: if self.globalTeamTags(includes='GhostLockdown') and self.isControlledByAI()
isActive: if self.globalTeamTags(includes='GhostLockdown') and (nearestUnit(withinRange=310, withTag='mech', relation='enemy') != nullUnit and nearestUnit(withinRange=310, withTag='mech', relation='enemy') != nearestUnit(withinRange=310, withTag='building', relation='enemy')) and self.resource.stasis<=0 and self.resource.maelstrom<=0
displayType:infoOnly
buildSpeed:0s
text_ru:Замыкание
text:Locdown
text_zh:解除隐形
onlyOneUnitAtATime: true
takeResources: lockdown=-44
takeResources_includeUnitsWithinRange:1000
takeResources_includeUnitsWithinRange_team: enemy
takeResources_discardCollected: true
takeResources_includeReference: unitRef nearestUnit(withinRange=320, withTag='mech', relation='enemy')
fireTurretXAtGround:null_2
fireTurretXAtGround_withProjectile:lockdown
fireTurretXAtGround_withTarget: nearestUnit(withinRange=320, withTag='mech', relation='enemy')
playAnimation:attack
playSoundAtUnit:lockdown.ogg:0.4
ai_isHighPriority: true
iconExtraColor:#FFFFFFFF
iconExtraImage:ROOT:/DATA/Terran/lockdown_icon.png

[action_nuke]
isVisible: if self.resource.nuke>0 and self.resource.select<=0
isActive: if self.resource.maelstrom<=0 and self.resource.stasis<=0 and memory.nuke==null and self.resource.select<=0
price:energy=25,nuke=1
displayType:infoOnly
buildSpeed:0s
text_ru:Ядерный удар
text:Nuke
text_zh:聚变打击
isGuiBlinking: if memory.nuke!=null
fireTurretXAtGround:null
fireTurretXAtGround_withProjectile:null
onlyOneUnitAtATime: true
ai_isDisabled: true
iconExtraColor:#FFFFFFFF
iconExtraImage:ROOT:/DATA/Terran/nuke.png
addResources:energy=25,nuke=1
setUnitMemory: nuke=thisActionTarget
alsoTriggerAction:nuke_2

[hiddenAction_nuke_2]
addWaypoint_type: move
clearAllWaypoints:true
addWaypoint_target_fromReference: memory.nuke

[hiddenAction_nuke_3]
autoTrigger: if memory.nuke!=nullUnit and ((not self.globalTeamTags(includes='OcularImplants') and distanceBetween(self, memory.nuke)<=310) or (self.globalTeamTags(includes='OcularImplants') and distanceBetween(self, memory.nuke)<=430)) and self.energy>=25 and self.resource.nuke>0 and self.resource.maelstrom<=0 and self.resource.stasis<=0
fireTurretXAtGround:null
fireTurretXAtGround_withProjectile:nuke
fireTurretXAtGround_withTarget: memory.nuke
playSoundAtUnit:laser.ogg:0.4
clearAllWaypoints:true
addResources:energy=-25,nuke=-1
setResourcesWithLogic: select=11
takeResources: localNuke=1
takeResources_includeUnitsWithinRange:9999
takeResources_excludeUnitsWithoutTags: NuclearSilo
takeResources_discardCollected:true
setUnitMemory: nuke=null

[hiddenAction_removeNuke]
autoTriggerOnEvent:newWaypointGivenByPlayer
requireConditional: if memory.nuke!=nullUnit
autoTrigger: if memory.nuke!=nullUnit and (self.energy<25 or self.resource.nuke<=0)
setUnitMemory: nuke=null

[hiddenAction_nuke_set]
autoTrigger: if self.resource.select>0
temporarilyAddTags: setNuke
playAnimation: nuke_set
clearAllWaypoints:true
addResources: select=-0.1
setUnitStats:moveSpeed=0, maxTurnSpeed=0, maxAttackRange=0, mass=9999999, shootDelayMultiplier=0, shootDamageMultiplier=0
alsoTriggerAction:nuke_set_2

[hiddenAction_nuke_set_2]
requireConditional: if self.resource.select<=0
resetToDefaultTags:true
resetUnitStats:true

[hiddenAction_armour]
@copyFromSection:template_set_armour
@define armourUpgradeType: TerranInfantryArmor

[hiddenAction_maxEnergy]
autoTrigger: if self.globalTeamTags(includes='MoebiusReactor') and self.maxEnergy!=250
temporarilyAddTags: maxEnergy
setUnitStats: maxEnergy=250

[hiddenAction_startingEnergy]
autoTriggerOnEvent:created
requireConditional: if self.globalTeamTags(includes='MoebiusReactor')
setUnitStats:energy=62

[hiddenAction_vis]
autoTrigger: if self.energy(lessThan=1)
convertTo:ghost
convertTo_keepCurrentFields: maxEnergy, moveSpeed, maxTurnSpeed, maxAttackRange, fogOfWarSightRange, maxShield, armour
playSoundAtUnit:ROOT:/DATA/total/cloaking_2.ogg:0.4

[hiddenAction_invis2]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='detector',withinRange=320)>0 or numberOfUnitsInEnemyTeam(withTag='detectorRange',withinRange=440)>0 or self.resource.d_matrix>0 or self.resource.maelstrom>0 or self.resource.stasis>0 or self.resource.ensnare>0 or self.resource.plague>0
convertTo:ghostInvis2
convertTo_keepCurrentFields: maxEnergy, moveSpeed, maxTurnSpeed, maxAttackRange, fogOfWarSightRange, maxShield, armour
playSoundAtUnit:ROOT:/DATA/total/cloaking_2.ogg:0.4

[hiddenAction_attackAnimTimer]
setUnitMemory:attackAnimTimer=self.timeAlive

[hiddenAction_stopAttackAnim]
@define animSize:0.5
autoTrigger: if memory.attackAnimTimer>0 and self.timeAlive-memory.attackAnimTimer>=${animSize} and self.isMoving
stopLastAnimation:true
setUnitMemory:attackAnimTimer=0

[effect_corpse]
alwayStartDirAtZero:true
attachedToUnit: false
life: 70
alpha: 7
image: death.png
priority: critical
drawUnderUnits: true
total_frames:9
animateFrameStart:0
animateFrameEnd:6
animateFrameSpeed:0.2
alsoPlaySound:death.ogg

[action_portrait]
unitShownInUI:portrait_ghost

[graphics]
isVisibleToEnemies: false
image_offsetY:-12
icon_build: ghost_icon.png
image:        ghost2.png
image_wreak:  dead.png
image_turret: NONE
image_shadow:NONE
animation_moving_start: 0
animation_moving_end: 8
animation_moving_speed: 3
drawLayer:experimentals
lock_body_rotation_with_main_turret: true
rotate_with_direction: false
animation_direction_units: 45
animation_direction_strideX:0
animation_direction_strideY:1
animation_direction_starting:180
frame_width:  42
frame_height: 42

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
isFixedFiring: true
turretSize: 6
turretTurnSpeed: 3
maxAttackRange: 325
shootDelay: 0.924s
showRangeUIGuide:true

[turret_T1T2]
showRangeUIGuide:false
canAttackCondition: if (self.resource(type='TerranInfantryAttack',equalTo=0) or self.resource(type='TerranInfantryAttack',equalTo=1)) and numberOfUnitsInNeutralTeam(withTag='disruptionWeb',withinRange=120,lessThan=1) and self.resource(type='select',lessThan=1)
onShoot_freezeBodyMovementFor:0.5s
x: 0
y: 0
projectile:T1
shoot_sound:attack.ogg
shoot_sound_vol:0.3
recoilOffset: 0
shoot_flame:NONE
altProjectile: T2
altProjectileCondition: if self.resource(type='TerranInfantryAttack',equalTo=1)
onShoot_triggerActions:attackAnimTimer

[turret_T3T4]
canAttackCondition: if (self.resource(type='TerranInfantryAttack',equalTo=2) or self.resource(type='TerranInfantryAttack',equalTo=3)) and numberOfUnitsInNeutralTeam(withTag='disruptionWeb',withinRange=120,lessThan=1) and self.resource(type='select',lessThan=1)
@copyFromSection:turret_T1T2
projectile:T3
altProjectile: T4
altProjectileCondition: if self.resource(type='TerranInfantryAttack',equalTo=3)

[projectile_T1]
explodeEffect:CUSTOM:sparks
explodeEffectOnShield:CUSTOM:sparks
directDamage:145
life: 20
instant: true
invisible: true
mutator1_ifUnitWithTags:M
mutator1_ifUnitWithoutTags:haveShield
mutator1_directDamageMultiplier:0.5
mutator2_ifUnitWithTags:L, building
mutator2_ifUnitWithoutTags:haveShield
mutator2_directDamageMultiplier:0.25
mutator3_ifUnitWithTags: zergSwarm
mutator3_directDamageMultiplier:0
mutator4_ifUnitWithTags:hallucination
mutator4_directDamageMultiplier:2

[projectile_T2]
directDamage:148
@copyFromSection:projectile_T1

[projectile_T3]
directDamage:151
@copyFromSection:projectile_T1

[projectile_T4]
directDamage:154
@copyFromSection:projectile_T1

[turret_null]
x: 0
y: 0
limitingRange:9999
canAttackCondition: if self.globalTeamTags(includes='GOVNO')
projectile:null
showRangeUIGuide:false

[turret_null_2]
x: 0
y: 0
limitingRange:9999
recoilOffset: 0
shoot_flame:NONE
showRangeUIGuide:false
canAttackCondition: if self.globalTeamTags(includes='GOVNO')
onShoot_freezeBodyMovementFor:0.924s

[projectile_null]
life:0
speed:0
invisible: true
directDamage: 0
explodeEffect:NONE
explodeEffectOnShield:NONE

[projectile_nuke]
life: 20
instant: true
invisible: true
directDamage: 0
targetGround: true
explodeOnEndOfLife: true
spawnUnit:point
explodeEffect:NONE

[projectile_lockdown]
life: 240
speed: 4
targetSpeed: 8
areaDamage: 0
areaRadius: 0
targetGround: true
image:ROOT:/DATA/Terran/units/rocket.png
trailEffect:CUSTOM:smoke
trailEffectRate:6
explodeEffect:CUSTOM:sparks
explodeEffectOnShield:CUSTOM:sparks

[movement]
movementType: LAND
moveSpeed: 1.1904
moveAccelerationSpeed: 20
moveDecelerationSpeed: 20
maxTurnSpeed: 40
turnAcceleration: 40
moveSlidingMode :false
moveIgnoringBody:false
reverseSpeedPercentage:0
joinsGroupFormations: false

[ai]
buildPriority: 0.8
noneInBaseExtraPriority: 0.8
noneGlobalExtraPriority: 0.8
maxEachBase: 10
upgradedFrom: ghost

[animation_attack]
onActions: attack
body_0s: {frame:12}
body_0.1s: {frame:12}
body_0.11s: {frame:11}
body_0.96s: {frame:11}

[animation_nuke_set]
body_0s: {frame:11}
body_0.6s: {frame:11}

[hiddenAction_debuff_lockdown]
@copyFrom_skipThisSection: true

[hiddenAction_removeDebuff_lockdown]
@copyFrom_skipThisSection: true

[decal_grn_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByOwnPlayer:true
image:ROOT:/DATA/total/circle_smll_grn.png

[decal_red_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByEnemyPlayer:true
image:ROOT:/DATA/total/circle_smll_red.png

[decal_yellow_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByAllyNotOwnPlayer:true
image:ROOT:/DATA/total/circle_smll_yell.png

[decal_hp]
@copyFromSection: template_customBar
@define totalFrames:5
image:ROOT:/DATA/total/hp_6.png
frame_width:19
frame_height:5
frame:int((self.hp*100/self.maxHp)/(100/${totalFrames}))
yOffsetAbsolute:14

[decal_energy]
@copyFromSection: template_customBar
@define totalFrames:6
onlyWhenSelectedByOwnPlayer:true
onlyWhenSelectedByAnyPlayer:false
image:ROOT:/DATA/total/energy_6.png
frame_width:19
frame_height:5
frame:int((self.energy*100/self.maxEnergy)/(100/${totalFrames}))
yOffsetAbsolute:20