[core]
copyFrom:ROOT:/DATA/total/forcesAttack.template, ROOT:/DATA/Protoss/protossUpgrades.template, ROOT:/DATA/total/debuffs.template, ROOT:/DATA/total/customUI.template, ROOT:/DATA/total/unit_portrait.template
name: zealot
tags:S,ground,bio,unit,vis17,groundUnit,canBeHallucinated
class: CustomUnitMetadata
price:Gas=100
maxHp:400
maxShield:275
shieldRegen:0.085
shieldDisplayOnlyDeflection:true
mass: 500
displayText_ru: Зилот
displayText: Zealot
displayText_zh:狂热者
techLevel: 1
buildSpeed: 8.7s
#availableInDemo: true
radius: 11
hideScorchMark: false
displayRadius: 14
isBio: true
isBug: false
fogOfWarSightRange:17
isUnrepairableUnit: false
softCollisionOnAll: 5
transportSlotsNeeded: 2
effectOnDeath:NONE
soundOnMoveOrder:zealot_yes.ogg:0.3,zealot_yes_1.ogg:0.3,zealot_yes_2.ogg:0.3,zealot_yes_3.ogg:0.3
soundOnAttackOrder:zealot_yes.ogg:0.3,zealot_yes_1.ogg:0.3,zealot_yes_2.ogg:0.3,zealot_yes_3.ogg:0.3
soundOnNewSelection:zealot_what.ogg:0.3,zealot_what_1.ogg:0.3,zealot_what_2.ogg:0.3,zealot_what_3.ogg:0.3
@global hallucinationUnit:zealot
@global supplyAdd:2
@memory attackAnimTimer:float

[hiddenAction_onDestroyed_nonHallucination]
spawnEffects:CUSTOM:corpse

[hiddenAction_Recall]
autoTrigger: if numberOfUnitsInTeam(withTag='recall',withinRange=100,greaterThan=0) and nearestUnit(withinRange=120, withTag='recall', relation='own').customTarget1!=nullUnit
clearAllWaypoints: true
teleportTo: nearestUnit(withinRange=120, withTag='recall', relation='own').customTarget1

[hiddenAction_onCreate]
autoTriggerOnEvent: created
playSoundToPlayer:zealot_ready.ogg
requireConditional:if self.customTarget1!=nullUnit and customTarget1.tags(includes="building")
addWaypoint_type:move
addWaypoint_target_fromReference: customTarget1.readUnitMemory(name="rally",type="unit")

[effect_corpse]
alwayStartDirAtZero:true
attachedToUnit: false
life: 70
alpha: 7
image: death.png
priority: critical
drawUnderUnits: true
total_frames:7
animateFrameStart:0
animateFrameEnd:6
animateFrameSpeed:0.2
alsoPlaySound:dead.ogg
frame_width: 128
frame_height: 128

[hiddenAction_armour]
@copyFromSection:template_set_shieldArmour
@define armourUpgradeType: ProtossGroundArmor

[hiddenAction_speed]
autoTrigger: if self.globalTeamTags(includes='CitadelOfAdunSpeed') and not self.tags(includes='speed')
temporarilyAddTags: speed
setUnitStats: moveSpeed+=0.5952

[hiddenAction_arbiter_cloak]
autoTrigger: if numberOfUnitsInTeam(withTag='arbiter',withinRange=220)>0 and self.resource.hallucination==0
convertTo:zealot_vis
convertTo_keepCurrentFields: armour
playSoundAtUnit:ROOT:/DATA/total/cloaking.ogg:0.4

[hiddenAction_attackAnimTimer]
setUnitMemory:attackAnimTimer=self.timeAlive

[hiddenAction_stopAttackAnim]
@define animSize:0.5
autoTrigger: if memory.attackAnimTimer>0 and self.timeAlive-memory.attackAnimTimer>=${animSize} and self.isMoving
stopLastAnimation:true
setUnitMemory:attackAnimTimer=0

[effect_spark]
attachedToUnit: false
life: 50
alpha: 0.4
priority: critical
drawUnderUnits:false
alsoPlaySound:hit.wav:0.2
image:ROOT:/DATA/total/null.png

[action_portrait]
unitShownInUI:portrait_zealot

[graphics]
image_offsetY:-12
icon_build: zealot_icon.png
image:        zealot.png
image_wreak:  NONE
image_turret: NONE
image_shadow:NONE
animation_moving_start: 0
animation_moving_end: 7
animation_moving_speed: 3
drawLayer:experimentals
rotate_with_direction: false
animation_direction_units: 45
animation_direction_strideX:13
animation_direction_strideY:0
animation_direction_starting:180
frame_width:  64
frame_height: 64

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
meleeEngangementDistance: 200
isMelee:true
isFixedFiring: true
turretSize: 12
aimOffsetSpread: 0
maxAttackRange: 21
shootDelay: 0.924s
showRangeUIGuide:false

[turret_T1T2]
canAttackCondition: if (self.resource(type='ProtossGroundAttack',equalTo=0) or self.resource(type='ProtossGroundAttack',equalTo=1)) and numberOfUnitsInNeutralTeam(withTag='disruptionWeb',withinRange=120)<=0
x: 0
y: 0
shoot_sound:attack.wav,attack2.wav
shoot_sound_vol:0.2
recoilOffset:0
projectile:T1
showRangeUIGuide:false
onShoot_freezeBodyMovementFor:0.5s
altProjectile: T2
altProjectileCondition: if self.resource(type='ProtossGroundAttack',equalTo=1)
onShoot_triggerActions:attackAnimTimer

[turret_T3T4]
canAttackCondition: if (self.resource(type='ProtossGroundAttack',equalTo=2) or self.resource(type='ProtossGroundAttack',equalTo=3)) and numberOfUnitsInNeutralTeam(withTag='disruptionWeb',withinRange=120)<=0
@copyFromSection:turret_T1T2
projectile:T3
altProjectile: T4
altProjectileCondition: if self.resource(type='ProtossGroundAttack',equalTo=3)

[turret_T1T2_2]
showRangeUIGuide:false
canAttackCondition: if (self.resource(type='ProtossGroundAttack',equalTo=0) or self.resource(type='ProtossGroundAttack',equalTo=1)) and numberOfUnitsInNeutralTeam(withTag='disruptionWeb',withinRange=120)<=0
projectile:T1
x: 0
y: 0
slave:true
attachedTo:T1T2
warmup:0s
altProjectile: T2
altProjectileCondition: if self.resource(type='ProtossGroundAttack',equalTo=1)

[turret_T3T4_2]
canAttackCondition: if (self.resource(type='ProtossGroundAttack',equalTo=2) or self.resource(type='ProtossGroundAttack',equalTo=3)) and numberOfUnitsInNeutralTeam(withTag='disruptionWeb',withinRange=120)<=0
@copyFromSection:turret_T1T2_2
projectile:T3
attachedTo:T3T4
altProjectile: T4
altProjectileCondition: if self.resource(type='ProtossGroundAttack',equalTo=3)

[projectile_T1]
directDamage:60
life: 20
instant: true
invisible: true
explodeEffect:CUSTOM:spark
explodeEffectOnShield:CUSTOM:spark
mutator1_ifUnitWithTags:hallucination
mutator1_directDamageMultiplier:2

[projectile_T2]
directDamage:63
@copyFromSection:projectile_T1

[projectile_T3]
directDamage:66
@copyFromSection:projectile_T1

[projectile_T4]
directDamage:69
@copyFromSection:projectile_T1

[movement]
movementType: LAND
moveSpeed: 1.32
moveAccelerationSpeed: 40
moveDecelerationSpeed: 40
maxTurnSpeed: 40
turnAcceleration: 40
reverseSpeedPercentage:0
joinsGroupFormations: false

[ai]
buildPriority: 0.8
noneInBaseExtraPriority: 0.8
noneGlobalExtraPriority: 0.8
maxEachBase: 10

[animation_attack]
onActions: attack
body_0s: {frame:8}
body_0.05s: {frame:9}
body_0.1s: {frame:10} 
body_0.15s: {frame:11}
body_0.2s: {frame:12}
body_0.25s: {frame:8}
body_0.926s: {frame:8}

[decal_hallucination_texture]
@copyFromSection: template_hallucination_texture
@define totalFrames:13
image: zealot_illusion.png

[decal_hallucination_energy]
@define totalFrames:7
image:ROOT:/DATA/total/energy_7.png
frame_width:22
frame_height:5
yOffsetAbsolute:21

[hiddenAction_debuff_lockdown]
@copyFrom_skipThisSection: true

[hiddenAction_removeDebuff_lockdown]
@copyFrom_skipThisSection: true

[hiddenAction_feedback_debuff]
@copyFrom_skipThisSection: true

[effect_feedback]
@copyFrom_skipThisSection: true

[decal_grn_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByOwnPlayer:true
image:ROOT:/DATA/total/circle_smll_grn.png

[decal_red_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByEnemyPlayer:true
image:ROOT:/DATA/total/circle_smll_red.png

[decal_yellow_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByAllyNotOwnPlayer:true
image:ROOT:/DATA/total/circle_smll_yell.png

[decal_hp]
@copyFromSection: template_customBar
@define totalFrames:6
image:ROOT:/DATA/total/hp_p7.png
frame_width:22
frame_height:7
frame:int((self.hp*100/self.maxHp)/(100/${totalFrames}))
yOffsetAbsolute:14

[decal_shield]
@copyFromSection: template_customBar
@define totalFrames:6
image:ROOT:/DATA/total/shield_p7.png
frame_width:22
frame_height:7
frame:int((self.shield*100/self.maxShield)/(100/${totalFrames}))
yOffsetAbsolute:14