[core]
copyFrom:ROOT:/DATA/Zerg/units/airUnits.template, ROOT:/DATA/Zerg/zergUpgrades.template, ROOT:/DATA/total/debuffs.template, ROOT:/DATA/total/customUI.template, ROOT:/DATA/total/unit_portrait.template
name: queen
tags:M,bio,queen,haveEnergy,canConsume,unit,vis17
price:Minerals=100,gas=100,supply=2, displaySupply=-2
borrowResourcesWhileAlive:supply=2, displaySupply=-2
maxHp: 120
energyMax: 200
energyRegen:0.0124
energyStartingPercentage:0.25
displayText_ru: Королева
displayText: Queen
displayText_zh:虫后
buildSpeed:32s
radius: 24
displayRadius: 26
soundOnMoveOrder: queen_yes_1.ogg:0.3,queen_yes_2.ogg:0.3,queen_yes_3.ogg:0.3,queen_yes_4.ogg:0.3
soundOnAttackOrder: queen_yes_1.ogg:0.3,queen_yes_2.ogg:0.3,queen_yes_3.ogg:0.3,queen_yes_4.ogg:0.3
soundOnNewSelection:queen_what_1.ogg:0.3,queen_what_2.ogg:0.3,queen_what_3.ogg:0.3,queen_what_4.ogg:0.3

@memory ensnare:unit
@memory parasit:unit
@memory broodling:unit

[hiddenAction_soundOnCreate]
autoTriggerOnEvent: created
requireConditional:if self.customTarget1!=nullUnit
playSoundToPlayer:queen_ready.ogg
addWaypoint_type:move
addWaypoint_target_fromReference: customTarget1.readUnitMemory(name="rally",type="unit")

[hiddenAction_maxEnergy]
autoTrigger: if self.globalTeamTags(includes='GameteMeiosis') and self.maxEnergy!=250
temporarilyAddTags: maxEnergy
setUnitStats: maxEnergy=250

[hiddenAction_startingEnergy]
autoTriggerOnEvent:created
requireConditional: if self.globalTeamTags(includes='GameteMeiosis')
setUnitStats:energy=62

[effect_ensnare]
alwayStartDirAtZero:true
attachedToUnit: false
life: 140
alpha: 14
image:ROOT:/DATA/Zerg/ensnare.png
priority: critical
drawUnderUnits:false
total_frames:15
animateFrameStart:0
animateFrameEnd:14
animateFrameSpeed:0.2
frame_width:  130
frame_height: 123
alsoPlaySound:ensnare.ogg:0.4

[action_parasit]
isActive: if self.resource.maelstrom<=0 and self.resource.stasis<=0 and memory.parasit==null
alwaysSinglePress:true
price:energy=75
displayType:infoOnly
buildSpeed:0s
text_ru:Паразит
text:Parasit
text_zh:寄生
isGuiBlinking: if memory.parasit!=null
onlyOneUnitAtATime: true
fireTurretXAtGround:null
fireTurretXAtGround_withProjectile:null
ai_isDisabled: true
iconExtraColor:#FFFFFFFF
iconExtraImage:parasite.png
addResources:energy=75
alsoTriggerAction:parasit_2
alsoTriggerOrQueueActionConditional: if createMarker(x=thisActionTarget.x,y=thisActionTarget.y,teamId=self.teamId).nearestUnit(withinRange=40, withTag='unit', relation='enemy') != nullUnit

[hiddenAction_parasit_2]
addWaypoint_type: touchTarget
clearAllWaypoints:true
addWaypoint_target_fromReference: createMarker(x=thisActionTarget.x,y=thisActionTarget.y,teamId=self.teamId).nearestUnit(withinRange=40, withTag='unit', relation='enemy')
setUnitMemory: parasit=createMarker(x=thisActionTarget.x,y=thisActionTarget.y,teamId=self.teamId).nearestUnit(withinRange=40, withTag='unit', relation='enemy')

[hiddenAction_parasit_3]
autoTrigger: if memory.parasit!=nullUnit and memory.parasit.hp>0 and distanceBetween(self, memory.parasit)<=310 and self.energy>=75 and self.resource.maelstrom<=0 and self.resource.stasis<=0
fireTurretXAtGround:null_2
fireTurretXAtGround_withProjectile:parasit
fireTurretXAtGround_withTarget: memory.parasit
playSoundAtUnit:shoot.ogg:0.3
playAnimation:attack
stopLastAnimation:true
clearAllWaypoints:true
addResources:energy=-75
setUnitMemory: parasit=null

[hiddenAction_removeParasit]
autoTriggerOnEvent:newWaypointGivenByPlayer
requireConditional: if memory.parasit!=nullUnit
autoTrigger: if memory.parasit!=nullUnit and (self.energy<75 or memory.parasit.hp<=0)
setUnitMemory: parasit=null

[action_ensnare]
isVisible: if self.globalTeamTags(includes='Ensnare')
isActive: if self.resource.maelstrom<=0 and self.resource.stasis<=0 and memory.ensnare==null
price:energy=75
displayType:infoOnly
buildSpeed:0s
text_ru:Паутина
text:Ensnare
text_zh:诱捕
isGuiBlinking: if memory.ensnare!=null
fireTurretXAtGround:null
fireTurretXAtGround_withProjectile:null
onlyOneUnitAtATime: true
ai_isDisabled: true
iconExtraColor:#FFFFFFFF
iconExtraImage:ROOT:/DATA/Zerg/ensnare_icon.png
addResources:energy=75
setUnitMemory: ensnare=thisActionTarget
alsoTriggerAction:ensnare_2

[hiddenAction_ensnare_2]
addWaypoint_type: move
clearAllWaypoints:true
addWaypoint_target_fromReference: memory.ensnare

[hiddenAction_ensnare_3]
autoTrigger: if memory.ensnare!=nullUnit and distanceBetween(self, memory.ensnare)<=310 and self.energy>=75 and self.resource.maelstrom<=0 and self.resource.stasis<=0
fireTurretXAtGround:null_2
fireTurretXAtGround_withProjectile:ensnare
fireTurretXAtGround_withTarget: memory.ensnare
playSoundAtUnit:shoot.ogg:0.3
playAnimation:attack
stopLastAnimation:true
clearAllWaypoints:true
addResources:energy=-75
setUnitMemory: ensnare=null

[hiddenAction_removeEnsnare]
autoTriggerOnEvent:newWaypointGivenByPlayer
requireConditional: if memory.ensnare!=nullUnit
autoTrigger: if memory.ensnare!=nullUnit and self.energy<75
setUnitMemory: ensnare=null

[action_ensnare_ai]
price:energy=75
isVisible: if self.globalTeamTags(includes='Ensnare') and self.isControlledByAI()
isActive: if self.globalTeamTags(includes='Ensnare') and numberOfUnitsInEnemyTeam(withTag="unit", withinRange=310)>0 and self.resource.maelstrom<=0 and self.resource.stasis<=0
displayType:infoOnly
buildSpeed:0s
text_ru:Паутина
text:Ensnare
text_zh:诱捕
onlyOneUnitAtATime: true
fireTurretXAtGround:null
fireTurretXAtGround_withProjectile:ensnare
fireTurretXAtGround_withTarget: nearestUnit(withinRange=320, withTag='unit', relation='enemy')
playAnimation:attack
stopLastAnimation:true
ai_isHighPriority: true
iconExtraColor:#FFFFFFFF
iconExtraImage:ROOT:/DATA/Zerg/ensnare_icon.png

[action_broodling]
alwaysSinglePress:true
price:energy=150
isVisible: if self.globalTeamTags(includes='SpawnBroodlings')
isActive: if self.globalTeamTags(includes='SpawnBroodlings') and self.resource.broodling<=0 and self.resource.maelstrom<=0 and self.resource.stasis<=0
displayType:infoOnly
buildSpeed:0s
text_ru:Породить брудлингов
text:Spawn Broodlings
text_zh:孵化巢虫
isGuiBlinking: if self.resource.broodling>0
highPriorityQueue: true
fireTurretXAtGround:null
fireTurretXAtGround_withProjectile:null
ai_isDisabled: false
iconExtraColor:#FFFFFFFF
iconExtraImage:ROOT:/DATA/Zerg/broodling_icon.png
onlyOneUnitAtATime: true
addResources:energy=150
alsoTriggerAction:broodling_2
alsoTriggerOrQueueActionConditional: if createMarker(x=thisActionTarget.x,y=thisActionTarget.y,teamId=self.teamId).nearestUnit(withinRange=40, withTag='unit', relation='enemy') != nullUnit and not createMarker(x=thisActionTarget.x,y=thisActionTarget.y,teamId=self.teamId).nearestUnit(withinRange=40, withTag='unit', relation='enemy').tags(includes="NotBroodling") and not createMarker(x=thisActionTarget.x,y=thisActionTarget.y,teamId=self.teamId).nearestUnit(withinRange=40, withTag='unit', relation='enemy').tags(includes="building") and createMarker(x=thisActionTarget.x,y=thisActionTarget.y,teamId=self.teamId).nearestUnit(withinRange=40, withTag='unit', relation='enemy').height==0

[hiddenAction_broodling_2]
addWaypoint_type: attack
clearAllWaypoints:true
addWaypoint_target_fromReference: createMarker(x=thisActionTarget.x,y=thisActionTarget.y,teamId=self.teamId).nearestUnit(withinRange=40, withTag='unit', relation='enemy')
setUnitMemory: broodling=createMarker(x=thisActionTarget.x,y=thisActionTarget.y,teamId=self.teamId).nearestUnit(withinRange=40, withTag='unit', relation='enemy')
addResources:broodling=1

[hiddenAction_removeBroodling]
autoTriggerOnEvent:newWaypointGivenByPlayer
requireConditional: if memory.broodling!=nullUnit
autoTrigger: if memory.broodling!=nullUnit and (self.energy<150 or memory.broodling.hp<=0)
setUnitMemory: broodling=null
setResourcesWithLogic: broodling=0

[action_infest]
isActive: if self.resource.maelstrom<=0 and self.resource.stasis<=0
text_ru: Заражение
text: Infest
text_zh:骚扰
displayType:infoOnly
buildSpeed: 0s
highPriorityQueue: false
fireTurretXAtGround: infest
fireTurretXAtGround_withProjectile:null
onlyOneUnitAtATime: true
ai_isDisabled:true
iconExtraColor:#FFFFFFFF
iconExtraImage:infest.png
alsoTriggerAction:infest_2
alsoTriggerOrQueueActionConditional: if thisActionTarget.nearestUnit(withinRange=50, withTag='CommandCenter', relation='any') != nullUnit and thisActionTarget.nearestUnit(withinRange=50, withTag='CommandCenter', relation='any').hp<thisActionTarget.nearestUnit(withinRange=50, withTag='CommandCenter', relation='any').maxHp*0.5

[hiddenAction_infest_2]
addWaypoint_type: touchTarget
clearAllWaypoints:true
addWaypoint_target_fromReference: thisActionTarget.nearestUnit(withinRange=50, withTag='CommandCenter', relation='any') 

[hiddenAction_infest_3]
autoTriggerOnEvent: touchTargetSuccess
requireConditional: if eventSource.hp<eventSource.maxHp*0.5 and eventSource.tags(includes="building")
sendMessageTo: eventSource
sendMessageWithTags:infest

[effect_corpse]
alwayStartDirAtZero:true
attachedToUnit: false
life: 50
alpha: 7
hSpeed: 0
image: death.png
priority: critical
drawUnderUnits:false
total_frames:7
animateFrameStart:0
animateFrameEnd:6
animateFrameSpeed:0.2
alsoPlaySound:death.wav
scaleFrom:1
scaleTo: 1

[action_portrait]
unitShownInUI:portrait_queen

[graphics]
image_offsetY:-4
#image_offsetX:5
total_frames: 11
icon_build: queen_icon.png
image:        queen.png
image_wreak:  NONE
image_turret: NONE
image_shadow: AUTO_ANIMATED
animation_moving_start: 0
animation_moving_end: 4
animation_moving_speed: 3
animation_idle_start: 0
animation_idle_end: 4
animation_idle_speed: 4
lock_body_rotation_with_main_turret: true
rotate_with_direction: false
animation_direction_units: 45
animation_direction_strideX:11
animation_direction_strideY:0
animation_direction_starting:180
frame_width:  100
frame_height: 100

[attack]
disablePassiveTargeting: true
canAttackLandUnits: if self.resource.broodling>0
canAttackFlyingUnits: false
maxAttackRange: 310
shootDelay:1s
stopTargetingAfterFiring: true

[turret_null]
x: 0
y: 0
limitingRange:9999
recoilOffset: 0
shoot_flame:NONE
showRangeUIGuide:false
canAttackCondition: if self.globalTeamTags(includes='GOVNO')

[turret_null_2]
x: 0
y: 0
limitingRange:9999
recoilOffset: 0
shoot_flame:NONE
showRangeUIGuide:false
canAttackCondition: if self.globalTeamTags(includes='GOVNO')
onShoot_freezeBodyMovementFor:0.6s

[projectile_null]
directDamage: 0
life: 0
speed: 0
invisible:true
explodeEffect:NONE

[projectile_parasit]
directDamage: 0
spawnUnit: parasite
targetGround: true
life: 160
speed: 5
targetSpeed: 12
image:arrow.png
explodeEffect:NONE

[projectile_ensnare]
directDamage: 0
areaDamage:0
areaRadius:80
areaDamageNoFalloff: true
areaHitAirAndLandAtSameTime: true
friendlyFire: true
targetGround: true
life: 160
speed: 5
targetSpeed: 12
image:arrow.png
explodeEffect:CUSTOM:ensnare
mutator1_ifUnitWithTags:S,M,L
mutator1_ifUnitWithoutTags:undergroundZerg
mutator1_areaDamageMultiplier: 0
mutator1_addResourcesAreaHit: ensnare=25

[turret_broodling]
canOnlyAttackUnitsWithoutTags:NotBroodling,building
x: 0
y: 0
shoot_sound:shoot.ogg
shoot_sound_vol:0.3
shoot_flame:NONE
resourceUsage:broodling=1, energy=150
showRangeUIGuide:false
projectile:broodling
canAttackCondition: if self.resource.broodling>0
onShoot_freezeBodyMovementFor:0.6s

[projectile_broodling]
directDamage: 600
spawnUnit: broodling*2
life: 160
speed: 5
targetSpeed: 12
image:arrow.png
explodeEffect:NONE
buildingDamageMultiplier: 0
autoTargetingOnDeadTarget: true

[turret_infest]
x: 0
y: 0
limitingRange:9999
showRangeUIGuide:false

[movement]
moveSpeed: 1.9852

[resource_broodling]
hidden:false

[resource_infest]
hidden:false

[animation_attack]
onActions: attack
body_0s: {frame:5}
body_0.05s: {frame:5}
body_0.1s: {frame:6}
body_0.15s: {frame:7}
body_0.2s: {frame:8}
body_0.25s: {frame:9}
body_0.3s: {frame:10}
body_0.35s: {frame:11}

[decal_ensnare_goo]
image:ROOT:/DATA/total/ensnare_goo_2.png

[decal_acidSpores]
image:ROOT:/DATA/total/acidSpores_M.png
frame_width:34
frame_height:34

[decal_plague_goo]
image:ROOT:/DATA/total/plague_goo_2.png

[decal_defensive_matrix]
image:ROOT:/DATA/total/defensive_matrix_2.png

[effect_mindControl]
image:ROOT:/DATA/total/mindControl_2.png
frame_width: 64
frame_height: 64

[effect_feedback]
image:ROOT:/DATA/total/feedback_2.png
frame_width: 128
frame_height: 128

[decal_maelstrom]
image:ROOT:/DATA/total/maelstrom_2.png
frame_width:  64
frame_height: 64

[decal_grn_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByOwnPlayer:true
image:ROOT:/DATA/total/circle_med_grn.png

[decal_red_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByEnemyPlayer:true
image:ROOT:/DATA/total/circle_med_red.png

[decal_yellow_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByAllyNotOwnPlayer:true
image:ROOT:/DATA/total/circle_med_yell.png

[decal_hp]
@copyFromSection: template_customBar
@define totalFrames:10
image:ROOT:/DATA/total/hp_11.png
frame_width:34
frame_height:5
frame:int((self.hp*100/self.maxHp)/(100/${totalFrames}))
yOffsetAbsolute:23

[decal_energy]
@copyFromSection: template_customBar
@define totalFrames:11
onlyWhenSelectedByOwnPlayer:true
onlyWhenSelectedByAnyPlayer:false
image:ROOT:/DATA/total/energy_11.png
frame_width:34
frame_height:5
frame:int((self.energy*100/self.maxEnergy)/(100/${totalFrames}))
yOffsetAbsolute:29