[core]
copyFrom:ROOT:/DATA/total/forcesAttack.template, ROOT:/DATA/Terran/terranUpgrades.template, ROOT:/DATA/total/debuffs.template, ROOT:/DATA/total/customUI.template, ROOT:/DATA/total/unit_portrait.template
name: firebat
tags: bio,firebat,bunkerBio,S,infantry,unit,vis17,groundUnit
class: CustomUnitMetadata
price:Gas=125
maxHp: 580
energyMax: 0
energyRegen: -0.0166666666
armour:1
mass: 500
displayText_ru: Огнемётчик
displayText: Firebat
displayText_zh:火蝠
techLevel: 1
buildSpeed: 9.2s
#availableInDemo: true
radius: 12
hideScorchMark: false
displayRadius: 14
isBio: true
isBug: false
isUnrepairableUnit: false
softCollisionOnAll: 5
transportSlotsNeeded: 1
fogOfWarSightRange:17
effectOnDeath:CUSTOM:corpse
soundOnMoveOrder:firebat_yes.ogg:0.3,firebat_yes_1.ogg:0.3,firebat_yes_2.ogg:0.3,firebat_yes_3.ogg:0.3
soundOnAttackOrder:firebat_yes.ogg:0.3,firebat_yes_1.ogg:0.3,firebat_yes_2.ogg:0.3,firebat_yes_3.ogg:0.3
soundOnNewSelection:firebat_what.ogg:0.3,firebat_what_1.ogg:0.3,firebat_what_2.ogg:0.3
@memory attackAnimTimer:float

[hiddenAction_moveToBunkerAI]
autoTrigger: if self.isControlledByAI() and numberOfUnitsInTeam(withTag='BunkerAI',greaterThan=0,withinRange=320) and not self.hasActiveWaypoint(type='loadInto')
addWaypoint_type:loadInto
addWaypoint_target_nearestUnit_team:own
addWaypoint_target_nearestUnit_tagged:BunkerAI
clearAllWaypoints:true
#addWaypoint_prepend: true

[hiddenAction_repairForMedic]
autoTrigger: if not self.hp(full=true) and not self.tags(includes='repairInfantry')
temporarilyAddTags:repairInfantry

[hiddenAction_notRepairForMedic]
autoTrigger: if self.hp(full=true) and self.tags(includes='repairInfantry')
temporarilyRemoveTags:repairInfantry

[hiddenAction_soundOnCreate]
autoTriggerOnEvent: created
playSoundToPlayer:firebat_ready.ogg
requireConditional:if self.customTarget1!=nullUnit
addWaypoint_type:move
addWaypoint_target_fromReference: customTarget1.readUnitMemory(name="rally",type="unit")

[action_stimPack]
alwaysSinglePress:true
isVisible: if self.globalTeamTags(includes='AcademyStimPack')
isActive: if self.globalTeamTags(includes='AcademyStimPack') and not self.tags(includes='stimpack') and self.resource.stasis<=0
isLocked: if self.isControlledByAI() and ((not self.isAttacking() and distanceBetween(self, self.activeWaypointTarget)>300) or not self.isAttacking())
price: hp=11
text_ru:Стимуляторы
text:Stimpack
text_zh:兴奋剂
displayType:infoOnly
buildSpeed: 0s
highPriorityQueue: true
playSoundAtUnit:stimpack.ogg
iconExtraColor:#FFFFFFFF
iconExtraImage:ROOT:/DATA/Terran/stimpack.png
ai_isHighPriority:true
setUnitStats: moveSpeed=1.7856, maxEnergy=10, energy+=10, shootDelayMultiplier=0.5
temporarilyAddTags: stimpack

[hiddenAction_stimPack_2]
autoTrigger: if (self.tags(includes='stimpack') and self.energy(empty=true)) or (self.tags(includes='stimpack') and self.resource.ensnare>0)
setUnitStats: moveSpeed=1.1904, maxEnergy=0, shootDelayMultiplier=1
temporarilyRemoveTags: stimpack

[hiddenAction_Bunker]
autoTriggerOnEvent:enteredTransport
autoTrigger: if self.hasParent(withTag='Bunker')
requireConditional: if self.hasParent(withTag='Bunker')
convertTo_keepCurrentFields: armour
convertTo:firebatBunker
clearAllWaypoints:true

[hiddenAction_armour]
@copyFromSection:template_set_armour
@define armourUpgradeType: TerranInfantryArmor

[hiddenAction_attackAnimTimer]
setUnitMemory:attackAnimTimer=self.timeAlive

[hiddenAction_stopAttackAnim]
@define animSize:0.462
autoTrigger: if memory.attackAnimTimer>0 and self.timeAlive-memory.attackAnimTimer>=${animSize} and self.isMoving
stopLastAnimation:true
setUnitMemory:attackAnimTimer=0

[effect_corpse]
alwayStartDirAtZero:true
attachedToUnit: false
life: 90
alpha: 9
image:ROOT:/DATA/Terran/units/death.png
priority: critical
drawUnderUnits: true
animateFrameStart:0
animateFrameEnd:8
animateFrameSpeed:0.2
alsoPlaySound:death.wav
frame_width:  128
frame_height: 128

[effect_fire]
attachedToUnit: false
yOffsetRelative: 50
hOffset: 10
hSpeed: 0
life: 80
alpha: 8
image:fire.png
priority: critical
drawUnderUnits:false
total_frames:8
animateFrameStart:0
animateFrameEnd:7
animateFrameSpeed:0.35

[action_portrait]
unitShownInUI:portrait_firebat

[graphics]
image_offsetY:-12
icon_build: firebat_icon.png
image:        firebat.png
image_wreak:  NONE
image_turret: NONE
image_shadow:NONE
showEnergyBar:false
animation_moving_start: 0
animation_moving_end: 7
animation_moving_speed: 3
drawLayer:experimentals
lock_body_rotation_with_main_turret: true
rotate_with_direction: false
animation_direction_units: 45
animation_direction_strideX:0
animation_direction_strideY:1
animation_direction_starting:180
frame_width:  32
frame_height: 32

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
isFixedFiring: true
aimOffsetSpread: 0
turretSize: 12
maxAttackRange: 20
shootDelay: 0.924s
meleeEngangementDistance: 190
isMelee:true
showRangeUIGuide:false

[turret_T1T2]
showRangeUIGuide:false
canAttackLandUnits: if (self.resource(type='TerranInfantryAttack',equalTo=0) or self.resource(type='TerranInfantryAttack',equalTo=1)) and numberOfUnitsInNeutralTeam(withTag='disruptionWeb',withinRange=120)<=0
x: 0
y: 0
shoot_sound:attack.ogg
shoot_sound_vol:0.3
recoilOffset: 0
shoot_flame:CUSTOM:fire
projectile:T1
onShoot_freezeBodyMovementFor:0.462s
altProjectile: T2
altProjectileCondition: if self.resource(type='TerranInfantryAttack',equalTo=1)
onShoot_triggerActions:attackAnimTimer

[turret_T3T4]
canAttackLandUnits: if (self.resource(type='TerranInfantryAttack',equalTo=2) or self.resource(type='TerranInfantryAttack',equalTo=3)) and numberOfUnitsInNeutralTeam(withTag='disruptionWeb',withinRange=120)<=0
@copyFromSection:turret_T1T2
projectile:T3
altProjectile: T4
altProjectileCondition: if self.resource(type='TerranInfantryAttack',equalTo=3)

[projectile_T1]
areaDamage:82
areaRadius:18
areaDamageNoFalloff: true
life: 0
speed: 0
turnSpeed: 0
invisible: true
targetGround: true
explodeOnEndOfLife: true
disableLeadTargeting: true
explodeEffect: NONE
explodeEffectOnShield: NONE
mutator1_ifUnitWithTags:M
mutator1_ifUnitWithoutTags:haveShield
mutator1_areaDamageMultiplier:0.5
mutator2_ifUnitWithTags:L, building
mutator2_ifUnitWithoutTags:haveShield
mutator2_areaDamageMultiplier:0.25
mutator3_ifUnitWithTags: stasis
mutator3_areaDamageMultiplier:0
mutator4_ifUnitWithTags:hallucination
mutator4_areaDamageMultiplier:2
spawnProjectilesOnCreate: T1(recursionLimit=4, yOffsetRelative=30)

[projectile_T2]
areaDamage:84
spawnProjectilesOnCreate: T2(recursionLimit=4, yOffsetRelative=30)
@copyFromSection:projectile_T1

[projectile_T3]
areaDamage:86
spawnProjectilesOnCreate: T3(recursionLimit=4, yOffsetRelative=30)
@copyFromSection:projectile_T1

[projectile_T4]
areaDamage:88
spawnProjectilesOnCreate: T4(recursionLimit=4, yOffsetRelative=30)
@copyFromSection:projectile_T1

[movement]
movementType: LAND
moveSpeed: 1.1904
moveAccelerationSpeed: 20
moveDecelerationSpeed: 20
maxTurnSpeed: 40
turnAcceleration: 40
moveSlidingMode :false
moveIgnoringBody:false
reverseSpeedPercentage:0
joinsGroupFormations: false

[ai]
buildPriority: 0.8
noneInBaseExtraPriority: 0.8
noneGlobalExtraPriority: 0.8
maxEachBase: 10
#disableUse: true

[animation_attack]
onActions: attack
body_0s: {frame:9}
body_0.462s: {frame:10}
body_0.926s: {frame:10}

[hiddenAction_debuff_lockdown]
@copyFrom_skipThisSection: true

[hiddenAction_removeDebuff_lockdown]
@copyFrom_skipThisSection: true

[hiddenAction_feedback_debuff]
@copyFrom_skipThisSection: true

[effect_feedback]
@copyFrom_skipThisSection: true

[decal_grn_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByOwnPlayer:true
image:ROOT:/DATA/total/circle_smll_grn.png

[decal_red_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByEnemyPlayer:true
image:ROOT:/DATA/total/circle_smll_red.png

[decal_yellow_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByAllyNotOwnPlayer:true
image:ROOT:/DATA/total/circle_smll_yell.png

[decal_hp]
@copyFromSection: template_customBar
@define totalFrames:5
image:ROOT:/DATA/total/hp_6.png
frame_width:19
frame_height:5
frame:int((self.hp*100/self.maxHp)/(100/${totalFrames}))
yOffsetAbsolute:14