[core]
copyFrom:ROOT:/DATA/total/forcesAttack.template, ROOT:/DATA/Terran/terranUpgrades.template, ROOT:/DATA/total/debuffs.template, ROOT:/DATA/total/customUI.template, ROOT:/DATA/total/unit_portrait.template
name: siegeTank
tags:L,unit,mech,vis17,groundLargeUnit,gasCost
class: CustomUnitMetadata
price:Gas=1100
maxHp: 3800
energyMax: 3
energyRegen: 0.016666666
armour:2
mass: 9999
displayText_ru: Осадный танк
displayText: Siege tank
displayText_zh:攻城坦克
techLevel: 1
buildSpeed: 26s
#availableInDemo: true
radius: 30
displayRadius: 32
isBio: true
hideScorchMark: true
isBug: false
isUnrepairableUnit: false
softCollisionOnAll: 5
transportSlotsNeeded: 4
fogOfWarSightRange:17
effectOnDeath:CUSTOM:corpse
soundOnMoveOrder:siegeTank_yes_1.ogg:0.3,siegeTank_yes_2.ogg:0.3,siegeTank_yes_3.ogg:0.3,siegeTank_yes_4.ogg:0.3
soundOnAttackOrder:siegeTank_yes_1.ogg:0.3,siegeTank_yes_2.ogg:0.3,siegeTank_yes_3.ogg:0.3,siegeTank_yes_4.ogg:0.3
soundOnNewSelection:siegeTank_what_1.ogg:0.3,siegeTank_what_2.ogg:0.3,siegeTank_what_3.ogg:0.3,siegeTank_what_4.ogg:0.3
@memory attackTarget:unit
@memory shootAnim:float
updateUnitMemory: attackTarget=select(attacking!=nullUnit and attacking.hp>0, attacking, select(memory.attackTarget!=nullUnit and memory.attackTarget.teamId!=self.teamId and (memory.attackTarget.hp>0 or self.speed==0) and distanceBetween(self,memory.attackTarget)<=280,memory.attackTarget,self.getOffsetRelative(0,20)))
updateUnitMemoryRate:0.05s

[hiddenAction_shootAnim]
setUnitMemory:shootAnim=self.timeAlive

[effect_sparks]
alwayStartDirAtZero:true
attachedToUnit: false
life: 100
alpha: 10
image:ROOT:/DATA/Terran/units/explode.png
priority: critical
drawUnderUnits:false
total_frames:10
animateFrameStart:0
animateFrameEnd:9
animateFrameSpeed:0.2

[effect_corpse]
alwayStartDirAtZero:true
attachedToUnit: false
life: 90
alpha: 9
image:ROOT:/DATA/Terran/units/death.png
priority: critical
drawUnderUnits: true
animateFrameStart:0
animateFrameEnd:8
animateFrameSpeed:0.2
alsoPlaySound:death.wav
frame_width:  128
frame_height: 128

[hiddenAction_soundOnCreate]
autoTriggerOnEvent: created
playSoundToPlayer:siegeTank_ready.ogg
requireConditional:if self.customTarget1!=nullUnit
addWaypoint_type:move
addWaypoint_target_fromReference: customTarget1.readUnitMemory(name="rally",type="unit")

[action_siege]
alwaysSinglePress:true
isVisible: if self.globalTeamTags(includes='MachineShopTank')
isActive: if self.globalTeamTags(includes='MachineShopTank') and self.queueSize(equalTo=0) and self.resource.lockdown<=0 and self.resource.stasis<=0
isLocked: if self.isControlledByAI() and ((not self.isAttacking() and distanceBetween(self, self.activeWaypointTarget)>480) or not self.isAttacking())
price:  0
text_ru:Режим осады
text:Siege mode
text_zh:攻城模式
displayType:infoOnly
buildSpeed: 0s
ai_isHighPriority:true
iconExtraColor:#FFFFFFFF
iconExtraImage:ROOT:/DATA/Terran/siegeMod.png
iconImage:ROOT:/DATA/Terran/siegeMod.png
playSoundAtUnit:siege.ogg:0.3
alsoQueueAction:siege_2
setBodyRotation: 45
allowMultipleInQueue:false
clearAllWaypoints:true

[hiddenAction_siege_2]
convertTo: siegeTank2
buildSpeed: 4s
highPriorityQueue: true
whenBuilding_playAnimation:siege
whenBuilding_temporarilyConvertTo: siegeTank2
whenBuilding_cannotMove:true
whenBuilding_rotateTo: 45
setBodyRotation: 225
canPlayerCancel:false
clearAllWaypoints:true
convertTo_keepCurrentFields: fogOfWarSightRange, maxShield, armour
whenBuilding_temporarilyConvertTo_keepFields: fogOfWarSightRange, maxShield, armour

[hiddenAction_armour]
@copyFromSection:template_set_armour
@define armourUpgradeType: TerranVehicleArmor

[action_portrait]
unitShownInUI:portrait_siegeTank

[graphics]
image_offsetY:-4
icon_build: tank_icon.png
image:       tank_hull.png
image_wreak:  NONE
image_turret: NONE
image_shadow:NONE
animation_moving_start: 0
animation_moving_end: 2
animation_moving_speed: 4
lock_body_rotation_with_main_turret: true
drawLayer:experimentals
showEnergyBar:false
rotate_with_direction: false
animation_direction_units: 45
animation_direction_strideX:3
animation_direction_strideY:0
animation_direction_starting:180
frame_width: 84
frame_height: 84

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: if self.queueSize(lessThan=1)
canAttackUnderwaterUnits: false
isFixedFiring: false
turretSize: 6
turretTurnSpeed: 99
shootDelay: 1.554s
showRangeUIGuide:true
maxAttackRange: 280

[turret_T1T2]
showRangeUIGuide:false
canAttackCondition: if (self.resource(type='TerranVehicleAttack',equalTo=0) or self.resource(type='TerranVehicleAttack',equalTo=1)) and numberOfUnitsInNeutralTeam(withTag='disruptionWeb',withinRange=120,lessThan=1) and not self.hasActiveWaypoint(type="move")
x: 0
y: 0
projectile:T1
shoot_sound:attack.ogg
shoot_sound_vol:0.3
shoot_flame:NONE
recoilOffset: 0
onShoot_freezeBodyMovementFor:0.4s
altProjectile: T2
altProjectileCondition: if self.resource(type='TerranVehicleAttack',equalTo=1)
onShoot_playAnimation: attack
onShoot_triggerActions:shootAnim

[turret_T3T4]
canAttackCondition: if (self.resource(type='TerranVehicleAttack',equalTo=2) or self.resource(type='TerranVehicleAttack',equalTo=3)) and numberOfUnitsInNeutralTeam(withTag='disruptionWeb',withinRange=120,lessThan=1) and not self.hasActiveWaypoint(type="move")
@copyFromSection:turret_T1T2
projectile:T3
altProjectile: T4
altProjectileCondition: if self.resource(type='TerranVehicleAttack',equalTo=3)

[projectile_T1]
explodeEffect:CUSTOM:sparks
explodeEffectOnShield:CUSTOM:sparks
directDamage: 200
areaDamage: 140
areaRadius: 64
invisible: true
life: 20
instant: true
mutator1_ifUnitWithTags:M
mutator1_ifUnitWithoutTags:haveShield
mutator1_directDamageMultiplier:0.75
mutator2_ifUnitWithTags:S
mutator2_ifUnitWithoutTags:haveShield
mutator2_directDamageMultiplier:0.5
mutator3_ifUnitWithTags: zergSwarm
mutator3_directDamageMultiplier:0
mutator4_ifUnitWithTags:hallucination
mutator4_directDamageMultiplier:2

[projectile_T2]
directDamage:205
areaDamage: 145
@copyFromSection:projectile_T1

[projectile_T3]
directDamage:210
areaDamage: 145
@copyFromSection:projectile_T1

[projectile_T4]
directDamage:210
areaDamage: 150
@copyFromSection:projectile_T1

[movement]
movementType: LAND
moveSpeed: 0.71
moveAccelerationSpeed: 20
moveDecelerationSpeed: 20
maxTurnSpeed: 40
turnAcceleration: 40
moveSlidingMode :false
moveIgnoringBody:false
reverseSpeedPercentage:0
joinsGroupFormations: false

[ai]
buildPriority: 0.9
noneInBaseExtraPriority: 0.9
noneGlobalExtraPriority: 0.9
maxEachBase: 10

[animation_siege]
body_0s: {frame:9}
body_0.2s: {frame:10} 
body_0.4s: {frame:11}
body_0.6s: {frame:12}
body_0.8s: {frame:13}
body_1s: {frame:14}
body_1.6s: {frame:15}
body_1.75s: {frame:16}
body_1.9s: {frame:17}
body_2.05s: {frame:18}
body_2.2s: {frame:18}
direction_units: 0
direction_strideX:0
direction_strideY:0
direction_starting:180

[animation_attack]
body_0s: {frame:0}
body_0.4s: {frame:0}

[animation_siegeAI]
body_0s: {frame:0}
body_0.6s: {frame:0}

[decal_turret]
@define dir0: (directionBetween(self,memory.attackTarget)>=-22.5 and directionBetween(self,memory.attackTarget)<=22.5)
@define dir45: (directionBetween(self,memory.attackTarget)>=22.5 and directionBetween(self,memory.attackTarget)<=67.5)
@define dir90: (directionBetween(self,memory.attackTarget)>=67.5 and directionBetween(self,memory.attackTarget)<=112.5)
@define dir135: (directionBetween(self,memory.attackTarget)>=112.5 and directionBetween(self,memory.attackTarget)<=157.5)
@define dir180: ((directionBetween(self,memory.attackTarget)>=157.5 and directionBetween(self,memory.attackTarget)<=180) or (directionBetween(self,memory.attackTarget)<=-157.5 and directionBetween(self,memory.attackTarget)>=-180))
@define dir225: (directionBetween(self,memory.attackTarget)<=-112.5 and directionBetween(self,memory.attackTarget)>=-157.5)
@define dir270: (directionBetween(self,memory.attackTarget)<=-67.5 and directionBetween(self,memory.attackTarget)>=-112.5)
@define dir315: (directionBetween(self,memory.attackTarget)<=-22.5 and directionBetween(self,memory.attackTarget)>=-67.5)

@define t_dir0: (self.dir>=-22.5 and self.dir<=22.5)
@define t_dir45: (self.dir>=22.5 and self.dir<=67.5)
@define t_dir90: (self.dir>=67.5 and self.dir<=112.5)
@define t_dir135: (self.dir>=112.5 and self.dir<=157.5)
@define t_dir180: ((self.dir>=157.5 and self.dir<=180) or (self.dir<=-157.5 and self.dir>=-180))
@define t_dir225: (self.dir<=-112.5 and self.dir>=-157.5)
@define t_dir270: (self.dir<=-67.5 and self.dir>=-112.5)
@define t_dir315: (self.dir<=-22.5 and self.dir>=-67.5)

@define totalFrames:2
layer: afterBody
image:tank_turret.png
onlyOnNonPreview:false
alwaysStartDirAtZero:true
teamColors:true
frame_width:  128
frame_height: 128
frame: select(${dir0},4,select(${dir45},5,select(${dir90},6,select(${dir135},7,select(${dir180},0,select(${dir225},1,select(${dir270},2,select(${dir315},3,0))))))))*${totalFrames}+select(self.timeAlive-memory.shootAnim<=0.1 and memory.shootAnim!=0,1,0)
xOffsetAbsolute:select(${t_dir0},-13,select(${t_dir45},-9,select(${t_dir90},0,select(${t_dir135},9,select(${t_dir180},13,select(${t_dir225},10,select(${t_dir270},0,select(${t_dir315},-10,0))))))))
yOffsetAbsolute:-1*select(${t_dir0},10,select(${t_dir45},16,select(${t_dir90},19,select(${t_dir135},16,select(${t_dir180},10,select(${t_dir225},3,select(${t_dir270},1,select(${t_dir315},3,0))))))))+${graphics.image_offsetY}

[decal_ensnare_goo]
image:ROOT:/DATA/total/ensnare_goo_3.png

[decal_plague_goo]
image:ROOT:/DATA/total/plague_goo_3.png

[decal_defensive_matrix]
image:ROOT:/DATA/total/defensive_matrix_3.png

[decal_lockdown]
image:ROOT:/DATA/total/lockdown_3.png

[effect_mindControl]
image:ROOT:/DATA/total/mindControl_3.png
frame_width: 128
frame_height: 128

[hiddenAction_debuff_ensnare]
setUnitStats: moveSpeed=${movement.moveSpeed}*0.5, shootDelayMultiplier=1

[hiddenAction_feedback_debuff]
@copyFrom_skipThisSection: true

[effect_feedback]
@copyFrom_skipThisSection: true

[hiddenAction_debuff_maelstrom]
@copyFrom_skipThisSection: true

[hiddenAction_debuff_maelstrom_effect]
@copyFrom_skipThisSection: true

[hiddenAction_removeDebuff_maelstrom]
@copyFrom_skipThisSection: true

[decal_grn_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByOwnPlayer:true
image:ROOT:/DATA/total/circle_lrg_grn.png

[decal_red_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByEnemyPlayer:true
image:ROOT:/DATA/total/circle_lrg_red.png

[decal_yellow_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByAllyNotOwnPlayer:true
image:ROOT:/DATA/total/circle_lrg_yell.png

[decal_hp]
@copyFromSection: template_customBar
@define totalFrames:16
image:ROOT:/DATA/total/hp_17.png
frame_width:52
frame_height:5
frame:int((self.hp*100/self.maxHp)/(100/${totalFrames}))
yOffsetAbsolute:33