[core]
copyFrom:ROOT:/DATA/total/forcesAttack.template, ROOT:/DATA/Terran/terranUpgrades.template, ROOT:/DATA/total/debuffs.template, ROOT:/DATA/total/customUI.template, ROOT:/DATA/total/unit_portrait.template
name: siegeTank2
tags:L,unit,mech,vis17,groundLargeUnit,gasCost
class: CustomUnitMetadata
price:Gas=150
borrowResourcesWhileAlive:supply=2,displaySupply=-2
maxHp: 3800
armour:2
mass: 99999999
displayText_ru: Осадный танк
displayText: Siege tank
displayText_zh:攻城坦克
techLevel: 1
buildSpeed: 0.005
radius: 30
displayRadius: 32
isBio: true
hideScorchMark: true
isBug: false
isUnrepairableUnit: false
softCollisionOnAll: 5
fogOfWarSightRange:17
transportSlotsNeeded: 30
effectOnDeath:CUSTOM:corpse
soundOnAttackOrder:siegeTank_yes_1.ogg:0.3,siegeTank_yes_2.ogg:0.3,siegeTank_yes_3.ogg:0.3,siegeTank_yes_4.ogg:0.3
soundOnNewSelection:siegeTank_what_1.ogg:0.3,siegeTank_what_2.ogg:0.3,siegeTank_what_3.ogg:0.3,siegeTank_what_4.ogg:0.3

[effect_corpse]
alwayStartDirAtZero:true
attachedToUnit: false
life: 90
alpha: 9
image:ROOT:/DATA/Terran/units/death.png
priority: critical
drawUnderUnits: true
animateFrameStart:0
animateFrameEnd:8
animateFrameSpeed:0.2
alsoPlaySound:death.wav
frame_width:  128
frame_height: 128

[effect_sparks]
alwayStartDirAtZero:true
attachedToUnit: false
life: 90
alpha: 9
image: sparks.png
priority: critical
drawUnderUnits:false
total_frames:9
animateFrameStart:0
animateFrameEnd:8
animateFrameSpeed:0.25
scaleFrom:1
scaleTo:1
frame_width:  100
frame_height: 108

[hiddenAction_clearAttacking]
autoTriggerOnEvent:newWaypointGivenByPlayer
requireConditional: if distanceBetween(self, self.activeWaypointTarget)>480
autoTrigger: if distanceBetween(self, self.activeWaypointTarget)>480 or distanceBetween(self, self.attacking)>480
clearAllWaypoints:true

[action_mobile]
isActive: if self.queueSize(equalTo=0) and self.resource.lockdown<=0 and self.resource.stasis<=0
alwaysSinglePress:true
price:  0
text_ru:Мобильный режим
text:Mobile mode
text_zh:移动模式
displayType:infoOnly
buildSpeed: 0s
#ai_isDisabled:true
ai_isHighPriority: true
iconExtraColor:#FFFFFFFF
iconExtraImage:ROOT:/DATA/Terran/mobileMod.png
iconImage:ROOT:/DATA/Terran/mobileMod.png
playSoundAtUnit:siege2.ogg:0.3
alsoQueueAction:mobile_2
setBodyRotation: 45
allowMultipleInQueue:false
clearAllWaypoints:true
isLocked: if self.isControlledByAI() and self.isAttacking()

[hiddenAction_mobile_2]
convertTo: siegeTank
buildSpeed: 4s
highPriorityQueue: true
whenBuilding_playAnimation:siege
whenBuilding_cannotMove:true
whenBuilding_rotateTo: 45
setBodyRotation: 45
canPlayerCancel:false
convertTo_keepCurrentFields: fogOfWarSightRange, maxShield, armour

[hiddenAction_armour]
@copyFromSection:template_set_armour
@define armourUpgradeType: TerranVehicleArmor

[action_portrait]
unitShownInUI:portrait_siegeTank

[graphics]
image_offsetX:-7
image_offsetY:-18
icon_build: siegeTank_icon.png
image:       tank_2.png
image_wreak:  NONE
image_turret: NONE
image_shadow:NONE
showEnergyBar:false
showShotDelayBar:false
lock_body_rotation_with_main_turret: false
drawLayer:experimentals
rotate_with_direction: false
animation_direction_units: 45
animation_direction_strideX:3
animation_direction_strideY:0
animation_direction_starting:180
frame_width:  128
frame_height: 128

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: if self.queueSize(lessThan=1) and distanceBetween(self,attacking)<=480
canAttackUnderwaterUnits: false
isFixedFiring: true
turretSize: 6
aimOffsetSpread: 0.1
turretTurnSpeed: 3
maxAttackRange: 460
shootDelay: 4s
showRangeUIGuide:true

[turret_null]
canShoot: false
x: 0
y: 0
recoilOffset: 0
showRangeUIGuide:false

[turret_T1T2]
showRangeUIGuide:false
canAttackCondition: if (self.resource(type='TerranVehicleAttack',equalTo=0) or self.resource(type='TerranVehicleAttack',equalTo=1)) and numberOfUnitsInNeutralTeam(withTag='disruptionWeb',withinRange=120,lessThan=1) and ${attackLoS}
attachedTo: null
slave: true
x: 0
y: 0
projectile:T1
recoilOffset:0
shoot_sound:attack2.ogg
shoot_sound_vol:0.3
shoot_flame:NONE
onShoot_freezeBodyMovementFor:0.4s
shouldResetTurret:false
limitingMinRange:80
altProjectile: T2
altProjectileCondition: if self.resource(type='TerranVehicleAttack',equalTo=1)

[turret_T3T4]
canAttackCondition: if (self.resource(type='TerranVehicleAttack',equalTo=2) or self.resource(type='TerranVehicleAttack',equalTo=3)) and numberOfUnitsInNeutralTeam(withTag='disruptionWeb',withinRange=120,lessThan=1) and ${attackLoS}
@copyFromSection:turret_T1T2
projectile:T3
altProjectile: T4
altProjectileCondition: if self.resource(type='TerranVehicleAttack',equalTo=3)

[projectile_T1]
friendlyFire: true
explodeEffect:CUSTOM:sparks
explodeEffectOnShield:CUSTOM:sparks
directDamage: 240
areaDamage: 270
areaRadius:84
armourIgnoreAmount:100
areaDamageNoFalloff: true
invisible: true
life: 20
instant: true
mutator1_ifUnitWithTags:M
mutator1_ifUnitWithoutTags:haveShield
mutator1_areaDamageMultiplier:0.75
mutator2_ifUnitWithTags:S
mutator2_ifUnitWithoutTags:haveShield
mutator2_areaDamageMultiplier:0.5
mutator3_ifUnitWithTags: zergSwarm
mutator3_areaDamageMultiplier:0.25
mutator4_ifUnitWithTags: stasis
mutator4_areaDamageMultiplier:0
mutator5_ifUnitWithTags:hallucination
mutator5_areaDamageMultiplier:2
mutator6_ifUnitWithoutTags:GOVNO
mutator6_areaDamageMultiplier:0.5
spawnProjectilesOnCreate: T1_r1, T1_r2, T1_darkSwarm

[projectile_T2]
directDamage: 250
areaDamage: 280
spawnProjectilesOnCreate: T2_r1, T2_r2, T2_darkSwarm
@copyFromSection:projectile_T1

[projectile_T3]
directDamage: 250
areaDamage: 290
spawnProjectilesOnCreate: T3_r1, T3_r2, T3_darkSwarm
@copyFromSection:projectile_T1

[projectile_T4]
directDamage: 250
areaDamage: 295
spawnProjectilesOnCreate: T4_r1, T4_r2, T4_darkSwarm
@copyFromSection:projectile_T1



[projectile_T1_r1]
friendlyFire: true
explodeEffect:NONE
explodeEffectOnShield:NONE
areaDamage: ${projectile_T1.areaDamage}
areaRadius:30
areaDamageNoFalloff: true
armourIgnoreAmount:100
invisible: true
life: 20
instant: true
mutator1_ifUnitWithTags:M
mutator1_ifUnitWithoutTags:haveShield
mutator1_areaDamageMultiplier:0.75
mutator2_ifUnitWithTags:S
mutator2_ifUnitWithoutTags:haveShield
mutator2_areaDamageMultiplier:0.5
mutator3_ifUnitWithTags: zergSwarm
mutator3_areaDamageMultiplier:0.25
mutator4_ifUnitWithTags: stasis
mutator4_areaDamageMultiplier:0
mutator5_ifUnitWithTags:hallucination
mutator5_areaDamageMultiplier:2
mutator6_ifUnitWithoutTags:GOVNO
mutator6_areaDamageMultiplier:0.25

[projectile_T2_r1]
@copyFromSection:projectile_T1_r1
areaDamage: ${projectile_T2.areaDamage}

[projectile_T3_r1]
@copyFromSection:projectile_T1_r1
areaDamage: ${projectile_T3.areaDamage}

[projectile_T4_r1]
@copyFromSection:projectile_T1_r1
areaDamage: ${projectile_T4.areaDamage}



[projectile_T1_r2]
@copyFromSection:projectile_T1_r1
areaRadius:48
areaDamage: ${projectile_T1.areaDamage}
armourIgnoreAmount:IGNORE

[projectile_T2_r2]
@copyFromSection:projectile_T1_r2
areaDamage: ${projectile_T2.areaDamage}

[projectile_T3_r2]
@copyFromSection:projectile_T1_r2
areaDamage: ${projectile_T3.areaDamage}

[projectile_T4_r2]
@copyFromSection:projectile_T1_r2
areaDamage: ${projectile_T4.areaDamage}



[projectile_T1_darkSwarm]
explodeEffect:NONE
directDamage:${projectile_T1.areaDamage}
invisible: true
life: 20
instant: true
mutator1_ifUnitWithTags:M
mutator1_ifUnitWithoutTags:haveShield
mutator1_directDamageMultiplier:0.75
mutator2_ifUnitWithTags:S
mutator2_ifUnitWithoutTags:haveShield
mutator2_directDamageMultiplier:0.5
mutator3_ifUnitWithTags: zergSwarm
mutator3_directDamageMultiplier:0.25
mutator4_ifUnitWithTags: stasis
mutator4_directDamageMultiplier:0
mutator5_ifUnitWithoutTags: zergSwarm
mutator5_directDamageMultiplier:0
mutator6_ifUnitWithTags:hallucination
mutator6_directDamageMultiplier:2

[projectile_T2_darkSwarm]
directDamage:${projectile_T2.areaDamage}
@copyFromSection:projectile_T1_darkSwarm

[projectile_T3_darkSwarm]
directDamage:${projectile_T3.areaDamage}
@copyFromSection:projectile_T1_darkSwarm

[projectile_T4_darkSwarm]
directDamage:${projectile_T4.areaDamage}
@copyFromSection:projectile_T1_darkSwarm

[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 20
moveDecelerationSpeed: 20
maxTurnSpeed: 20
#turnAcceleration: 20
moveSlidingMode :false
moveIgnoringBody:false
reverseSpeedPercentage:0
joinsGroupFormations: false
ignoreMoveOrders:true

[ai]
buildPriority: 0.8
noneInBaseExtraPriority: 0.8
noneGlobalExtraPriority: 0.8
maxEachBase: 10

[animation_attack]
onActions: attack
body_0s: {frame:0}
body_0.1s: {frame:2}
body_0.15s: {frame:2}
pingPong: true

[animation_siege]
body_0s: {frame:18}
body_0.2s: {frame:17} 
body_0.4s: {frame:16}
body_0.6s: {frame:15}
body_1.2s: {frame:14}
body_1.35s: {frame:13}
body_1.5s: {frame:12}
body_1.75s: {frame:11}
body_1.9s: {frame:10}
body_2.05s: {frame:9}
body_2.2s: {frame:9}
direction_units: 0
direction_strideX:0
direction_strideY:0

[decal_ensnare_goo]
image:ROOT:/DATA/total/ensnare_goo_3.png

[decal_plague_goo]
image:ROOT:/DATA/total/plague_goo_3.png

[decal_lockdown]
image:ROOT:/DATA/total/lockdown_3.png

[decal_defensive_matrix]
image:ROOT:/DATA/total/defensive_matrix_3.png

[effect_mindControl]
image:ROOT:/DATA/total/mindControl_3.png
frame_width: 128
frame_height: 128

[hiddenAction_debuff_ensnare]
setUnitStats: moveSpeed=${movement.moveSpeed}*0, shootDelayMultiplier=1

[hiddenAction_feedback_debuff]
@copyFrom_skipThisSection: true

[effect_feedback]
@copyFrom_skipThisSection: true

[hiddenAction_debuff_maelstrom]
@copyFrom_skipThisSection: true

[hiddenAction_debuff_maelstrom_effect]
@copyFrom_skipThisSection: true

[hiddenAction_removeDebuff_maelstrom]
@copyFrom_skipThisSection: true

[decal_grn_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByOwnPlayer:true
image:ROOT:/DATA/total/circle_lrg_grn.png

[decal_red_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByEnemyPlayer:true
image:ROOT:/DATA/total/circle_lrg_red.png

[decal_yellow_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByAllyNotOwnPlayer:true
image:ROOT:/DATA/total/circle_lrg_yell.png

[decal_hp]
@copyFromSection: template_customBar
@define totalFrames:16
image:ROOT:/DATA/total/hp_17.png
frame_width:52
frame_height:5
frame:int((self.hp*100/self.maxHp)/(100/${totalFrames}))
yOffsetAbsolute:33