[core]
copyFrom:ROOT:/DATA/total/forcesAttack.template, ROOT:/DATA/Protoss/protossUpgrades.template, ROOT:/DATA/total/debuffs.template, ROOT:/DATA/total/customUI.template, ROOT:/DATA/total/unit_portrait.template
name: dragoon
tags:L,unit,mech,vis17,groundUnit,canBeHallucinated
class: CustomUnitMetadata
price:Gas=450
maxHp: 1400
maxShield:700
shieldRegen:0.1
shieldDisplayOnlyDeflection:true
armour:2
mass: 500
displayText_ru: Драгун
displayText: Dragoon
displayText_zh:龙骑士
techLevel: 1
buildSpeed: 24s
radius: 20
displayRadius: 22
hideScorchMark:false
isBio: true
isBug: false
fogOfWarSightRange:17
isUnrepairableUnit: true
softCollisionOnAll: 5
transportSlotsNeeded: 4
effectOnDeath:NONE
soundOnMoveOrder:dragoon_yes.ogg:0.3,dragoon_yes_1.ogg:0.3,dragoon_yes_2.ogg:0.3,dragoon_yes_3.ogg:0.3,dragoon_yes_4.ogg:0.3,dragoon_yes_5.ogg:0.3,dragoon_yes_6.ogg:0.3
soundOnAttackOrder:dragoon_yes.ogg:0.3,dragoon_yes_1.ogg:0.3,dragoon_yes_2.ogg:0.3,dragoon_yes_3.ogg:0.3,dragoon_yes_4.ogg:0.3,dragoon_yes_5.ogg:0.3,dragoon_yes_6.ogg:0.3
soundOnNewSelection:dragoon_what.ogg:0.3,dragoon_what_1.ogg:0.3,dragoon_what_2.ogg:0.3,dragoon_what_3.ogg:0.3,dragoon_what_4.ogg:0.3,dragoon_what_5.ogg:0.3,dragoon_what_6.ogg:0.3,dragoon_what_7.ogg:0.3
@global hallucinationUnit:dragoon
@global supplyAdd:2
@memory attackAnimTimer:float

[hiddenAction_onDestroyed_nonHallucination]
spawnEffects:CUSTOM:corpse

[hiddenAction_Recall]
autoTrigger: if numberOfUnitsInTeam(withTag='recall',withinRange=100,greaterThan=0) and nearestUnit(withinRange=120, withTag='recall', relation='own').customTarget1!=nullUnit
clearAllWaypoints: true
teleportTo: nearestUnit(withinRange=120, withTag='recall', relation='own').customTarget1

[hiddenAction_soundOnCreate]
autoTriggerOnEvent: created
playSoundToPlayer:dragoon_ready.ogg
requireConditional:if self.customTarget1!=nullUnit and customTarget1.tags(includes="building")
addWaypoint_type:move
addWaypoint_target_fromReference: customTarget1.readUnitMemory(name="rally",type="unit")

[effect_corpse]
alwayStartDirAtZero:true
attachedToUnit: false
life: 70
alpha: 70
image: death.png
priority: critical
drawUnderUnits: true
total_frames:7
animateFrameStart:0
animateFrameEnd:6
animateFrameSpeed:0.15
alsoPlaySound:dead.ogg

[hiddenAction_attackRange]
autoTrigger: if self.globalTeamTags(includes='CybernaticsCoreRange') and not self.tags(includes='attackRange')
temporarilyAddTags: attackRange
setUnitStats: maxAttackRange+=60

[hiddenAction_armour]
@copyFromSection:template_set_shieldArmour
@define armourUpgradeType: ProtossGroundArmor

[hiddenAction_arbiter_cloak]
autoTrigger: if numberOfUnitsInTeam(withTag='arbiter',withinRange=220)>0 and self.resource.hallucination==0
convertTo:dragoon_vis
convertTo_keepCurrentFields: armour
playSoundAtUnit:ROOT:/DATA/total/cloaking.ogg:0.4

[hiddenAction_attackAnimTimer]
setUnitMemory:attackAnimTimer=self.timeAlive

[hiddenAction_stopAttackAnim]
@define animSize:0.5
autoTrigger: if memory.attackAnimTimer>0 and self.timeAlive-memory.attackAnimTimer>=${animSize} and self.isMoving
stopLastAnimation:true
setUnitMemory:attackAnimTimer=0

[effect_sparks]
alwayStartDirAtZero:true
attachedToUnit: false
life: 140
alpha: 14
hSpeed: 0
image: ROOT:/DATA/Protoss/units/spark.png
priority: critical
drawUnderUnits:false
total_frames:14
animateFrameStart:0
animateFrameEnd:13
animateFrameSpeed:0.25
scaleFrom:1
scaleTo: 1

[action_portrait]
unitShownInUI:portrait_dragoon

[graphics]
image_offsetY:-9
icon_build: dragoon_icon.png
image:        dragoon.png
image_wreak:  dead.png
image_turret: NONE
image_shadow:NONE
drawLayer:experimentals
lock_body_rotation_with_main_turret: false
rotate_with_direction: false
animation_direction_units: 0
animation_direction_strideX:0
animation_direction_strideY:0
#animation_direction_starting:180
frame_width:  96
frame_height: 96

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
isFixedFiring: true
turretSize: 1
turretTurnSpeed: 3
shootDelay: 1.26s
maxAttackRange: 180
showRangeUIGuide:true

[turret_T1T2]
showRangeUIGuide:false
canAttackCondition: if (self.resource(type='ProtossGroundAttack',equalTo=0) or self.resource(type='ProtossGroundAttack',equalTo=1)) and numberOfUnitsInNeutralTeam(withTag='disruptionWeb',withinRange=120)<=0
x: 0
y: 0
shoot_sound:attack.ogg
shoot_sound_vol:0.3
recoilOffset: 0
shoot_flame:NONE
barrelHeight: 10
projectile:T1
onShoot_freezeBodyMovementFor:0.5s
altProjectile: T2
altProjectileCondition: if self.resource(type='ProtossGroundAttack',equalTo=1)
onShoot_triggerActions:attackAnimTimer

[turret_T3T4]
canAttackCondition: if (self.resource(type='ProtossGroundAttack',equalTo=2) or self.resource(type='ProtossGroundAttack',equalTo=3)) and numberOfUnitsInNeutralTeam(withTag='disruptionWeb',withinRange=120)<=0
@copyFromSection:turret_T1T2
projectile:T3
altProjectile: T2
altProjectileCondition: if self.resource(type='ProtossGroundAttack',equalTo=3)

[projectile_T1]
directDamage: 106
areaDamage: 80
areaRadius: 60
life: 160
speed: 4
targetSpeed: 8
image:photon.png
explodeEffect:CUSTOM:sparks
explodeEffectOnShield:CUSTOM:sparks
mutator1_ifUnitWithTags:M
mutator1_ifUnitWithoutTags:haveShield
mutator1_directDamageMultiplier:0.75
mutator2_ifUnitWithTags:S
mutator2_ifUnitWithoutTags:haveShield
mutator2_directDamageMultiplier:0.5
mutator3_ifUnitWithTags: zergSwarm
mutator3_directDamageMultiplier:0
mutator4_ifUnitWithTags:hallucination
mutator4_directDamageMultiplier:2

[projectile_T2]
directDamage:112
areaDamage: 82
@copyFromSection:projectile_T1

[projectile_T3]
directDamage:116
areaDamage: 84
@copyFromSection:projectile_T1

[projectile_T4]
directDamage:122
areaDamage: 86
@copyFromSection:projectile_T1

[movement]
movementType: LAND
moveSpeed: 1.29
moveAccelerationSpeed: 20
moveDecelerationSpeed: 20
maxTurnSpeed: 40
turnAcceleration: 40
reverseSpeedPercentage:0
joinsGroupFormations: false

[ai]
buildPriority: 0.8
noneInBaseExtraPriority: 0.8
noneGlobalExtraPriority: 0.8
maxEachBase: 10

[animation_idle]
onActions: idle
body_0s: {frame:0}
body_0.7s: {frame:7}
body_0.8s: {frame:7}
direction_units: 0
direction_strideX:0
direction_strideY:0
#direction_starting:180

[animation_move]
onActions: move
body_0s: {frame:8}
body_0.35s: {frame:15}
body_0.4s: {frame:15}
direction_units: 90
direction_strideX:8
direction_strideY:0
direction_starting:180

[animation_attack]
onActions: attack
body_0s: {frame:40}
body_0.15s: {frame:43}
body_1.3s: {frame:43}
body_1.50s: {frame:48}
body_1.55s: {frame:48}
direction_units: 0
direction_strideX:0
direction_strideY:0
#direction_starting:180

[decal_hallucination_texture]
@copyFromSection: template_hallucination_texture
@define dir0: (self.dir>=-45 and self.dir<=45)
@define dir90: (self.dir>=45 and self.dir<=135)
@define dir180: ((self.dir>=135 and self.dir<=180) or (self.dir<=-135 and self.dir>=-180))
@define dir270: (self.dir<=-45 and self.dir>=-135)
@define totalFrames:8
image: dragoon_illusion.png
frame: select(self.isMoving, (select(${dir0},2,select(${dir90},3,select(${dir180},0,select(${dir270},1,0))))*${totalFrames}), 0)

[decal_hallucination_energy]
@define totalFrames:10
image:ROOT:/DATA/total/energy_10.png
frame_width:31
frame_height:5
yOffsetAbsolute:30

[decal_ensnare_goo]
image:ROOT:/DATA/total/ensnare_goo_2.png

[decal_plague_goo]
image:ROOT:/DATA/total/plague_goo_2.png

[decal_defensive_matrix]
image:ROOT:/DATA/total/defensive_matrix_2.png

[decal_lockdown]
image:ROOT:/DATA/total/lockdown_2.png

[effect_mindControl]
image:ROOT:/DATA/total/mindControl_2.png
frame_width: 64
frame_height: 64

[hiddenAction_feedback_debuff]
@copyFrom_skipThisSection: true

[effect_feedback]
@copyFrom_skipThisSection: true

[hiddenAction_debuff_maelstrom]
@copyFrom_skipThisSection: true

[hiddenAction_debuff_maelstrom_effect]
@copyFrom_skipThisSection: true

[hiddenAction_removeDebuff_maelstrom]
@copyFrom_skipThisSection: true

[decal_grn_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByOwnPlayer:true
image:ROOT:/DATA/total/circle_med_grn.png

[decal_red_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByEnemyPlayer:true
image:ROOT:/DATA/total/circle_med_red.png

[decal_yellow_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByAllyNotOwnPlayer:true
image:ROOT:/DATA/total/circle_med_yell.png

[decal_hp]
@copyFromSection: template_customBar
@define totalFrames:9
image:ROOT:/DATA/total/hp_p10.png
frame_width:31
frame_height:7
frame:int((self.hp*100/self.maxHp)/(100/${totalFrames}))
yOffsetAbsolute:23

[decal_shield]
@copyFromSection: template_customBar
@define totalFrames:9
image:ROOT:/DATA/total/shield_p10.png
frame_width:31
frame_height:7
frame:int((self.shield*100/self.maxShield)/(100/${totalFrames}))
yOffsetAbsolute:23