[core]
copyFrom:ROOT:/DATA/total/baseAttack.template, ROOT:/DATA/total/debuffs.template, ROOT:/DATA/Terran/buildings.template, ROOT:/DATA/total/customUI.template
name: MachineShop
tags: MachineShop,building,MShop,mech,vis8,gasCost
class: CustomUnitMetadata
price:0
maxHp: 750
mass: 9000
armour:1
hideScorchMark: true
fogOfWarSightRange:8
displayText_ru:Мастерская
displayText:Machine shop
displayText_zh:机械车间
footprint: -1,-1,1,1
constructionFootprint:-1,-1,1,1
buildingToFootprintOffsetX:10
buildingToFootprintOffsetY:2
exit_x:0
exit_y:40
techLevel: 1
buildSpeed: 1
radius: 40
buildingSelectionOffset: -8
isBuilder: true
nanoRange: 0
isBuilding: true
isBio: true
numBitsOnDeath: 12
isUnrepairableUnit:false
effectOnDeath:CUSTOM:corpse
soundOnNewSelection:Factory.ogg:0.3
@memory connectionFrame:float
updateUnitMemory: connectionFrame=select(self.getOffsetAbsolute(x=-90,y=-20).self.hasUnitInTeam(withTag="Factory",withinRange=10) and self.getOffsetAbsolute(x=-90,y=-20).nearestUnit(withTag="Factory",withinRange=10,relation="own").z==self.z and memory.connectionFrame<3, memory.connectionFrame+1, select((not self.getOffsetAbsolute(x=-90,y=-20).self.hasUnitInTeam(withTag="Factory",withinRange=10) or self.getOffsetAbsolute(x=-90,y=-20).nearestUnit(withTag="Factory",withinRange=10,relation="own").z!=self.z) and memory.connectionFrame>0, memory.connectionFrame-1, memory.connectionFrame))
updateUnitMemoryRate:0.1s

[effect_corpse]
alwayStartDirAtZero:true
attachedToUnit: false
life: 120
alpha: 12
image:ROOT:/DATA/Terran/death.png
alsoPlaySound:ROOT:/DATA/total/buildingExplode.wav
priority: critical
drawUnderUnits:false
animateFrameStart:0
animateFrameEnd:11
animateFrameSpeed:0.2
frame_width:  252
frame_height: 200

[action_clear]
isVisible:true
isActive:true
displayType:infoOnly
buildSpeed:0s
price:0
text_ru:Уничтожить
text:Delete
text_zh:自毁
iconExtraColor:#FFFFFFFF
iconExtraImage:ROOT:/DATA/total/delete.png
addResources:hp=-1500
ai_isDisabled:true

[action_upgrade_SiegeMode]
isVisible: if ((self.getOffsetAbsolute(x=-90,y=-20).self.hasUnitInTeam(withTag="Factory",withinRange=10) and not self.isControlledByAI()) or (self.hasUnitInTeam(withTag="Factory", withinRange=100) and self.isControlledByAI())) and not self.globalTeamTags(includes='MachineShopTank') and not self.globalTeamTags(includes='TankLocked')
buildSpeed:65s
displayType: queueUnit
price:Gas:800
text_ru:Улучшение
text:Upgrade
text_zh:升级
description_ru:Осадный режим\n Позволяет танкам переходить в осадный режим
description: Siege mode/n Every Tank gains the Siege mode ability
description_zh:攻城模式/n每辆坦克都获得攻城模式能力
playSoundToPlayer:ROOT:/DATA/Terran/research.ogg:0.4
ai_isHighPriority:true
onlyOneUnitAtATime: true
iconExtraColor:#FFFFFFFF
iconExtraImage:ROOT:/DATA/Terran/siegeMod.png
allowMultipleInQueue:false
addGlobalTeamTags:MachineShopTank
whenBuilding_playAnimation:build

[action_upgrade_SpiderMine]
isVisible: if ((self.getOffsetAbsolute(x=-90,y=-20).self.hasUnitInTeam(withTag="Factory",withinRange=10) and not self.isControlledByAI()) or (self.hasUnitInTeam(withTag="Factory", withinRange=100) and self.isControlledByAI())) and not self.globalTeamTags(includes='MachineShopMine')
buildSpeed:63s
displayType: queueUnit
price:Gas:400
text_ru:Улучшение
text:Upgrade
text_zh:升级
description_ru:Мины\n Стервятники смогут пользоваться минами
description: Spider mine/n Every Vulture gains the Spider mine ability
description_zh:蜘蛛雷/n每辆秃鹫战车都获得释放蜘蛛雷的能力
playSoundToPlayer:ROOT:/DATA/Terran/research.ogg:0.4
ai_isHighPriority:true
onlyOneUnitAtATime: true
iconExtraColor:#FFFFFFFF
iconExtraImage:spiderMine.png
allowMultipleInQueue:false
addGlobalTeamTags:MachineShopMine
whenBuilding_playAnimation:build

[action_upgrade_IonThrusters]
isVisible: if ((self.getOffsetAbsolute(x=-90,y=-20).self.hasUnitInTeam(withTag="Factory",withinRange=10) and not self.isControlledByAI()) or (self.hasUnitInTeam(withTag="Factory", withinRange=100) and self.isControlledByAI())) and not self.globalTeamTags(includes='MachineShopThrusters')
buildSpeed:63s
displayType: queueUnit
price:Gas:450
text_ru:Улучшение
text_zh:升级
text:Upgrade
description_ru:Ионные ускорители\n Увеличивает скорость Стервятников
description:Ion thrusters/n Increases Vulture speed
description_zh:推进器/n增加秃鹫战车的速度
playSoundToPlayer:ROOT:/DATA/Terran/research.ogg:0.4
onlyOneUnitAtATime: true
iconExtraColor:#FFFFFFFF
iconExtraImage:vultureSpeed.png
allowMultipleInQueue:false
addGlobalTeamTags:MachineShopThrusters
whenBuilding_playAnimation:build

[action_upgrade_CharonBoosters]
isVisible: if ((self.getOffsetAbsolute(x=-90,y=-20).self.hasUnitInTeam(withTag="Factory",withinRange=10) and not self.isControlledByAI()) or (self.hasUnitInTeam(withTag="Factory", withinRange=100) and self.isControlledByAI())) and not self.globalTeamTags(includes='GoliathRange')
buildSpeed:84s
displayType: queueUnit
price:Gas:500
text_ru:Улучшение
text_zh:升级
text:Upgrade
description_ru:Ускорители Харон\n Увеличивает дальность воздушной атаки Голиафов
description:Charon boosters/n Increases every Goliath's air attack range
description_zh:卡戎助推器/n增加每个歌莉娅的空中攻击范围
playSoundToPlayer:ROOT:/DATA/Terran/research.ogg:0.4
onlyOneUnitAtATime: true
ai_isHighPriority:true
iconExtraColor:#FFFFFFFF
iconExtraImage:goliathRange.png
allowMultipleInQueue:false
addGlobalTeamTags:GoliathRange
whenBuilding_playAnimation:build

[hiddenAction_removeAllQueue]
autoTrigger: if ((not self.getOffsetAbsolute(x=-90,y=-20).self.hasUnitInTeam(withTag="Factory",withinRange=10) or self.getOffsetAbsolute(x=-90,y=-20).nearestUnit(withTag="Factory",withinRange=10,relation="own").z!=self.z) and not self.isControlledByAI()) or (not self.hasUnitInTeam(withTag="Factory", withinRange=100) and self.isControlledByAI()) and self.queueSize>0
refundAllQueuedItems:true

[hiddenAction_enemyCapture]
autoTrigger: if self.getOffsetAbsolute(x=-90,y=-20).nearestUnit(withTag="Factory",withinRange=10,relation="any")!=nullUnit and self.getOffsetAbsolute(x=-90,y=-20).nearestUnit(withTag="Factory",withinRange=10,relation="any").z==self.z and self.getOffsetAbsolute(x=-90,y=-20).nearestUnit(withTag="Factory",withinRange=10,relation="any").teamId!=self.teamId
refundAllQueuedItems:true
switchToTeam: self.getOffsetAbsolute(x=-90,y=-20).nearestUnit(withTag="Factory",withinRange=10,relation="any").teamId

[decal_connection]
image:machineShop_connection.png
onlyOnNonPreview:true
alwaysStartDirAtZero:true
teamColors:false
xOffsetAbsolute:-16
yOffsetAbsolute:-18
frame_width:  84
frame_height: 84
frame: memory.connectionFrame
onlyWhileAlive: true

[decal_fire]
@copyFromSection: template_fire
isVisible: if self.hp<self.maxHp*0.85
image:ROOT:/DATA/Terran/fire.png
frame: select(self.hp<self.maxHp*0.5,12,0)+(self.timeAlive*12%12)
xOffsetAbsolute:-7
yOffsetAbsolute:-18

[graphics]
total_frames: 4
image_offsetX:6
image_offsetY:4
image:        machineShop.png
image_back:   NONE
image_wreak:ROOT:/DATA/Terran/dead.png
image_turret: NONE
drawLayer:experimentals
#AUTO
image_shadow:shadow_ms.png
shadowOffsetX:6
shadowOffsetY:4
animation_idle_start: 0
animation_idle_end: 0
animation_idle_speed: 36

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

turretSize: 0
turretTurnSpeed: 6


maxAttackRange: 0
shootDelay: 80

[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01

maxTurnSpeed: 0
turnAcceleration: 0.1



[ai]
buildPriority: 0.1
noneInBaseExtraPriority: 0.1
noneGlobalExtraPriority: 0.1
maxEachBase: 4
recommendedInEachBaseNum: 4
#disableUse: true

[animation_build]
body_0s: {frame:0}
body_0.06s: {frame:1}
body_0.12s: {frame:2}
body_0.18s: {frame:3}
body_0.24s: {frame:3}

[decal_grn_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByOwnPlayer:true
image:ROOT:/DATA/total/circle_lrg_grn_2.png
yOffsetAbsolute:5

[decal_red_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByEnemyPlayer:true
image:ROOT:/DATA/total/circle_lrg_red_2.png
yOffsetAbsolute:5

[decal_yellow_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByAllyNotOwnPlayer:true
image:ROOT:/DATA/total/circle_lrg_yell_2.png
yOffsetAbsolute:5

[decal_hp]
@copyFromSection: template_customBar
@define totalFrames:23
image:ROOT:/DATA/total/hp_24.png
frame_width:73
frame_height:5
frame:int((self.hp*100/self.maxHp)/(100/${totalFrames}))
yOffsetAbsolute:40