[core]
copyFrom:ROOT:/DATA/total/forcesAttack.template, ROOT:/DATA/Protoss/protossUpgrades.template, ROOT:/DATA/total/debuffs.template, ROOT:/DATA/total/customUI.template, ROOT:/DATA/total/unit_portrait.template
name: shuttle
tags:L,mech,unit,vis17, canBeHallucinated, shuttle
class: CustomUnitMetadata
price:Gas=125
maxHp: 800
maxShield:800
shieldRegen:0.12
shieldDisplayOnlyDeflection:true
armour:1
mass: 500
displayText_ru: Шаттл
displayText: Shuttle
displayText_zh:穿梭机
techLevel: 1
buildSpeed: 38s
#availableInDemo: true
radius: 20
displayRadius: 22
isBio: true
hideScorchMark: true
isBug: false
fogOfWarSightRange:17
isUnrepairableUnit: true
softCollisionOnAll: 250
maxTransportingUnits:8
transportUnitsUnloadDelayBetweenEachUnit: 0.8s
exit_moveAwayAmount: 0
exitHeightIgnoreParent: true
exit_heightOffset: 0
transportUnitsBlockOtherTransports:false
effectOnDeath:NONE
soundOnMoveOrder:shuttle_yes.ogg:0.3,shuttle_yes_1.ogg:0.3
soundOnNewSelection:shuttle_what.ogg:0.3,shuttle_what_1.ogg:0.3
@global hallucinationUnit:shuttle
@global supplyAdd:2

[hiddenAction_onDestroyed_nonHallucination]
spawnEffects:CUSTOM:corpse

[action_unload]
isVisible: if self.transportingCount>0
isActive: if self.transportingCount>0
text_ru: Выгрузить
text: Unload
text_zh:空投
displayType:infoOnly
buildSpeed: 0s
highPriorityQueue: false
fireTurretXAtGround: null
fireTurretXAtGround_withProjectile:null
#onlyOneUnitAtATime: true
ai_isDisabled:true
iconExtraColor:#FFFFFFFF
iconExtraImage:ROOT:/DATA/total/unload.png
addWaypoint_type: move
addWaypoint_target_fromReference: unitRef thisActionTarget
clearAllWaypoints: true
startUnloadingTransport:true

[action_loadUp]
isVisible: if not self.hasFlag(id=1)
isActive: if not self.hasFlag(id=1)
text_ru: Погрузить
text: LoadUp
text_zh:装载
displayType:infoOnly
buildSpeed: 0s
highPriorityQueue: false
fireTurretXAtGround: null
fireTurretXAtGround_withProjectile:null
#onlyOneUnitAtATime: true
ai_isDisabled:true
iconExtraColor:#FFFFFFFF
iconExtraImage:ROOT:/DATA/total/loadUp.png
alsoTriggerAction:loadUp_2
alsoTriggerOrQueueActionConditional: if thisActionTarget.nearestUnit(withinRange=25, relation='any') != nullUnit and not thisActionTarget.nearestUnit(withinRange=25, relation='any').isFlying()

[hiddenAction_loadUp_2]
addWaypoint_type: loadUp
addWaypoint_target_fromReference: unitRef thisActionTarget.nearestUnit(withinRange=25, relation='any')
addWaypoint_target_nearestUnit_team: own
clearAllWaypoints: true

[hiddenAction_loadUp_moveToTarget]
autoTriggerOnEvent: newMessage(withTag="moveTransport")
addWaypoint_type: touchTarget
addWaypoint_target_fromReference: eventSource
clearAllWaypoints:true

[action_unload_slot1]
@define slotId: 0
#id:unloadSlots${slotId}
alwaysSinglePress:true
isVisible: if transporting(slot=${slotId})!=nullUnit
isActive: if not self.isOverwater() and not self.isOverLiquid() and not self.isOverClift() and transporting(slot=${slotId})!=nullUnit
forceUnloadTransportNow: true
forceUnloadTransportNow_onlyOnSlot: ${slotId}
addActionCooldownTime: 0.8s
addActionCooldownApplyToActions: unload_slot1, unload_slot2, unload_slot3, unload_slot4, unload_slot5, unload_slot6, unload_slot7, unload_slot8
price: 0
text: [
textAddUnitName: unitRef self.transporting(slot=${slotId})
textPostFix: ]
unitShownInUI: unitRef self.transporting(slot=${slotId})
displayType:infoOnly
buildSpeed: 0s
highPriorityQueue: true
ai_isDisabled:true

[action_unload_slot2]
@define slotId: 1
@copyFromSection: action_unload_slot1

[action_unload_slot3]
@define slotId: 2
@copyFromSection: action_unload_slot1

[action_unload_slot4]
@define slotId: 3
@copyFromSection: action_unload_slot1

[action_unload_slot5]
@define slotId: 4
@copyFromSection: action_unload_slot1

[action_unload_slot6]
@define slotId: 5
@copyFromSection: action_unload_slot1

[action_unload_slot7]
@define slotId: 6
@copyFromSection: action_unload_slot1

[action_unload_slot8]
@define slotId: 7
@copyFromSection: action_unload_slot1

[turret_null]
x: 0
y: 0
limitingRange:9999
canShoot: false
showRangeUIGuide:false

[projectile_null]
life:0
speed:0
directDamage: 0
targetGround: true
explodeEffect:NONE

[hiddenAction_soundOnLoad]
autoTriggerOnEvent: transportingNewUnit
requireConditional: if self.resource.hallucination==0
playSoundAtUnit: load.wav:0.3

[hiddenAction_soundOnUnload]
autoTriggerOnEvent: transportUnloadedOrRemovedUnit
requireConditional: if self.resource.hallucination==0
playSoundAtUnit: unload.wav:0.3

[hiddenAction_hallucinationUnload]
autoTriggerOnEvent: transportingNewUnit
requireConditional: if self.resource.hallucination>0
forceUnloadTransportNow: true

[hiddenAction_soundOnCreate]
autoTriggerOnEvent: created
playSoundToPlayer:shuttle_ready.ogg
requireConditional:if self.customTarget1!=nullUnit and customTarget1.tags(includes="building")
addWaypoint_type:move
addWaypoint_target_fromReference: customTarget1.readUnitMemory(name="rally",type="unit")

[hiddenAction_Recall]
autoTrigger: if numberOfUnitsInTeam(withTag='recall',withinRange=100,greaterThan=0) and nearestUnit(withinRange=120, withTag='recall', relation='own').customTarget1!=nullUnit
clearAllWaypoints: true
teleportTo: nearestUnit(withinRange=120, withTag='recall', relation='own').customTarget1

[effect_corpse]
alwayStartDirAtZero:true
attachedToUnit: false
life: 100
alpha: 10
image: ROOT:/DATA/Protoss/death.png
priority: critical
drawUnderUnits:false
total_frames:10
animateFrameStart:0
animateFrameEnd:9
animateFrameSpeed:0.2
frame_width:  190
frame_height: 152
alsoPlaySound:dead.ogg

[hiddenAction_armour]
@copyFromSection:template_set_shieldArmour
@define armourUpgradeType: ProtossAirArmor

[hiddenAction_speed]
autoTrigger: if self.globalTeamTags(includes='RoboFacilitySupportSpeed') and not self.tags(includes='speed')
temporarilyAddTags: speed
setUnitStats: moveSpeed+=0.6636

[hiddenAction_arbiter_cloak]
autoTrigger: if numberOfUnitsInTeam(withTag='arbiter',withinRange=220)>0 and self.resource.hallucination==0
convertTo:shuttle_vis
convertTo_keepCurrentFields: armour
playSoundAtUnit:ROOT:/DATA/total/cloaking.ogg:0.4

[action_portrait]
unitShownInUI:portrait_shuttle

[graphics]
image_offsetY:-10
total_frames: 2
icon_build: shuttle_icon.png
image:        shuttle.png
image_wreak:  NONE
image_turret: NONE
image_shadow: AUTO_ANIMATED
animation_moving_start: 1
animation_moving_end: 2
animation_moving_speed: 2.5
showTransportBar:false
lock_body_rotation_with_main_turret: true
rotate_with_direction: false
animation_direction_units: 45
animation_direction_strideX:3
animation_direction_strideY:0
animation_direction_starting:180
frame_width:  60
frame_height: 60

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
maxAttackRange:0

[movement]
movementType: AIR
moveSpeed: 1.3212
moveAccelerationSpeed: 0.03
moveDecelerationSpeed: 0.02
maxTurnSpeed: 40
turnAcceleration: 40
reverseSpeedPercentage:0
joinsGroupFormations: false
slowDeathFall: false
startingHeightOffset: 35

[ai]
useAsTransport: true
buildPriority: 0.7
noneInBaseExtraPriority: 0.7
noneGlobalExtraPriority: 0.7
maxGlobal: 5

[decal_hallucination_texture]
@copyFromSection: template_hallucination_texture
@define totalFrames:3
image: shuttle_illusion.png

[decal_hallucination_energy]
@define totalFrames:10
image:ROOT:/DATA/total/energy_10.png
frame_width:31
frame_height:5
yOffsetAbsolute:30

[decal_ensnare_goo]
image:ROOT:/DATA/total/ensnare_goo_2.png

[decal_acidSpores]
image:ROOT:/DATA/total/acidSpores_M.png
frame_width:34
frame_height:34

[decal_plague_goo]
image:ROOT:/DATA/total/plague_goo_2.png

[decal_defensive_matrix]
image:ROOT:/DATA/total/defensive_matrix_2.png

[decal_lockdown]
image:ROOT:/DATA/total/lockdown_2.png

[effect_mindControl]
image:ROOT:/DATA/total/mindControl_2.png
frame_width: 64
frame_height: 64

[hiddenAction_feedback_debuff]
@copyFrom_skipThisSection: true

[effect_feedback]
@copyFrom_skipThisSection: true

[hiddenAction_debuff_maelstrom]
@copyFrom_skipThisSection: true

[hiddenAction_debuff_maelstrom_effect]
@copyFrom_skipThisSection: true

[hiddenAction_removeDebuff_maelstrom]
@copyFrom_skipThisSection: true

[decal_grn_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByOwnPlayer:true
image:ROOT:/DATA/total/circle_med_grn.png

[decal_red_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByEnemyPlayer:true
image:ROOT:/DATA/total/circle_med_red.png

[decal_yellow_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByAllyNotOwnPlayer:true
image:ROOT:/DATA/total/circle_med_yell.png

[decal_hp]
@copyFromSection: template_customBar
@define totalFrames:9
image:ROOT:/DATA/total/hp_p10.png
frame_width:31
frame_height:7
frame:int((self.hp*100/self.maxHp)/(100/${totalFrames}))
yOffsetAbsolute:23

[decal_shield]
@copyFromSection: template_customBar
@define totalFrames:9
image:ROOT:/DATA/total/shield_p10.png
frame_width:31
frame_height:7
frame:int((self.shield*100/self.maxShield)/(100/${totalFrames}))
yOffsetAbsolute:23