[core]
copyFrom:ROOT:/DATA/total/forcesAttack.template, ROOT:/DATA/Protoss/protossUpgrades.template, ROOT:/DATA/total/debuffs.template, ROOT:/DATA/total/customUI.template, ROOT:/DATA/total/unit_portrait.template
name:highTemplar
tags:highTemplar,S,unit,bio,haveEnergy,vis17,groundUnit,canBeHallucinated
class: CustomUnitMetadata
price:Gas=750
maxHp:350
maxShield:500
shieldRegen:0.2
shieldDisplayOnlyDeflection:true
energyMax:200
energyRegen:0.0124
energyStartingPercentage:0.25
mass: 500
displayText_ru: Высший тамплиер
displayText: High templar
displayText_zh:高阶圣堂武士
techLevel: 1
buildSpeed: 32s
#availableInDemo: true
radius: 12
hideScorchMark: false
displayRadius: 14
isBio: true
isBug: false
softCollisionOnAll: 5
fogOfWarSightRange:17
transportSlotsNeeded: 2
effectOnDeath:NONE
maxTransportingUnits:2
transportUnitsRequireTag: merge
transportUnitsBlockOtherTransports:false
transportUnitsCanUnloadUnits: false
transportUnitsAddUnloadOption: false
soundOnMoveOrder:highTemplar_yes.ogg:0.3,highTemplar_yes_1.ogg:0.3,highTemplar_yes_2.ogg:0.3,highTemplar_yes_3.ogg:0.3
soundOnAttackOrder:highTemplar_yes.ogg:0.3,highTemplar_yes_1.ogg:0.3,highTemplar_yes_2.ogg:0.3,highTemplar_yes_3.ogg:0.3
soundOnNewSelection:highTemplar_what.ogg:0.3,highTemplar_what_1.ogg:0.3,highTemplar_what_2.ogg:0.3,highTemplar_what_3.ogg:0.3

@memory storm:unit
@memory hallucination:unit
@memory trail_frame:float
@memory trail_pos:unit
@global trail_maxFrames:3
@global hallucinationUnit:highTemplar
@global supplyAdd:2

updateUnitMemory: """
trail_frame=select(memory.trail_frame<${trail_maxFrames},min(memory.trail_frame+1,${trail_maxFrames}),select(self.isMoving,0,memory.trail_frame+1)),
trail_pos=select(memory.trail_frame<${trail_maxFrames},memory.trail_pos,self.getOffsetRelative(0,-0.5).getAsMarker)
"""
updateUnitMemoryRate:0.06s

[hiddenAction_onDestroyed_nonHallucination]
spawnEffects:CUSTOM:corpse

[hiddenAction_Recall]
autoTrigger: if numberOfUnitsInTeam(withTag='recall',withinRange=100,greaterThan=0) and nearestUnit(withinRange=120, withTag='recall', relation='own').customTarget1!=nullUnit
clearAllWaypoints: true
teleportTo: nearestUnit(withinRange=120, withTag='recall', relation='own').customTarget1

[hiddenAction_soundOnCreate]
autoTriggerOnEvent: created
playSoundToPlayer:highTemplar_ready.ogg
requireConditional:if self.customTarget1!=nullUnit and customTarget1.tags(includes="building")
addWaypoint_type:move
addWaypoint_target_fromReference: customTarget1.readUnitMemory(name="rally",type="unit")

[effect_corpse]
alwayStartDirAtZero:true
attachedToUnit: false
yOffsetAbsolute: -12
life: 70
alpha: 7
image: death.png
priority: critical
drawUnderUnits: true
animateFrameStart:0
animateFrameEnd:6
animateFrameSpeed:0.2
frame_width:  82
frame_height: 82
alsoPlaySound:dead.ogg

[action_archont]
isVisible: if numberOfUnitsInTeam(withTag='highTemplar',withinRange=200,greaterThan=1) and self.resource.hallucination==0
isActive: if numberOfUnitsInTeam(withTag='highTemplar',withinRange=200,greaterThan=1)
price:Gas=4500
buildSpeed:0s
displayType:infoOnly
text_ru:Архон
text:Archon
text_zh:融合
onlyOneUnitAtATime: true
temporarilyAddTags: merge
temporarilyRemoveTags: highTemplar
iconExtraColor:#FFFFFFFF
iconExtraImage:archon_icon.png
iconImage:archon_icon.png
clearActiveWaypoint: true
alsoTriggerAction:archont_2

[hiddenAction_archont_2]
addWaypoint_type: loadInto
addWaypoint_target_randomUnit_tagged: highTemplar
addWaypoint_target_randomUnit_team: own
addWaypoint_target_randomUnit_maxRange: 200
addWaypoint_triggerActionIfFailed: archont_2

[hiddenAction_archont_3]
autoTrigger: if self.transportingCount(greaterThan=0) and self.queueSize(lessThan=1)
deleteNumUnitsFromTransport:1
addResources: energy=9999, hp=999, shield=9999
alsoQueueAction: convert
spawnEffects:CUSTOM:archont

[hiddenAction_convert]
buildSpeed: 0.2s
whenBuilding_playAnimation: create
whenBuilding_temporarilyConvertTo: archontBuild
whenBuilding_cannotMove:true
convertTo_keepCurrentFields: armour
whenBuilding_temporarilyConvertTo_keepFields: armour
convertTo: archontBuild
clearAllWaypoints:true

[effect_archont]
attachedToUnit: false
life: 100
alpha: 10
showInFog:false
image: ROOT:/DATA/total/null.png
alsoPlaySound:archont.wav
priority: critical

[hiddenAction_stop]
autoTriggerOnEvent: newWaypointGivenByPlayer
requireConditional: if self.tags(includes='merge')
autoTrigger: if self.hasParent() and self.tags(includes='merge')
temporarilyRemoveTags: merge
temporarilyAddTags: highTemplar

[action_psiStorm]
isVisible: if self.globalTeamTags(includes='PsiStorm') and self.resource.hallucination==0
isActive: if self.resource.maelstrom<=0 and self.resource.stasis<=0 and memory.storm==null
price:energy=75
buildSpeed:0s
displayType:infoOnly
text_ru:Псионический шторм
text:Psionic storm
text_zh:灵能风暴
isGuiBlinking: if memory.storm!=null
fireTurretXAtGround:null
fireTurretXAtGround_withProjectile:null
onlyOneUnitAtATime: true
ai_isDisabled: true
iconExtraColor:#FFFFFFFF
iconExtraImage:ROOT:/DATA/Protoss/psistorm.png
addResources:energy=75
setUnitMemory: storm=thisActionTarget
addWaypoint_type: move
clearAllWaypoints:true
addWaypoint_target_fromReference: thisActionTarget

[hiddenAction_psiStorm_2]
autoTrigger: if memory.storm!=nullUnit and distanceBetween(self, memory.storm)<=310 and self.energy>=75 and self.resource.maelstrom<=0 and self.resource.stasis<=0
fireTurretXAtGround:null_2
fireTurretXAtGround_withProjectile:storm
fireTurretXAtGround_withTarget: memory.storm
clearAllWaypoints:true
addResources:energy=-75
setUnitMemory: storm=null

[hiddenAction_removePsiStorm]
autoTriggerOnEvent:newWaypointGivenByPlayer
requireConditional: if memory.storm!=nullUnit
autoTrigger: if memory.storm!=nullUnit and self.energy<75
setUnitMemory: storm=null


[action_hallucination]
isVisible: if self.globalTeamTags(includes='Hallucination') and self.resource.hallucination==0
isActive: if self.resource.maelstrom<=0 and self.resource.stasis<=0 and memory.hallucination==null
alwaysSinglePress:true
price:energy=100
displayType:infoOnly
buildSpeed:0s
text_ru:Иллюзия
text:Hallucination
text_zh:幻觉
isGuiBlinking: if memory.hallucination!=null
onlyOneUnitAtATime: true
fireTurretXAtGround:null
fireTurretXAtGround_withProjectile:null
ai_isDisabled: true
iconExtraColor:#FFFFFFFF
iconExtraImage:ROOT:/DATA/Protoss/hallucination.png
addResources:energy=100
alsoTriggerAction:hallucination_2
alsoTriggerOrQueueActionConditional: if createMarker(x=thisActionTarget.x,y=thisActionTarget.y,teamId=self.teamId).nearestUnit(withinRange=40, withTag='canBeHallucinated', relation='own') != nullUnit and createMarker(x=thisActionTarget.x,y=thisActionTarget.y,teamId=self.teamId).nearestUnit(withinRange=40, withTag='canBeHallucinated', relation='own') != self

[hiddenAction_hallucination_2]
addWaypoint_type: touchTarget
clearAllWaypoints:true
addWaypoint_target_fromReference: createMarker(x=thisActionTarget.x,y=thisActionTarget.y,teamId=self.teamId).nearestUnit(withinRange=40, withTag='canBeHallucinated', relation='own')
setUnitMemory: hallucination=createMarker(x=thisActionTarget.x,y=thisActionTarget.y,teamId=self.teamId).nearestUnit(withinRange=40, withTag='canBeHallucinated', relation='own')

[hiddenAction_hallucination_3]
autoTrigger: if memory.hallucination!=nullUnit and memory.hallucination.hp>0 and distanceBetween(self, memory.hallucination)<=310 and self.energy>=100 and self.resource.maelstrom<=0 and self.resource.stasis<=0
sendMessageTo: memory.hallucination
sendMessageWithTags:Hallucination
fireTurretXAtGround:null_2
fireTurretXAtGround_withProjectile:null
fireTurretXAtGround_withTarget: memory.hallucination
clearAllWaypoints:true
addResources:energy=-100
alsoTriggerAction:removeHallucination

[hiddenAction_removeHallucination]
autoTriggerOnEvent:newWaypointGivenByPlayer
requireConditional: if memory.hallucination!=nullUnit
autoTrigger: if memory.hallucination!=nullUnit and (self.energy<100 or memory.hallucination.hp<=0)
setUnitMemory: hallucination=null


[hiddenAction_armour]
@copyFromSection:template_set_shieldArmour
@define armourUpgradeType: ProtossGroundArmor

[hiddenAction_maxEnergy]
autoTrigger: if self.globalTeamTags(includes='KhaydarinAmulet') and self.maxEnergy!=250 and self.resource.hallucination==0
temporarilyAddTags: maxEnergy
setUnitStats: maxEnergy=250

[hiddenAction_startingEnergy]
autoTriggerOnEvent:created
requireConditional: if self.globalTeamTags(includes='KhaydarinAmulet') and self.resource.hallucination==0
setUnitStats:energy=62

[hiddenAction_arbiter_cloak]
autoTrigger: if numberOfUnitsInTeam(withTag='arbiter',withinRange=220)>0 and self.resource.hallucination==0
convertTo:highTemplar_vis
convertTo_keepCurrentFields: armour
playSoundAtUnit:ROOT:/DATA/total/cloaking.ogg:0.4

[action_portrait]
unitShownInUI:portrait_highTemplar

[graphics]
image_offsetY:-12
total_frames: 13
icon_build: highTemplar_icon.png
image:        highTemplar.png
image_wreak:  NONE
image_turret: NONE
image_shadow: ROOT:/DATA/total/shadow.png
animation_moving_start: 7
animation_moving_end: 7
animation_moving_speed: 4
animation_idle_start: 0
animation_idle_end: 6
animation_idle_speed: 5
animation_attack_start: 8
animation_attack_end: 12
animation_attack_speed: 5
showTransportBar:false
lock_body_rotation_with_main_turret: true
drawLayer:experimentals
rotate_with_direction: false
animation_direction_units: 45
animation_direction_strideX:13
animation_direction_strideY:0
animation_direction_starting:180
frame_width:  68
frame_height: 68

[attack]
canAttack: true
canAttackFlyingUnits: if self.isControlledByAI()
canAttackLandUnits: if self.isControlledByAI()
canAttackUnderwaterUnits: false
isFixedFiring: true
aimOffsetSpread: 0
turretMultiTargeting:true
turretSize: 10
turretTurnSpeed: 3
maxAttackRange: 320
shootDelay: 2s
showRangeUIGuide:false

[turret_null]
x: 0
y: 0
limitingRange:9999
recoilOffset: 0
shoot_flame:NONE
showRangeUIGuide:false
canAttackCondition: if self.globalTeamTags(includes='GOVNO')

[turret_null_2]
x: 0
y: 0
limitingRange:9999
recoilOffset: 0
shoot_flame:NONE
showRangeUIGuide:false
onShoot_playAnimation: attack
canAttackCondition: if self.globalTeamTags(includes='GOVNO')
onShoot_freezeBodyMovementFor:0.63s

[projectile_null]
directDamage: 0
life: 0
speed: 0
invisible:true
explodeEffect:NONE

[turret_stormForAI]
x: 0
y: 0
limitingRange:320
canAttackCondition: if self.isControlledByAI() and self.energy(greaterThan=74) and self.globalTeamTags(includes='PsiStorm')
energyUsage=75
projectile:storm
onShoot_freezeBodyMovementFor:0.63s
showRangeUIGuide:false
canOnlyAttackUnitsWithoutTags: building, interceptor

[projectile_storm]
life: 20
invisible: true
instant:true
directDamage: 0
targetGround: true
spawnUnit:PsiStorm
disableLeadTargeting: true
explodeEffect:NONE

[movement]
movementType: LAND
moveSpeed: 0.9912
moveAccelerationSpeed: 0.05
moveDecelerationSpeed: 0.05
maxTurnSpeed: 40
turnAcceleration: 40
reverseSpeedPercentage:0
joinsGroupFormations: false

[ai]
buildPriority: 0.9
noneInBaseExtraPriority: 0.9
noneGlobalExtraPriority: 0.9
maxGlobal: 3

[animation_attack]
body_0s: {frame:8}
body_0.05s: {frame:8}
body_0.2s: {frame:12}
body_0.25s: {frame:12}

[animation_create]
body_0s: {frame:5}
body_0.1s: {frame:6}
body_0.2s: {frame:6}

[decal_hallucination_texture]
@copyFromSection: template_hallucination_texture
@define totalFrames:13
image: highTemplar_illusion.png

[decal_hallucination_energy]
@define totalFrames:7
image:ROOT:/DATA/total/energy_7.png
frame_width:22
frame_height:5
yOffsetAbsolute:21

[decal_trail]
@define dir0: (self.dir>=-22.5 and self.dir<=22.5)
@define dir45: (self.dir>=22.5 and self.dir<=67.5)
@define dir90: (self.dir>=67.5 and self.dir<=112.5)
@define dir135: (self.dir>=112.5 and self.dir<=157.5)
@define dir180: ((self.dir>=157.5 and self.dir<=180) or (self.dir<=-157.5 and self.dir>=-180))
@define dir225: (self.dir<=-112.5 and self.dir>=-157.5)
@define dir270: (self.dir<=-67.5 and self.dir>=-112.5)
@define dir315: (self.dir<=-22.5 and self.dir>=-67.5)
@define totalFrames:4
isVisible: if memory.trail_frame<=${trail_maxFrames} and self.y<=memory.trail_pos.y+1.5
layer: afterBody
image: highTemplar_trail.png
frame_width: 42
frame_height:42
onlyOnNonPreview:true
alwaysStartDirAtZero:true
onlyWhileAlive:true
teamColors:false
yOffsetAbsolute:${graphics.image_offsetY}
frame: (select(${dir0},4,select(${dir45},5,select(${dir90},6,select(${dir135},7,select(${dir180},0,select(${dir225},1,select(${dir270},2,select(${dir315},3,0))))))))*${totalFrames})+memory.trail_frame
basePosition:memory.trail_pos

[decal_trail_2]
@copyFromSection: decal_trail
isVisible: if memory.trail_frame<=${trail_maxFrames} and self.y>memory.trail_pos.y+1.5
layer: beforeBody

[hiddenAction_debuff_lockdown]
@copyFrom_skipThisSection: true

[hiddenAction_removeDebuff_lockdown]
@copyFrom_skipThisSection: true

[decal_grn_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByOwnPlayer:true
image:ROOT:/DATA/total/circle_smll_grn.png

[decal_red_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByEnemyPlayer:true
image:ROOT:/DATA/total/circle_smll_red.png

[decal_yellow_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByAllyNotOwnPlayer:true
image:ROOT:/DATA/total/circle_smll_yell.png

[decal_hp]
@copyFromSection: template_customBar
@define totalFrames:6
image:ROOT:/DATA/total/hp_p7.png
frame_width:22
frame_height:7
frame:int((self.hp*100/self.maxHp)/(100/${totalFrames}))
yOffsetAbsolute:14

[decal_shield]
@copyFromSection: template_customBar
@define totalFrames:6
image:ROOT:/DATA/total/shield_p7.png
frame_width:22
frame_height:7
frame:int((self.shield*100/self.maxShield)/(100/${totalFrames}))
yOffsetAbsolute:14

[decal_energy]
@copyFromSection: template_customBar
@define totalFrames:7
isVisible: if self.maxEnergy>0
onlyWhenSelectedByOwnPlayer:true
onlyWhenSelectedByAnyPlayer:false
image:ROOT:/DATA/total/energy_7.png
frame_width:22
frame_height:5
frame:int((self.energy*100/self.maxEnergy)/(100/${totalFrames}))
yOffsetAbsolute:21