[core]
copyFrom:ROOT:/DATA/total/baseAttack.template, ROOT:/DATA/Protoss/protossUpgrades.template, ROOT:/DATA/Protoss/buildings.template, ROOT:/DATA/total/customUI.template
name: CybernaticsCore
tags:CybernaticsCore,building,vis17
class: CustomUnitMetadata
price: 0
maxHp: 1800
maxShield:900
shieldRegen:0.12
shieldDisplayOnlyDeflection:true
mass: 9000
armour:1
hideScorchMark: false
fogOfWarSightRange:17
displayText_ru: Кибернетическое ядро
displayText: Cybernetics core
displayText_zh:控制核心
footprint: -2,-2,2,1
constructionFootprint:-2,-2,2,1
buildingToFootprintOffsetX:10
buildingToFootprintOffsetY:0
techLevel: 1
buildSpeed: 1
selfBuildRate: 1
radius: 60
isBuilder: true
nanoRange: 0
isBuilding: true
isBio: false
numBitsOnDeath: 12
isUnrepairableUnit:true
soundOnNewSelection:CCore.ogg:0.3
effectOnDeath: CUSTOM:corpse

[decal_light]
@copyFromSection: template_light
image:cybernaticsCore_light.png
frame_width:96
frame_height:128
yOffsetAbsolute:0

[decal_fire]
@copyFromSection: template_fire
isVisible: if self.hp<self.maxHp*0.85
image:ROOT:/DATA/Protoss/fire3.png
frame: select(self.hp<self.maxHp*0.7,12,0)+(self.timeAlive*12%12)
xOffsetAbsolute:21
yOffsetAbsolute:6

[decal_fire_2]
@copyFromSection: template_fire
isVisible: if self.hp<self.maxHp*0.55
image:ROOT:/DATA/Protoss/fire.png
frame: select(self.hp<self.maxHp*0.4,12,0)+(self.timeAlive*12%12)
xOffsetAbsolute:0
yOffsetAbsolute:-38

[effect_corpse]
alwayStartDirAtZero:true
attachedToUnit: false
life: 100
alpha: 10
image: ROOT:/DATA/Protoss/death.png
alsoPlaySound:ROOT:/DATA/total/buildingExplode.wav
priority: critical
drawUnderUnits:false
total_frames:10
animateFrameStart:0
animateFrameEnd:9
animateFrameSpeed:0.2
frame_width:  190
frame_height: 152

[action_clear]
isVisible:true
isActive:true
displayType:infoOnly
buildSpeed:0s
price:0
text_ru:Уничтожить
text:Delete
text_zh:自毁
iconExtraColor:#FFFFFFFF
iconExtraImage:ROOT:/DATA/total/delete.png
addResources:hp=-100,shield=-100
ai_isDisabled:true

[hiddenAction_notWorking]
autoTrigger: if not self.hasUnitInTeam(withTag='pylon',withinRange=300) and self.tags(includes='CybernaticsCore')
temporarilyRemoveTags:CybernaticsCore
refundAllQueuedItems:true

[hiddenAction_Working]
autoTrigger: if self.hasUnitInTeam(withTag='pylon',withinRange=300) and not self.tags(includes='CybernaticsCore')
temporarilyAddTags:CybernaticsCore

[action_armorT2]
@define upgradeLevel:1
isVisible: if self.resource.ProtossAirArmor==${upgradeLevel-1}
isActive: if self.resource.ProtossAirArmor==${upgradeLevel-1} and self.hasUnitInTeam(withTag='pylon',withinRange=300)
buildSpeed:${148+20*upgradeLevel}s
displayType: queueUnit
text_ru:Улучшение
text:Upgrade
text_zh:升级
description_ru:Воздушная броня\n След. уровень: ${upgradeLevel}\n Увеличивает защиту всех воздушных юнитов Протоссов
description:Air armor\n Next level: ${upgradeLevel}\n Increases the armor value of all Protoss flyer forces
description_zh:空中护甲\n 下一级别：${upgradeLevel}\n增加所有神族飞行部队的护甲值
price:Minerals=${75+75*upgradeLevel},Gas=${75+75*upgradeLevel}
playSoundToPlayer:ROOT:/DATA/Protoss/upgrade.ogg:0.5
onlyOneUnitAtATime: true
iconExtraColor:#FFFFFFFF
iconExtraImage:airArmor.png
allowMultipleInQueue:false
ai_isHighPriority:true
whenBuilding_playAnimation:build
setResourcesWithLogic: ProtossAirArmor=${upgradeLevel}

[action_armorT3]
@copyFromSection: action_armorT2
@define upgradeLevel:2
isLocked: if not self.hasUnitInTeam(withTag='FleetBeacon')
isLockedMessage:Requires:\n  >Fleet beacon
isLockedMessage_zh:需要:\n >舰队航标
isLockedMessage_ru:Требуется:\n  >Маяк флотилии

[action_armorT4]
@copyFromSection: action_armorT2
@define upgradeLevel:3
isLocked: if not self.hasUnitInTeam(withTag='FleetBeacon')
isLockedMessage:Requires:\n  >Fleet beacon
isLockedMessage_zh:需要:\n >舰队航标
isLockedMessage_ru:Требуется:\n  >Маяк флотилии

[action_attackT2]
@define upgradeLevel:1
isVisible: if self.resource.ProtossAirAttack==${upgradeLevel-1}
isActive: if self.resource.ProtossAirAttack==${upgradeLevel-1} and self.hasUnitInTeam(withTag='pylon',withinRange=300)
buildSpeed:${148+20*upgradeLevel}s
displayType: queueUnit
text_ru:Улучшение
text:Upgrade
text_zh:升级
description_ru:Воздушное оружие\n След. уровень: ${upgradeLevel}\n Увеличивает урон всех воздушных юнитов Протоссов
description:Air weapons\n Next level: ${upgradeLevel}\n Increases the attack damage of all Protoss flyer forces
description_zh:空中武器\n 下一级别：${upgradeLevel}\n增加所有神族飞行部队的攻击伤害
price:Minerals=${25+75*upgradeLevel},Gas=${25+75*upgradeLevel}
playSoundToPlayer:ROOT:/DATA/Protoss/upgrade.ogg:0.5
onlyOneUnitAtATime: true
iconExtraColor:#FFFFFFFF
iconExtraImage:airAttack.png
allowMultipleInQueue:false
ai_isHighPriority:true
whenBuilding_playAnimation:build
setResourcesWithLogic: ProtossAirAttack=${upgradeLevel}

[action_attackT3]
@copyFromSection: action_attackT2
@define upgradeLevel:2
isLocked: if not self.hasUnitInTeam(withTag='FleetBeacon')
isLockedMessage:Requires:\n  >Fleet beacon
isLockedMessage_zh:需要:\n >舰队航标
isLockedMessage_ru:Требуется:\n  >Маяк флотилии

[action_attackT4]
@copyFromSection: action_attackT2
@define upgradeLevel:3
isLocked: if not self.hasUnitInTeam(withTag='FleetBeacon')
isLockedMessage:Requires:\n  >Fleet beacon
isLockedMessage_zh:需要:\n >舰队航标
isLockedMessage_ru:Требуется:\n  >Маяк флотилии

[action_dragoonRange]
isVisible: if not self.globalTeamTags(includes='CybernaticsCoreRange')
isActive: if not self.globalTeamTags(includes='CybernaticsCoreRange') and self.hasUnitInTeam(withTag='pylon',withinRange=300)
buildSpeed:105s
displayType: queueUnit
text_ru:Улучшение
text:Upgrade
text_zh:升级
description_ru:Сингулярный заряд\n Увеличивается дальность атаки Драгунов
description:Singularity charge\n Increases Dragoons attack range
description_zh:奇点充能\n增加龙骑士的攻击范围
price:Minerals=150,Gas=150
playSoundToPlayer:ROOT:/DATA/Protoss/research.ogg:0.5
onlyOneUnitAtATime: true
iconExtraColor:#FFFFFFFF
iconExtraImage:dragoonRange.png
allowMultipleInQueue:false
addGlobalTeamTags:CybernaticsCoreRange
ai_isHighPriority:true
whenBuilding_playAnimation:build

[graphics]
#image_offsetY:-8
total_frames: 3
image: cybernaticsCore.png
image_wreak:  ROOT:/DATA/Protoss/dead2.png
drawLayer:experimentals
image_shadow:shadow.png
shadowOffsetX:0
shadowOffsetY:0

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
maxAttackRange: 0

[movement]
movementType: NONE

[ai]
buildPriority: 0.09
noneInBaseExtraPriority: 0.09
noneGlobalExtraPriority: 0.09
maxEachBase: 1
maxGlobal: 1
recommendedInEachBaseNum: 1
upgradedFrom: buildCybernaticsCore

[animation_build]
body_0s: {frame:0}
body_0.05s: {frame:1}
body_0.1s: {frame:2}
body_0.15s: {frame:2}

[decal_grn_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByOwnPlayer:true
image:ROOT:/DATA/total/circle_bldng_grn.png

[decal_red_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByEnemyPlayer:true
image:ROOT:/DATA/total/circle_bldng_red.png

[decal_yellow_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByAllyNotOwnPlayer:true
image:ROOT:/DATA/total/circle_bldng_yell.png

[decal_hp]
@copyFromSection: template_customBar
@define totalFrames:29
image:ROOT:/DATA/total/hp_p30.png
frame_width:91
frame_height:7
frame:int((self.hp*100/self.maxHp)/(100/${totalFrames}))
yOffsetAbsolute:41

[decal_shield]
@copyFromSection: template_customBar
@define totalFrames:29
image:ROOT:/DATA/total/shield_p30.png
frame_width:91
frame_height:7
frame:int((self.shield*100/self.maxShield)/(100/${totalFrames}))
yOffsetAbsolute:41