[core]
copyFrom:ROOT:/DATA/total/forcesAttack.template, ROOT:/DATA/Terran/terranUpgrades.template, ROOT:/DATA/total/debuffs.template, ROOT:/DATA/total/customUI.template, ROOT:/DATA/total/unit_portrait.template
name: battlecruiser
tags: mech,L,unit,haveEnergy,vis17,gasCost
class: CustomUnitMetadata
price:Gas=4500
maxHp: 7700
armour:3
energyMax:200
energyRegen:0.0124
energyStartingPercentage:0.25
mass: 5000000
displayText_ru: Крейсер
displayText: Battlecruiser
displayText_zh:战列舰
techLevel: 1
buildSpeed:57s
#availableInDemo: true
radius: 44
displayRadius: 46
isBio: true
hideScorchMark: true
isBug: false
isUnrepairableUnit: false
softCollisionOnAll: 250
explodeOnDeath: true
fogOfWarSightRange:17
explodeOnDeathGroundCollosion: true
effectOnDeath:CUSTOM:corpse
soundOnMoveOrder:battlecruiser_yes.ogg:0.3,battlecruiser_yes_1.ogg:0.3,battlecruiser_yes_2.ogg:0.3,battlecruiser_yes_3.ogg:0.3
soundOnAttackOrder:battlecruiser_yes.ogg:0.3,battlecruiser_yes_1.ogg:0.3,battlecruiser_yes_2.ogg:0.3,battlecruiser_yes_3.ogg:0.3
soundOnNewSelection:battlecruiser_what.ogg:0.3,battlecruiser_what_1.ogg:0.3,battlecruiser_what_2.ogg:0.3,battlecruiser_what_3.ogg:0.3

@memory yamato:unit
@memory yamatoTarget:unit
@memory shootAnim:float

[effect_sparks]
alwayStartDirAtZero:true
attachedToUnit: false
life: 100
alpha: 10
image:explode.png
priority: critical
drawUnderUnits:false
total_frames:10
animateFrameStart:0
animateFrameEnd:9
animateFrameSpeed:0.2
frame_width:  40
frame_height: 40

[effect_yamatoSparks]
alwayStartDirAtZero:true
attachedToUnit: false
life: 140
alpha: 14
image:yamatoSparks.png
priority: critical
drawUnderUnits:false
animateFrameStart:0
animateFrameEnd:13
animateFrameSpeed:0.2
frame_width:  144
frame_height: 144

[effect_yamato_shoot]
alwayStartDirAtZero:true
attachedToUnit: false
life: 50
alpha: 5
image:yamato_shoot.png
priority: critical
drawUnderUnits:false
animateFrameStart:6
animateFrameEnd:10
animateFrameSpeed:0.2
frame_width:  160
frame_height: 160

[effect_corpse]
alwayStartDirAtZero:true
attachedToUnit: false
life: 90
alpha: 9
image:ROOT:/DATA/Terran/units/death.png
priority: critical
drawUnderUnits:false
animateFrameStart:0
animateFrameEnd:8
animateFrameSpeed:0.2
alsoPlaySound:death.wav
frame_width:  128
frame_height: 128

[hiddenAction_soundOnCreate]
autoTriggerOnEvent: created
playSoundToPlayer:battlecruiser_ready.ogg
requireConditional:if self.customTarget1!=nullUnit
addWaypoint_type:move
addWaypoint_target_fromReference: customTarget1.readUnitMemory(name="rally",type="unit")

[action_yamato]
isVisible: if self.globalTeamTags(includes='PhysicalLabButtlecruiser')
isActive: if self.resource.lockdown<=0 and self.resource.stasis<=0 and memory.yamato==null
alwaysSinglePress:true
price:energy=150
displayType:infoOnly
buildSpeed:0s
text_ru:Пушка Ямато
text:Yamato gun
text_zh:大和炮
isGuiBlinking: if memory.yamato!=null
onlyOneUnitAtATime: true
fireTurretXAtGround:null
fireTurretXAtGround_withProjectile:null
ai_isDisabled: true
iconExtraColor:#FFFFFFFF
iconExtraImage:ROOT:/DATA/Terran/yamato.png
addResources:energy=150
alsoTriggerAction:yamato_2
alsoTriggerOrQueueActionConditional: if createMarker(x=thisActionTarget.x,y=thisActionTarget.y,teamId=self.teamId).nearestUnit(withinRange=40, relation='enemy') != nullUnit and (createMarker(x=thisActionTarget.x,y=thisActionTarget.y,teamId=self.teamId).nearestUnit(withinRange=40, relation='enemy').tags(includes="unit") or createMarker(x=thisActionTarget.x,y=thisActionTarget.y,teamId=self.teamId).nearestUnit(withinRange=40, relation='enemy').tags(includes="building"))

[hiddenAction_yamato_2]
addWaypoint_type: touchTarget
clearAllWaypoints:true
addWaypoint_target_fromReference: createMarker(x=thisActionTarget.x,y=thisActionTarget.y,teamId=self.teamId).nearestUnit(withinRange=40, relation='enemy')
setUnitMemory: yamato=createMarker(x=thisActionTarget.x,y=thisActionTarget.y,teamId=self.teamId).nearestUnit(withinRange=40, relation='enemy')

[hiddenAction_yamato_3]
autoTrigger: if memory.yamato!=nullUnit and memory.yamato.hp>0 and distanceBetween(self, memory.yamato)<=310 and self.energy>=150 and self.resource.lockdown<=0 and self.resource.stasis<=0
addResources:energy=-150
playSoundAtUnit:yamato.wav:0.3
addWaypoint_type: attack
clearAllWaypoints:true
addWaypoint_target_fromReference: memory.yamato
setUnitMemory:yamatoTarget=memory.yamato
alsoQueueAction:yamatoActivate

[hiddenAction_removeYamato]
autoTriggerOnEvent:newWaypointGivenByPlayer
requireConditional: if memory.yamato!=nullUnit
autoTrigger: if (memory.yamato!=nullUnit and (self.energy<150 or memory.yamato.hp<=0)) or (memory.yamato==null and self.ammo>0)
setUnitMemory: yamato=null
setResourcesWithLogic: ammo=0
setUnitStats: maxAttackRange=240

[hiddenAction_yamatoActivate]
tags:yamato
buildSpeed:2s
whenBuilding_cannotMove:true
setResourcesWithLogic: ammo=1
setUnitStats: maxAttackRange=9999
setUnitMemory:yamato=null
addWaypoint_type: attack
clearAllWaypoints:true
addWaypoint_target_fromReference: select(memory.yamatoTarget.parent==nullUnit,memory.yamatoTarget,memory.yamatoTarget.parent)

[hiddenAction_yamato_attackWaypoint]
autoTriggerOnEvent:newWaypointGivenByPlayer
requireConditional: if memory.yamatoTarget!=nullUnit and self.ammo>0
addWaypoint_type: attack
clearAllWaypoints:true
addWaypoint_target_fromReference: select(memory.yamatoTarget.parent==nullUnit,memory.yamatoTarget,memory.yamatoTarget.parent)

[hiddenAction_yamato_theEnd]
autoTrigger: if self.ammo>0 and ((memory.yamatoTarget.hp<=0 and memory.yamato.hp<=0) or (self.resource.lockdown>0 or self.resource.stasis>0))
setUnitMemory: yamatoTarget=null, yamato=null
setResourcesWithLogic: ammo=0
setUnitStats: maxAttackRange=240
clearAllWaypoints:true

[hiddenAction_shootAnim]
setUnitMemory: shootAnim=self.timeAlive

[hiddenAction_armour]
@copyFromSection:template_set_armour
@define armourUpgradeType: TerranAirArmor

[hiddenAction_maxEnergy]
autoTrigger: if self.globalTeamTags(includes='ColossusReactor') and self.maxEnergy!=250
temporarilyAddTags: maxEnergy
setUnitStats: maxEnergy=250

[hiddenAction_startingEnergy]
autoTriggerOnEvent:created
requireConditional: if self.globalTeamTags(includes='ColossusReactor')
setUnitStats:energy=62

[action_portrait]
unitShownInUI:portrait_battlecruiser

[graphics]
image_offsetY:-14
total_frames: 3
icon_build: battlecruiser_icon.png
image:        battlecruiser.png
image_wreak:  NONE
image_turret: NONE
image_shadow: AUTO_ANIMATED
animation_moving_start: 1
animation_moving_end: 2
animation_moving_speed: 2.5
lock_body_rotation_with_main_turret: true
rotate_with_direction: false
animation_direction_units: 45
animation_direction_strideX:3
animation_direction_strideY:0
animation_direction_starting:180
frame_width:  120
frame_height: 120

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
isFixedFiring: true
turretSize: 6
turretTurnSpeed: 3
shootDelay: 1.26s
maxAttackRange:240
showRangeUIGuide:true

[turret_T1T2]
showRangeUIGuide:false
canAttackCondition: if (self.resource(type='TerranAirAttack',equalTo=0) or self.resource(type='TerranAirAttack',equalTo=1)) and self.ammo==0 and self.queueSize==0
x: 0
y: 0
projectile:T1
shoot_flame:NONE
shoot_sound:attack.ogg
shoot_sound_vol:0.3
recoilOffset: 0
barrelY: 35
barrelHeight: 14
onShoot_freezeBodyMovementFor:0.75s
onShoot_triggerActions: shootAnim
altProjectile: T2
altProjectileCondition: if self.resource(type='TerranAirAttack',equalTo=1)

[turret_T3T4]
canAttackCondition: if (self.resource(type='TerranAirAttack',equalTo=2) or self.resource(type='TerranAirAttack',equalTo=3)) and self.ammo==0 and self.queueSize==0
@copyFromSection:turret_T1T2
projectile:T3
altProjectile: T4
altProjectileCondition: if self.resource(type='TerranAirAttack',equalTo=3)

[projectile_T1]
explodeEffect:CUSTOM:sparks
explodeEffectOnShield:CUSTOM:sparks
image:fire.png
directDamage: 205
areaDamage: 265
areaRadius: 82
life: 160
speed:12
mutator1_ifUnitWithTags: zergSwarm
mutator1_directDamageMultiplier:0
mutator2_ifUnitWithTags:hallucination
mutator2_directDamageMultiplier:2

[projectile_T2]
directDamage:210
areaDamage: 270
@copyFromSection:projectile_T1

[projectile_T3]
directDamage:215
areaDamage: 275
@copyFromSection:projectile_T1

[projectile_T4]
directDamage:220
areaDamage: 280
@copyFromSection:projectile_T1

[turret_yamato]
canAttackCondition: if self.ammo>0 and memory.yamatoTarget!=nullUnit and ((memory.yamatoTarget.parent==nullUnit and attacking==memory.yamatoTarget) or (memory.yamatoTarget.parent!=nullUnit and attacking==memory.yamatoTarget.parent))
x: 0
y: 0
warmup:0s
shoot_flame:CUSTOM:yamato_shoot
shoot_sound:attack2.wav
shoot_sound_vol:0.3
recoilOffset: 0
resourceUsage:ammo=1
showRangeUIGuide:false
onShoot_freezeBodyMovementFor:0.75s
barrelY: 35
barrelHeight: 14
projectile:yamato
onShoot_triggerActions: yamato_theEnd

[projectile_yamato]
image:fire2.png
directDamage: 3600
life: 500
speed:12
explodeEffect:CUSTOM:yamatoSparks
explodeEffectOnShield:CUSTOM:yamatoSparks
mutator1_ifUnitWithTags:hallucination
mutator1_directDamageMultiplier:2

[turret_null]
x: 0
y: 0
limitingRange:9999
canAttackCondition: if self.globalTeamTags(includes='GOVNO')
projectile:null
showRangeUIGuide:false

[projectile_null]
life:0
speed:0
invisible: true
directDamage: 0
explodeEffect:NONE
explodeEffectOnShield:NONE

[movement]
movementType: AIR
moveSpeed: 0.64
moveAccelerationSpeed: 0.03
moveDecelerationSpeed: 0.02
maxTurnSpeed: 40
turnAcceleration: 40
reverseSpeedPercentage:0
joinsGroupFormations: false
startingHeightOffset: 35

[ai]
buildPriority: 0.8
noneInBaseExtraPriority: 0.8
noneGlobalExtraPriority: 0.8
maxEachBase: 10

[animation_attack]
onActions:attack
body_0s: {frame:0}
body_0.75s: {frame:0}

[decal_ensnare_goo]
image:ROOT:/DATA/total/ensnare_goo_3.png

[decal_acidSpores]
image:ROOT:/DATA/total/acidSpores_L.png
frame_width:58
frame_height:58

[decal_plague_goo]
image:ROOT:/DATA/total/plague_goo_3.png

[decal_defensive_matrix]
image:ROOT:/DATA/total/defensive_matrix_3.png

[decal_lockdown]
image:ROOT:/DATA/total/lockdown_3.png

[effect_mindControl]
image:ROOT:/DATA/total/mindControl_3.png
frame_width: 128
frame_height: 128

[effect_feedback]
image:ROOT:/DATA/total/feedback_2.png
frame_width: 128
frame_height: 128

[hiddenAction_debuff_maelstrom]
@copyFrom_skipThisSection: true

[hiddenAction_debuff_maelstrom_effect]
@copyFrom_skipThisSection: true

[hiddenAction_removeDebuff_maelstrom]
@copyFrom_skipThisSection: true

[decal_stasis]
image:ROOT:/DATA/total/stasis_2.png
frame_width: 128
frame_height: 128

[effect_restoration]
image:ROOT:/DATA/total/restoration_2.png
frame_width: 128
frame_height: 128



[decal_shoot]
@define dir0: (self.dir>=-22.5 and self.dir<=22.5)
@define dir45: (self.dir>=22.5 and self.dir<=67.5)
@define dir90: (self.dir>=67.5 and self.dir<=112.5)
@define dir135: (self.dir>=112.5 and self.dir<=157.5)
@define dir180: ((self.dir>=157.5 and self.dir<=180) or (self.dir<=-157.5 and self.dir>=-180))
@define dir225: (self.dir<=-112.5 and self.dir>=-157.5)
@define dir270: (self.dir<=-67.5 and self.dir>=-112.5)
@define dir315: (self.dir<=-22.5 and self.dir>=-67.5)
@define totalFrames:5
@define framesPerSec: 12
isVisible: if memory.shootAnim!=0 and self.timeAlive-memory.shootAnim<=1/${framesPerSec}*${totalFrames}
image:shoot.png
frame_width:120
frame_height:120
layer: afterBody
alwaysStartDirAtZero:true
teamColors:false
onlyWhileAlive: true
frame: (select(${dir0},4,select(${dir45},5,select(${dir90},6,select(${dir135},7,select(${dir180},0,select(${dir225},1,select(${dir270},2,select(${dir315},3,0))))))))*${totalFrames})+((self.timeAlive-memory.shootAnim)*${framesPerSec})
yOffsetAbsolute:-14

[decal_yamato]
@define totalFrames:6
@define framesPerSec: 12
isVisible: if self.queueSize(withActionTag="yamato")>0
layer: afterBody
image:yamato_shoot.png
onlyOnNonPreview:true
alwaysStartDirAtZero:true
teamColors:false
yOffsetAbsolute:-14
yOffsetRelative:40
frame_width:160
frame_height:160
frame: self.timeAlive*${framesPerSec}%${totalFrames}
onlyWhileAlive: true

[decal_grn_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByOwnPlayer:true
image:ROOT:/DATA/total/circle_lrg_grn_2.png

[decal_red_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByEnemyPlayer:true
image:ROOT:/DATA/total/circle_lrg_red_2.png

[decal_yellow_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByAllyNotOwnPlayer:true
image:ROOT:/DATA/total/circle_lrg_yell_2.png

[decal_hp]
@copyFromSection: template_customBar
@define totalFrames:23
image:ROOT:/DATA/total/hp_24.png
frame_width:73
frame_height:5
frame:int((self.hp*100/self.maxHp)/(100/${totalFrames}))
yOffsetAbsolute:35

[decal_energy]
@copyFromSection: template_customBar
@define totalFrames:24
onlyWhenSelectedByOwnPlayer:true
onlyWhenSelectedByAnyPlayer:false
image:ROOT:/DATA/total/energy_24.png
frame_width:73
frame_height:5
frame:int((self.energy*100/self.maxEnergy)/(100/${totalFrames}))
yOffsetAbsolute:41