[core]
copyFrom:ROOT:/DATA/Zerg/units/rangeUnits.template, ROOT:/DATA/Zerg/zergUpgrades.template, ROOT:/DATA/total/debuffs.template, ROOT:/DATA/total/customUI.template, ROOT:/DATA/total/unit_portrait.template
overrideAndReplace: heavyHoverTank
name: lurker
tags:M,bio,canConsume,unit,vis17,groundLargeUnit
borrowResourcesWhileAlive:supply=2, displaySupply=-2
price: 0
maxHp: 125
armour:1
mass: 500
displayText_ru: Скрытень
displayText: Lurker
displayText_zh:潜伏者
buildSpeed: 0.005
radius: 22
hideScorchMark: true
displayRadius: 24
transportSlotsNeeded: 4
soundOnMoveOrder: lurker_yes_1.ogg:0.3,lurker_yes_2.ogg:0.3,lurker_yes_3.ogg:0.3,lurker_yes_4.ogg:0.3
soundOnAttackOrder: lurker_yes_1.ogg:0.3,lurker_yes_2.ogg:0.3,lurker_yes_3.ogg:0.3,lurker_yes_4.ogg:0.3
soundOnNewSelection:lurker_what_1.ogg:0.3,lurker_what_2.ogg:0.3,lurker_what_3.ogg:0.3,lurker_what_4.ogg:0.3

[action_burrow]
alwaysSinglePress:true
isVisible: true
isActive: if self.queueSize(equalTo=0) and self.resource.maelstrom<=0 and self.resource.stasis<=0
price: 0
pos: 0.1
buildSpeed: 0s
displayType:infoOnly
text_ru: Зарыться
text: Burrow
text_zh:埋地
iconExtraColor:#FFFFFFFF
iconExtraImage:ROOT:/DATA/Zerg/burrow.png
playSoundAtUnit:lurk.wav:0.3
isLocked: if self.isControlledByAI()
alsoQueueAction:burrow_2
allowMultipleInQueue:false
clearAllWaypoints:true
spawnEffects:CUSTOM:cloud

[hiddenAction_burrow_2]
highPriorityQueue: true
buildSpeed: 0.9s
convertTo: lurkerInvis
whenBuilding_playAnimation:burrow
whenBuilding_cannotMove:true
whenBuilding_temporarilyConvertTo: lurkerVis
convertTo_keepCurrentFields: armour
whenBuilding_temporarilyConvertTo_keepFields: armour
#whenBuilding_rotateTo:0
setBodyRotation: 0
canPlayerCancel:false
clearAllWaypoints:true
resetCustomTimer: true
setResourcesWithLogic:ensnare=0

[effect_corpse]
alwayStartDirAtZero:true
attachedToUnit: false
life: 60
alpha: 6
image: death.png
priority: critical
drawUnderUnits: true
total_frames:6
animateFrameStart:0
animateFrameEnd:5
animateFrameSpeed:0.2
alsoPlaySound:death.wav

[action_portrait]
unitShownInUI:portrait_lurker

[graphics]
image_offsetY:-3
total_frames: 15
icon_build:ROOT:/DATA/Zerg/lurker_icon.png
image:        lurker.png
image_wreak:  dead.png
image_turret: NONE
image_shadow:NONE
animation_moving_start: 0
animation_moving_end: 6
animation_moving_speed: 3
drawLayer:experimentals
showEnergyBar:false
showTransportBar:false
lock_body_rotation_with_main_turret: true
rotate_with_direction: false
animation_direction_units: 45
animation_direction_strideX:0
animation_direction_strideY:1
animation_direction_starting:180
frame_width:  71
frame_height: 66

[attack]
canAttackLandUnits: if self.isControlledByAI()
canAttackFlyingUnits: false
maxAttackRange: 240
shootDelay: 1s

[turret_burrow]
canAttackCondition: if self.isControlledByAI() and self.queueSize==0
showRangeUIGuide:false
x: 0
y: 0
projectile: 1
recoilOffset:0
shoot_flame:NONE
shouldResetTurret:false
onShoot_triggerActions: burrow

[projectile_1]
directDamage: 0
life: 0
speed:0
invisible: true
explodeEffect:NONE
explodeEffectOnShield:NONE

[movement]
moveSpeed: 1.7856

[animation_burrow]
body_0s: {frame:1}
body_0.05s: {frame:2}
body_0.1s: {frame:3} 
body_0.15s: {frame:4}
body_0.2s: {frame:5}
body_0.25s: {frame:1}
body_0.3s: {frame:2}
body_0.35s: {frame:3} 
body_0.4s: {frame:4}
body_0.45s: {frame:5}
body_0.5s: {frame:1}
body_0.55s: {frame:2}
body_0.6s: {frame:3} 
body_0.65s: {frame:4}
body_0.7s: {frame:5}
body_0.75s: {frame:6}
body_0.8s: {frame:7}
body_0.85s: {frame:8}
body_0.9s: {frame:8}

[decal_ensnare_goo]
image:ROOT:/DATA/total/ensnare_goo_2.png

[decal_plague_goo]
image:ROOT:/DATA/total/plague_goo_2.png

[decal_defensive_matrix]
image:ROOT:/DATA/total/defensive_matrix_2.png

[effect_mindControl]
image:ROOT:/DATA/total/mindControl_2.png
frame_width: 64
frame_height: 64

[hiddenAction_feedback_debuff]
@copyFrom_skipThisSection: true

[effect_feedback]
@copyFrom_skipThisSection: true

[decal_maelstrom]
image:ROOT:/DATA/total/maelstrom_2.png
frame_width:  64
frame_height: 64

[decal_grn_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByOwnPlayer:true
image:ROOT:/DATA/total/circle_lrg_grn.png

[decal_red_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByEnemyPlayer:true
image:ROOT:/DATA/total/circle_lrg_red.png

[decal_yellow_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByAllyNotOwnPlayer:true
image:ROOT:/DATA/total/circle_lrg_yell.png

[decal_hp]
@copyFromSection: template_customBar
@define totalFrames:16
image:ROOT:/DATA/total/hp_17.png
frame_width:52
frame_height:5
frame:int((self.hp*100/self.maxHp)/(100/${totalFrames}))
yOffsetAbsolute:23