[core]
copyFrom:ROOT:/DATA/total/forcesAttack.template, ROOT:/DATA/Protoss/protossUpgrades.template, ROOT:/DATA/total/debuffs.template, ROOT:/DATA/total/customUI.template, ROOT:/DATA/total/unit_portrait.template
name: arbiter
tags:L, haveEnergy, mech, unit, arbiter,vis17,canBeHallucinated
class: CustomUnitMetadata
price:Gas=2400
maxHp: 3600
maxShield:2800
armour:1
shieldRegen:0.26
energyStartingPercentage:0.25
shieldDisplayOnlyDeflection:true
energyMax:200
energyRegen:0.0124
mass: 500
displayText_ru: Судья
displayText: Arbiter
displayText_zh:仲裁者
techLevel: 1
buildSpeed: 50s
#availableInDemo: true
radius: 22
hideScorchMark: false
displayRadius: 24
isBio: false
isBug: false
exit_moveAwayAmount:0
fogOfWarSightRange:24
isUnrepairableUnit: true
softCollisionOnAll: 250
effectOnDeath:NONE
soundOnMoveOrder:arbiter_yes.ogg:0.3,arbiter_yes_1.ogg:0.3,arbiter_yes_2.ogg:0.3,arbiter_yes_3.ogg:0.3
soundOnAttackOrder:arbiter_yes.ogg:0.3,arbiter_yes_1.ogg:0.3,arbiter_yes_2.ogg:0.3,arbiter_yes_3.ogg:0.3
soundOnNewSelection:arbiter_what.ogg:0.3,arbiter_what_1.ogg:0.3,arbiter_what_2.ogg:0.3,arbiter_what_3.ogg:0.3

@memory stasis:unit
@memory recall:unit
@global hallucinationUnit:arbiter
@global supplyAdd:4

[hiddenAction_onDestroyed_nonHallucination]
spawnEffects:CUSTOM:corpse

[hiddenAction_Recall]
autoTrigger: if numberOfUnitsInTeam(withTag='recall',withinRange=100,greaterThan=0) and nearestUnit(withinRange=120, withTag='recall', relation='own').customTarget1!=nullUnit
clearAllWaypoints: true
teleportTo: nearestUnit(withinRange=120, withTag='recall', relation='own').customTarget1

[hiddenAction_soundOnCreate]
autoTriggerOnEvent: created
playSoundToPlayer:arbiter_ready.ogg
requireConditional:if self.customTarget1!=nullUnit and customTarget1.tags(includes="building")
addWaypoint_type:move
addWaypoint_target_fromReference: customTarget1.readUnitMemory(name="rally",type="unit")

[effect_sparks]
alwayStartDirAtZero:true
attachedToUnit: false
life: 140
alpha: 14
image: ROOT:/DATA/Protoss/units/spark.png
priority: critical
drawUnderUnits:false
total_frames:14
animateFrameStart:0
animateFrameEnd:13
animateFrameSpeed:0.25

[effect_corpse]
alwayStartDirAtZero:true
attachedToUnit: false
life: 100
alpha: 10
image: ROOT:/DATA/Protoss/death.png
priority: critical
drawUnderUnits:false
total_frames:10
animateFrameStart:0
animateFrameEnd:9
animateFrameSpeed:0.2
frame_width:  190
frame_height: 152
alsoPlaySound:dead.ogg

[effect_recall]
alwayStartDirAtZero:true
attachedToUnit: false
life: 110
alpha: 11
image: recall.png
priority: critical
drawUnderUnits:false
total_frames:11
animateFrameStart:0
animateFrameEnd:10
animateFrameSpeed:0.4
animateFramePingPong: true
frame_width:  100
frame_height: 100

[effect_stasisHit]
alwayStartDirAtZero:true
attachedToUnit: false
life: 90
alpha: 9
image: stasisHit.png
priority: critical
drawUnderUnits:false
total_frames:9
animateFrameStart:0
animateFrameEnd:8
animateFrameSpeed:0.2
frame_width:  128
frame_height: 128

[action_stasisField]
isVisible: if self.globalTeamTags(includes='StasisField') and self.resource.hallucination==0
isActive: if self.resource.lockdown<=0 and self.resource.stasis<=0 and memory.stasis==null
price:energy=100
displayType:infoOnly
buildSpeed:0s
text_ru:Стазисное поле
text:Stasis field
text_zh:停滞立场
isGuiBlinking: if memory.stasis!=null
fireTurretXAtGround:null
fireTurretXAtGround_withProjectile:null
onlyOneUnitAtATime: true
ai_isDisabled: true
iconExtraColor:#FFFFFFFF
iconExtraImage:ROOT:/DATA/Protoss/stasisIcon.png
addResources:energy=100
setUnitMemory: stasis=thisActionTarget
addWaypoint_type: move
clearAllWaypoints:true
addWaypoint_target_fromReference: thisActionTarget

[hiddenAction_stasisField_2]
autoTrigger: if memory.stasis!=nullUnit and distanceBetween(self, memory.stasis)<=310 and self.energy>=100 and self.resource.lockdown<=0 and self.resource.stasis<=0
fireTurretXAtGround:null_2
fireTurretXAtGround_withProjectile:stasis
fireTurretXAtGround_withTarget: memory.stasis
playSoundAtUnit:stasis.ogg:0.5
clearAllWaypoints:true
addResources:energy=-100
setUnitMemory: stasis=null

[hiddenAction_removeStasisField]
autoTriggerOnEvent:newWaypointGivenByPlayer
requireConditional: if memory.stasis!=nullUnit
autoTrigger: if memory.stasis!=nullUnit and self.energy<100
setUnitMemory: stasis=null

[action_stasisField_ai]
price:energy=100
isVisible: if self.globalTeamTags(includes='StasisField') and self.isControlledByAI() and self.resource.hallucination==0
isActive: if self.globalTeamTags(includes='StasisField') and nearestUnit(withinRange=310, withTag='unit', relation='enemy') != nullUnit and self.resource.lockdown<=0 and self.resource.stasis<=0
displayType:infoOnly
buildSpeed:0s
text_ru:Стазисное поле
text:Stasis field
text_zh:停滞立场
onlyOneUnitAtATime: true
fireTurretXAtGround: null_2
fireTurretXAtGround_withProjectile:stasis
fireTurretXAtGround_withTarget: nearestUnit(withinRange=320, withTag='unit', relation='enemy')
playSoundAtUnit:stasis.ogg:0.5
ai_isHighPriority: true
iconExtraColor:#FFFFFFFF
iconExtraImage:ROOT:/DATA/Protoss/stasisIcon.png

[action_recallAbility]
price:energy=150
isVisible: if self.globalTeamTags(includes='Recall') and self.resource.hallucination==0
isActive: if self.resource.lockdown<=0 and self.resource.stasis<=0
displayType:infoOnly
buildSpeed:0s
text_ru:Телепортация
text: Recall
fireTurretXAtGround: null_2
fireTurretXAtGround_withProjectile:recall
whenBuilding_cannotMove:true
onlyOneUnitAtATime: true
ai_isDisabled: true
spawnEffects:CUSTOM:recall
iconExtraColor:#FFFFFFFF
iconExtraImage:ROOT:/DATA/Protoss/recallIcon.png

[hiddenAction_armour]
@copyFromSection:template_set_shieldArmour
@define armourUpgradeType: ProtossAirArmor

[hiddenAction_maxEnergy]
autoTrigger: if self.globalTeamTags(includes='KhaydarinCore') and self.maxEnergy!=250 and self.resource.hallucination==0
temporarilyAddTags: maxEnergy
setUnitStats: maxEnergy=250

[hiddenAction_startingEnergy]
autoTriggerOnEvent:created
requireConditional: if self.globalTeamTags(includes='KhaydarinCore') and self.resource.hallucination==0
setUnitStats:energy=62

[action_portrait]
unitShownInUI:portrait_arbiter

[graphics]
image_offsetY:-10
total_frames: 2
icon_build: arbiter_icon.png
image:        arbiter.png
image_wreak:  NONE
image_turret: NONE
image_shadow: AUTO_ANIMATED
animation_moving_start: 1
animation_moving_end: 2
animation_moving_speed: 2.5
lock_body_rotation_with_main_turret: true
rotate_with_direction: false
animation_direction_units: 45
animation_direction_strideX:3
animation_direction_strideY:0
animation_direction_starting:180
frame_width:  76
frame_height: 76
imageScale: 1.6

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
isFixedFiring: true
turretSize: 6
turretTurnSpeed: 3
maxAttackRange: 285
shootDelay: 1.89s
showRangeUIGuide:true

[turret_T1T2]
showRangeUIGuide:false
canAttackCondition: if self.resource(type='ProtossAirAttack',equalTo=0) or self.resource(type='ProtossAirAttack',equalTo=1)
x: 0
y: 0
shoot_sound:attack.ogg
shoot_sound_vol:0.3
recoilOffset: 0
#barrelHeight: 10
shoot_flame:NONE
projectile:T1
altProjectile: T2
altProjectileCondition: if self.resource(type='ProtossAirAttack',equalTo=1)

[turret_T3T4]
canAttackCondition: if self.resource(type='ProtossAirAttack',equalTo=2) or self.resource(type='ProtossAirAttack',equalTo=3)
@copyFromSection:turret_T1T2
projectile:T3
altProjectile: T4
altProjectileCondition: if self.resource(type='ProtossAirAttack',equalTo=3)

[projectile_T1]
areaDamage: 420
areaRadius: 65
life: 160
speed: 4
targetSpeed: 8
image:bomb.png
explodeEffect:CUSTOM:sparks
explodeEffectOnShield:CUSTOM:sparks
mutator1_ifUnitWithTags:M
mutator1_ifUnitWithoutTags:haveShield
mutator1_directDamageMultiplier:0.75
mutator2_ifUnitWithTags:S
mutator2_ifUnitWithoutTags:haveShield
mutator2_directDamageMultiplier:0.5
mutator3_ifUnitWithTags: zergSwarm
mutator3_directDamageMultiplier:0
mutator4_ifUnitWithTags:hallucination
mutator4_directDamageMultiplier:2

[projectile_T2]
directDamage:15
areaDamage: 420
@copyFromSection:projectile_T1

[projectile_T3]
directDamage:30
areaDamage: 420
@copyFromSection:projectile_T1

[projectile_T4]
directDamage:45
areaDamage: 420
@copyFromSection:projectile_T1

[turret_null]
x: 0
y: 0
limitingRange:9999
recoilOffset: 0
shoot_flame:NONE
showRangeUIGuide:false
canAttackCondition: if self.globalTeamTags(includes='GOVNO')

[turret_null_2]
x: 0
y: 0
limitingRange:9999
recoilOffset: 0
shoot_flame:NONE
showRangeUIGuide:false
canAttackCondition: if self.globalTeamTags(includes='GOVNO')
onShoot_freezeBodyMovementFor:0.63s

[projectile_null]
directDamage: 0
life: 0
speed: 0
invisible:true
explodeEffect:NONE

[projectile_stasis]
areaDamage:0
areaRadius:80
areaDamageNoFalloff: true
areaHitAirAndLandAtSameTime: true
friendlyFire: true
targetGround: true
life: 10
instant:true
invisible:true
explodeEffect:CUSTOM:stasisHit
mutator1_ifUnitWithTags:S,M,L
mutator1_areaDamageMultiplier: 0
mutator1_addResourcesAreaHit: stasis=44

[projectile_recall]
life: 20
instant: true
drawSize: 0
areaDamage: 0
areaRadius: 120
targetGround: true
spawnUnit:recall
explodeEffect:NONE
friendlyFire: only-ignoreEnemy
areaDamageNoFalloff: true
areaHitAirAndLandAtSameTime: true

[movement]
movementType: AIR
moveSpeed: 0.98
moveAccelerationSpeed: 0.03
moveDecelerationSpeed: 0.02
maxTurnSpeed: 40
turnAcceleration: 40
reverseSpeedPercentage:0
joinsGroupFormations: false
startingHeightOffset: 35

[ai]
buildPriority: 0.8
noneInBaseExtraPriority: 0.8
noneGlobalExtraPriority: 0.8
maxEachBase: 10

[decal_hallucination_texture]
@copyFromSection: template_hallucination_texture
@define totalFrames:3
image: arbiter_illusion.png

[decal_hallucination_energy]
@define totalFrames:12
image:ROOT:/DATA/total/energy_12.png
frame_width:37
frame_height:5
yOffsetAbsolute:30

[decal_ensnare_goo]
image:ROOT:/DATA/total/ensnare_goo_3.png

[decal_plague_goo]
image:ROOT:/DATA/total/plague_goo_3.png

[decal_acidSpores]
image:ROOT:/DATA/total/acidSpores_L.png
frame_width:58
frame_height:58

[decal_defensive_matrix]
image:ROOT:/DATA/total/defensive_matrix_3.png

[decal_lockdown]
image:ROOT:/DATA/total/lockdown_3.png

[effect_mindControl]
image:ROOT:/DATA/total/mindControl_3.png
frame_width: 128
frame_height: 128

[effect_feedback]
image:ROOT:/DATA/total/feedback_2.png
frame_width: 128
frame_height: 128

[hiddenAction_debuff_maelstrom]
@copyFrom_skipThisSection: true

[hiddenAction_debuff_maelstrom_effect]
@copyFrom_skipThisSection: true

[hiddenAction_removeDebuff_maelstrom]
@copyFrom_skipThisSection: true

[decal_grn_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByOwnPlayer:true
image:ROOT:/DATA/total/circle_lrg_grn.png

[decal_red_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByEnemyPlayer:true
image:ROOT:/DATA/total/circle_lrg_red.png

[decal_yellow_circle]
@copyFromSection: template_customSelectCircle
onlyWhenSelectedByAllyNotOwnPlayer:true
image:ROOT:/DATA/total/circle_lrg_yell.png

[decal_hp]
@copyFromSection: template_customBar
@define totalFrames:11
image:ROOT:/DATA/total/hp_p12.png
frame_width:37
frame_height:7
frame:int((self.hp*100/self.maxHp)/(100/${totalFrames}))
yOffsetAbsolute:23

[decal_shield]
@copyFromSection: template_customBar
@define totalFrames:11
image:ROOT:/DATA/total/shield_p12.png
frame_width:37
frame_height:7
frame:int((self.shield*100/self.maxShield)/(100/${totalFrames}))
yOffsetAbsolute:23

[decal_energy]
@copyFromSection: template_customBar
@define totalFrames:12
isVisible: if self.maxEnergy>0
onlyWhenSelectedByOwnPlayer:true
onlyWhenSelectedByAnyPlayer:false
image:ROOT:/DATA/total/energy_12.png
frame_width:37
frame_height:5
frame:int((self.energy*100/self.maxEnergy)/(100/${totalFrames}))
yOffsetAbsolute:30